import { resolve, dirname, isAbsolute, relative } from 'path';
import { fileURLToPath } from 'url';
import { readFile } from 'fs/promises';
import { existsSync, lstatSync } from 'fs';
import chokidar from 'chokidar';
import { minimatch } from 'minimatch';
import type { CompileOptions } from '../types.js';
import type {
  Logger,
  PromptScriptConfig,
  TargetEntry,
  TargetConfig,
  BuildProfileConfig,
  Lockfile,
} from '@promptscript/core';
import { ErrorCode, isValidLockfile, PSError } from '@promptscript/core';

import type { CompileResult, FormatterOutput, OutputPlan } from '@promptscript/compiler';
import { loadEffectiveConfig, CONFIG_FILES } from '../config/loader.js';
import { resolvePrettierOptions } from '../prettier/loader.js';
import { postFormatWithPrettier } from '../prettier/post-format.js';
import { createSpinner, ConsoleOutput, isVerbose, isDebug } from '../output/console.js';
import { Compiler } from '@promptscript/compiler';
import { isTTY } from '../output/pager.js';
import { type CliServices, createDefaultServices } from '../services.js';
import { resolveRegistryPath } from '../utils/registry-resolver.js';
import { parse as parseYaml } from 'yaml';
import { stripMarkers } from '../utils/markers.js';
import {
  detectOutputConflicts,
  isPathInsideDir,
  validateOutputPath,
} from '../utils/conflict-detector.js';
import {
  cleanupManagedOutputs,
  createHookOutputSafely,
  isHookOutputPath,
  isPromptScriptOwnedHookOutput,
  mergePromptScriptCodexConfig,
  mergePromptScriptHookOutput,
  removeHookOutputIfUnchanged,
  removePromptScriptOwnedCodexHooks,
  rewriteHookOutputIfUnchanged,
} from '../utils/managed-output-cleanup.js';
import {
  detectLegacyFactorySettingsHooks,
  planLegacyFactoryHooksMigration,
  type LegacyFactoryMigrationPlan,
} from '../utils/legacy-factory-hooks.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Resolve and read the bundled PromptScript SKILL.md.
 * Uses the same dual-candidate pattern as init.ts to handle both
 * development (packages/cli/skills/...) and bundled (dist/packages/cli/skills/...) modes.
 * Returns the content string, or undefined if the file is missing.
 */
async function loadBundledSkillContent(logger: Logger): Promise<string | undefined> {
  const skillRelPath = 'skills/promptscript/SKILL.md';
  const candidates = [
    resolve(__dirname, skillRelPath), // bundled: dist/packages/cli/skills/...
    resolve(__dirname, '..', '..', skillRelPath), // dev: packages/cli/skills/...
  ];

  for (const candidate of candidates) {
    if (existsSync(candidate)) {
      try {
        const content = await readFile(candidate, 'utf-8');
        logger.debug(
          `Loaded bundled PromptScript skill from ${candidate} (${content.length} bytes)`
        );
        return content;
      } catch {
        continue;
      }
    }
  }

  logger.verbose('Warning: Could not load bundled PromptScript SKILL.md — skill injection skipped');
  return undefined;
}

async function loadCompileLockfile(
  projectRoot: string,
  logger: Logger
): Promise<Lockfile | undefined> {
  const lockfilePath = resolve(projectRoot, 'promptscript.lock');
  if (!existsSync(lockfilePath)) {
    return undefined;
  }
  try {
    const lockfileContent = await readFile(lockfilePath, 'utf-8');
    const parsed: unknown = parseYaml(lockfileContent, { maxAliasCount: 100 });
    if (!isValidLockfile(parsed)) {
      throw new Error(`Invalid lockfile: ${lockfilePath}`);
    }
    logger.verbose(`Loaded lockfile from ${lockfilePath}`);
    return parsed;
  } catch (error) {
    throw new Error(`Unable to read lockfile: ${lockfilePath}`, { cause: error });
  }
}

/**
 * Find a config file in the given directory by checking all known config file names.
 */
function findConfigInDir(dir: string): string | undefined {
  for (const file of CONFIG_FILES) {
    const fullPath = resolve(dir, file);
    if (existsSync(fullPath)) {
      return fullPath;
    }
  }
  return undefined;
}

/**
 * Markers that identify files generated by PromptScript.
 * We check the first 50 lines of a file for any of these markers.
 */
const PROMPTSCRIPT_MARKERS = [
  '<!-- PromptScript', // HTML comment marker (files without frontmatter)
  '# promptscript-generated:', // YAML comment marker (files with frontmatter)
  '> Auto-generated by PromptScript', // Legacy - for backwards compatibility
];

function applyConfiguredHeader(
  outputs: Map<string, FormatterOutput>,
  header: string | undefined
): void {
  const normalizedHeader = header?.trim();
  if (!normalizedHeader) return;

  for (const output of outputs.values()) {
    const lines = output.content.split('\n');
    const markerIndex = lines.findIndex((line) =>
      PROMPTSCRIPT_MARKERS.some((marker) => line.includes(marker))
    );
    if (markerIndex === -1) continue;

    let insertionIndex = markerIndex + 1;
    if (lines[0] === '---') {
      const frontmatterEnd = lines.indexOf('---', 1);
      if (frontmatterEnd !== -1) {
        insertionIndex = frontmatterEnd + 1;
      }
    }

    lines.splice(insertionIndex, 0, '', normalizedHeader);
    output.content = lines.join('\n');
  }
}

/**
 * Create a logger that outputs to ConsoleOutput based on log level.
 */
function createCliLogger(): Logger {
  return {
    verbose: (message: string) => {
      if (isVerbose() || isDebug()) {
        ConsoleOutput.verbose(message);
      }
    },
    debug: (message: string) => {
      if (isDebug()) {
        ConsoleOutput.debug(message);
      }
    },
    warn: (message: string) => {
      ConsoleOutput.warn(message);
    },
  };
}

/**
 * Parse target entries into compiler format.
 * Filters out targets with enabled: false.
 */
function parseTargets(targets: TargetEntry[]): { name: string; config?: TargetConfig }[] {
  return targets
    .map((entry) => {
      if (typeof entry === 'string') {
        return { name: entry };
      }
      // Object format: { github: { convention: 'xml' } }
      const entries = Object.entries(entry);
      if (entries.length === 0) {
        throw new Error('Empty target configuration');
      }
      const [name, config] = entries[0] as [string, TargetConfig | undefined];
      return { name, config };
    })
    .filter((target) => target.config?.enabled !== false);
}

function getBuildProfile(
  config: PromptScriptConfig,
  buildName: string | undefined
): BuildProfileConfig | undefined {
  if (!buildName) return undefined;

  const profile = config.builds?.[buildName];
  if (!profile) {
    const available = Object.keys(config.builds ?? {});
    const suffix =
      available.length > 0 ? ` Available build profiles: ${available.join(', ')}.` : '';
    throw new Error(`Unknown build profile: ${buildName}.${suffix}`);
  }

  return profile;
}

function resolveOutputBase(projectRoot: string, output: string | undefined): string {
  if (!output) return projectRoot;
  return isAbsolute(output) ? output : resolve(projectRoot, output);
}

function resolveProjectPath(projectRoot: string, path: string): string {
  return isAbsolute(path) ? path : resolve(projectRoot, path);
}

function validateWritePathSymlinks(outputPath: string, outputRoot: string): string | undefined {
  const root = resolve(outputRoot);
  const candidate = resolve(root, outputPath);
  const relativePath = relative(root, candidate);
  if (relativePath === '' || relativePath.startsWith('..') || isAbsolute(relativePath)) return;

  let current = root;
  for (const segment of relativePath.split(/[\\/]/)) {
    current = resolve(current, segment);
    let stat: ReturnType<typeof lstatSync> | undefined;
    try {
      stat = lstatSync(current);
    } catch (error: unknown) {
      if (
        error instanceof Error &&
        'code' in error &&
        (error as NodeJS.ErrnoException).code === 'ENOENT'
      ) {
        break;
      }
      return `Output path "${outputPath}" cannot be checked for symbolic links`;
    }
    if (stat?.isSymbolicLink()) {
      return `Output path "${outputPath}" traverses a symbolic link`;
    }
  }
  return undefined;
}

function resolveCompileConfigPath(
  projectRoot: string,
  options: Pick<CompileOptions, 'config' | 'cwd'>
): string | undefined {
  if (options.config) {
    return resolveProjectPath(projectRoot, options.config);
  }

  const environmentConfig = process.env['PROMPTSCRIPT_CONFIG'];
  if (options.cwd && environmentConfig) {
    return resolveProjectPath(projectRoot, environmentConfig);
  }

  const configPath = options.cwd ? findConfigInDir(projectRoot) : undefined;
  if (options.cwd && !configPath) {
    throw new Error(`No PromptScript configuration found in ${projectRoot}. Run: prs init`);
  }
  return configPath;
}

/**
 * Check if content was generated by PromptScript by looking for markers in the first 50 lines.
 * Extended from 20 to 50 to handle SKILL.md files with long YAML frontmatter
 * (compatibility lists, allowed-tools, etc. can push the marker past line 40).
 */
function hasPromptScriptMarker(content: string): boolean {
  const lines = content.split('\n').slice(0, 50);
  return lines.some((line) => PROMPTSCRIPT_MARKERS.some((marker) => line.includes(marker)));
}

function isPromptScriptOwnedOutput(path: string, content: string): boolean {
  if (isHookOutputPath(path)) {
    return isPromptScriptOwnedHookOutput(path, content);
  }
  return hasPromptScriptMarker(content);
}

/**
 * Read a file, returning undefined when it cannot be read.
 * Unreadable files fall through to overwrite protection.
 */
async function readFileOrUndefined(filePath: string): Promise<string | undefined> {
  try {
    return await readFile(filePath, 'utf-8');
  } catch {
    return undefined;
  }
}

/**
 * User response when prompted about overwriting a file.
 */
type OverwriteResponse = 'yes' | 'no' | 'all';

/**
 * Prompt the user about overwriting a file.
 * Returns 'yes' to overwrite this file, 'no' to skip, 'all' to overwrite all remaining.
 */
async function promptForOverwrite(
  filePath: string,
  services: CliServices
): Promise<OverwriteResponse> {
  const response = await services.prompts.select({
    message: `File exists and was not generated by PromptScript: ${filePath}\nOverwrite?`,
    choices: [
      { name: 'No (skip this file)', value: 'no' as const },
      { name: 'Yes (overwrite this file)', value: 'yes' as const },
      { name: 'All (overwrite all remaining files)', value: 'all' as const },
    ],
    default: 'no' as const,
  });
  return response;
}

/**
 * Resolve universalDir config to NativeSkillOptions.
 * Default (undefined/true) → '.agents', false → disabled, string → custom path.
 */
function resolveUniversalDir(
  universalDir: string | boolean | undefined
): { universalDir: string } | undefined {
  if (universalDir === false) return undefined;
  if (typeof universalDir === 'string') return { universalDir };
  // Default: enabled with '.agents'
  return { universalDir: '.agents' };
}

/**
 * Result of writing outputs.
 */
interface WriteResult {
  written: string[];
  created: string[];
  skipped: string[];
  unchanged: string[];
}

function getPlannedOutputs(
  outputs: Map<string, FormatterOutput>,
  outputPlan: OutputPlan | undefined
): FormatterOutput[] {
  if (!outputPlan) return [...outputs.values()];

  const plannedPaths = new Set<string>();
  const planned = outputPlan.files.map((file) => {
    plannedPaths.add(file.path);
    const current = outputs.get(file.path);
    return {
      path: file.path,
      content: current?.content ?? file.content,
      ...(current?.mode !== undefined
        ? { mode: current.mode }
        : file.mode !== undefined
          ? { mode: file.mode }
          : {}),
      ...(current?.merge !== undefined
        ? { merge: current.merge }
        : file.merge !== undefined
          ? { merge: file.merge }
          : {}),
      ...(current?.managedOutputDirectories !== undefined
        ? { managedOutputDirectories: current.managedOutputDirectories }
        : file.managedOutputDirectories !== undefined
          ? { managedOutputDirectories: file.managedOutputDirectories }
          : {}),
      ...(current?.managedOutputFiles !== undefined
        ? { managedOutputFiles: current.managedOutputFiles }
        : file.managedOutputFiles !== undefined
          ? { managedOutputFiles: file.managedOutputFiles }
          : {}),
    };
  });

  // Legacy callers may add a migration output after compilation. Preserve it
  // while ensuring formatter outputs always follow the shared plan.
  for (const output of outputs.values()) {
    if (!plannedPaths.has(output.path)) planned.push(output);
  }
  return planned;
}

async function prepareLegacyFactoryMigration(
  outputs: Map<string, FormatterOutput>,
  outputRoot: string
): Promise<LegacyFactoryMigrationPlan | undefined> {
  const factoryOutput = outputs.get('.factory/hooks.json');
  const plan = await planLegacyFactoryHooksMigration(outputRoot, factoryOutput?.content);
  if (!plan) return undefined;
  if (plan.migration.ambiguous.length > 0) {
    throw new Error(
      `Cannot migrate legacy Factory hooks safely. Review these entries in ${plan.settingsPath}: ` +
        plan.migration.ambiguous.join(', ')
    );
  }
  if (!plan.migration.changed) return undefined;

  const content = JSON.stringify(plan.migration.canonical, null, 2) + '\n';
  if (factoryOutput) {
    factoryOutput.content = content;
  } else {
    outputs.set('.factory/hooks.json', {
      path: '.factory/hooks.json',
      content,
    });
  }
  return plan;
}

async function finishLegacyFactoryMigration(
  plan: LegacyFactoryMigrationPlan,
  outputRoot: string,
  dryRun: boolean | undefined,
  canonicalCreated: boolean
): Promise<void> {
  const action =
    plan.migration.migrated > 0
      ? `migrate ${plan.migration.migrated} legacy Factory hook(s)`
      : 'remove legacy PromptScript-owned Factory hooks';
  if (dryRun) {
    ConsoleOutput.dryRun(`Would ${action} from ${plan.settingsPath} to ${plan.hooksPath}`);
    return;
  }

  const content = JSON.stringify(plan.migration.legacy, null, 2) + '\n';
  const rewritten = await rewriteHookOutputIfUnchanged(
    plan.settingsPath,
    outputRoot,
    plan.expectedSettingsContent,
    content
  );
  if (!rewritten) {
    const canonicalContent = JSON.stringify(plan.migration.canonical, null, 2) + '\n';
    const rolledBack =
      canonicalCreated &&
      (await removeHookOutputIfUnchanged(plan.hooksPath, outputRoot, canonicalContent));
    throw new Error(
      `Legacy Factory settings changed during compilation. ` +
        (rolledBack
          ? 'The canonical migration output was rolled back. '
          : `Review ${plan.hooksPath} for a partial migration. `) +
        `Review ${plan.settingsPath} and rerun.`
    );
  }
  const canonicalContent = JSON.stringify(plan.migration.canonical, null, 2) + '\n';
  const canonicalVerified = await rewriteHookOutputIfUnchanged(
    plan.hooksPath,
    outputRoot,
    canonicalContent,
    canonicalContent
  );
  if (!canonicalVerified) {
    const settingsRestored = await rewriteHookOutputIfUnchanged(
      plan.settingsPath,
      outputRoot,
      content,
      plan.expectedSettingsContent
    );
    throw new Error(
      `Canonical Factory hooks changed during migration. ` +
        (settingsRestored
          ? 'The legacy settings were restored. '
          : `Review ${plan.settingsPath} for a partial migration. `) +
        `Review ${plan.hooksPath} and rerun.`
    );
  }
  // A settings file whose only content was the migrated hooks section carries no
  // user configuration, so an empty `{}` would be left behind for good.
  if (Object.keys(plan.migration.legacy).length === 0) {
    const removed = await removeHookOutputIfUnchanged(plan.settingsPath, outputRoot, content);
    if (removed) {
      ConsoleOutput.muted(`Removed empty legacy settings: ${plan.settingsPath}`);
    } else {
      ConsoleOutput.warning(
        `Left an empty ${plan.settingsPath} behind - remove it manually if it is not needed.`
      );
    }
  }
  ConsoleOutput.success(`${action[0]!.toUpperCase()}${action.slice(1)}`);
}

/**
 * Print compilation errors to console.
 */
function printErrors(errors: CompileResult['errors']): void {
  for (const err of errors) {
    ConsoleOutput.error(err.message);
    if (err.location) {
      ConsoleOutput.muted(`at ${err.location.file}:${err.location.line}:${err.location.column}`);
    }
  }
}

/**
 * Write output files to disk or show dry-run preview.
 * Handles overwrite protection for user files.
 */
async function writeOutputs(
  outputs: Map<string, FormatterOutput>,
  options: CompileOptions,
  _config: PromptScriptConfig,
  services: CliServices,
  outputPlan?: OutputPlan
): Promise<WriteResult> {
  const result: WriteResult = { written: [], created: [], skipped: [], unchanged: [] };
  let overwriteAll = false;
  const conflicts: string[] = [];
  const targetErrors: string[] = [];
  const plannedOutputs = getPlannedOutputs(outputs, outputPlan);

  // Pre-flight: a target `output` comes from the config file, so a checked-in
  // path may point anywhere the user can write. Reject the whole run before
  // writing anything rather than planting files outside the output directory.
  const outputRoot = options.output ?? process.cwd();
  const escaping = plannedOutputs
    .flatMap((output) => [
      validateOutputPath(output.path, outputRoot),
      validateWritePathSymlinks(output.path, outputRoot),
    ])
    .filter((message): message is string => message !== undefined);
  if (escaping.length > 0) {
    throw new PSError(
      `Refusing to write outside the output directory:\n${escaping.map((m) => `  - ${m}`).join('\n')}`,
      ErrorCode.INVALID_PATH
    );
  }

  // Pre-flight: in non-interactive mode without --force, detect every
  // ownership conflict before writing anything so a refused overwrite cannot
  // leave a half-written set of outputs behind. The in-loop conflict handling
  // below stays as a backstop against files changed after this check.
  if (!options.dryRun && !options.force && !isTTY()) {
    const preflightConflicts: string[] = [];
    for (const output of plannedOutputs) {
      const outputPath = options.output
        ? resolve(options.output, output.path)
        : resolve(output.path);
      if (!existsSync(outputPath)) continue;
      const existingContent = await readFileOrUndefined(outputPath);
      const contentMatches =
        existingContent !== undefined &&
        stripMarkers(existingContent) === stripMarkers(output.content);
      if (contentMatches) continue;
      const existingHookOutputOwned =
        existingContent !== undefined &&
        isPromptScriptOwnedHookOutput(output.path, existingContent);
      const prunedCodexConfig =
        existingContent === undefined
          ? undefined
          : removePromptScriptOwnedCodexHooks(output.path, existingContent);
      const migratedCodexContent =
        prunedCodexConfig === undefined
          ? undefined
          : prunedCodexConfig.empty
            ? output.content
            : mergePromptScriptCodexConfig(prunedCodexConfig.content, output.content);
      const mergedHookContent =
        existingContent === undefined || existingHookOutputOwned
          ? undefined
          : (mergePromptScriptHookOutput(output.path, existingContent, output.content) ??
            migratedCodexContent);
      if (mergedHookContent !== undefined || existingHookOutputOwned) continue;
      if (existingContent !== undefined && isPromptScriptOwnedOutput(output.path, existingContent))
        continue;
      preflightConflicts.push(outputPath);
    }
    if (preflightConflicts.length > 0) {
      const fileList = preflightConflicts.map((f) => `  - ${f}`).join('\n');
      throw new Error(
        `Cannot overwrite files not generated by PromptScript in non-interactive mode:\n${fileList}\n\nUse --force to overwrite these files.`
      );
    }
  }

  async function safeOverwrite(
    output: FormatterOutput,
    outputPath: string,
    existingContent: string | undefined,
    content: string
  ): Promise<boolean> {
    const outputRoot = options.output ? resolve(options.output) : process.cwd();
    const rewritten =
      existingContent !== undefined &&
      (await rewriteHookOutputIfUnchanged(
        outputPath,
        outputRoot,
        existingContent,
        content,
        output.mode
      ));
    if (!rewritten) {
      const msg =
        existingContent === undefined
          ? `Skipped '${outputPath}' because it exists but could not be read.`
          : isHookOutputPath(output.path)
            ? `Skipped '${outputPath}' because it changed while PromptScript was writing hooks.`
            : `Skipped '${outputPath}' because it changed or became unsafe while PromptScript was writing it.`;
      targetErrors.push(msg);
      ConsoleOutput.error(msg);
    }
    return rewritten;
  }

  async function safeCreate(
    output: FormatterOutput,
    outputPath: string,
    content: string
  ): Promise<boolean> {
    const outputRoot = options.output ? resolve(options.output) : process.cwd();
    const created = await createHookOutputSafely(outputPath, outputRoot, content, output.mode);
    if (!created) {
      const msg = `Skipped '${outputPath}' because its output path was not safe to create.`;
      targetErrors.push(msg);
      ConsoleOutput.error(msg);
    }
    return created;
  }

  for (const output of plannedOutputs) {
    const outputPath = options.output ? resolve(options.output, output.path) : resolve(output.path);

    // Check if file exists
    const fileExists = existsSync(outputPath);
    const existingContent = fileExists ? await readFileOrUndefined(outputPath) : undefined;
    const existingHookOutputOwned =
      existingContent !== undefined && isPromptScriptOwnedHookOutput(output.path, existingContent);
    const prunedCodexConfig =
      existingContent === undefined
        ? undefined
        : removePromptScriptOwnedCodexHooks(output.path, existingContent);
    const migratedCodexContent =
      prunedCodexConfig === undefined
        ? undefined
        : prunedCodexConfig.empty
          ? output.content
          : mergePromptScriptCodexConfig(prunedCodexConfig.content, output.content);
    const mergedHookContent =
      existingContent === undefined || existingHookOutputOwned
        ? undefined
        : (mergePromptScriptHookOutput(output.path, existingContent, output.content) ??
          migratedCodexContent);
    const desiredContent =
      existingContent === undefined ? output.content : (mergedHookContent ?? output.content);

    // A file is up to date when it differs from the new output only by the
    // generation marker. Rewriting such a file would change nothing but the
    // marker timestamp, so it is skipped in every mode, including --force.
    const contentMatches =
      existingContent !== undefined &&
      stripMarkers(existingContent) === stripMarkers(desiredContent);

    if (options.dryRun) {
      // In dry-run mode, show what would happen
      if (!fileExists) {
        ConsoleOutput.dryRun(`Would write: ${outputPath}`);
        result.written.push(outputPath);
      } else if (contentMatches) {
        ConsoleOutput.dryRun(`Unchanged: ${outputPath}`);
        result.unchanged.push(outputPath);
      } else if (
        existingContent !== undefined &&
        (mergedHookContent !== undefined || isPromptScriptOwnedOutput(output.path, existingContent))
      ) {
        ConsoleOutput.dryRun(`Would overwrite: ${outputPath}`);
        result.written.push(outputPath);
      } else {
        ConsoleOutput.warning(`Would conflict: ${outputPath} (not generated by PromptScript)`);
        result.written.push(outputPath);
      }
      continue;
    }

    // File doesn't exist - write normally
    if (!fileExists) {
      if (await safeCreate(output, outputPath, desiredContent)) {
        ConsoleOutput.success(outputPath);
        result.written.push(outputPath);
        result.created.push(outputPath);
      }
      continue;
    }

    // Nothing but the marker would change - keep the file (and its timestamp)
    if (contentMatches) {
      if (output.mode !== undefined && existingContent !== undefined) {
        const modeUpdated = await rewriteHookOutputIfUnchanged(
          outputPath,
          options.output ? resolve(options.output) : process.cwd(),
          existingContent,
          existingContent,
          output.mode
        );
        if (!modeUpdated) {
          const msg = `Skipped '${outputPath}' because it changed or became unsafe while PromptScript was updating its mode.`;
          targetErrors.push(msg);
          ConsoleOutput.error(msg);
          continue;
        }
      }
      ConsoleOutput.unchanged(outputPath);
      result.unchanged.push(outputPath);
      continue;
    }

    if (mergedHookContent !== undefined) {
      if (await safeOverwrite(output, outputPath, existingContent, desiredContent)) {
        ConsoleOutput.success(outputPath);
        result.written.push(outputPath);
      }
      continue;
    }

    // File exists - check if it was generated by PromptScript
    if (existingContent !== undefined && isPromptScriptOwnedOutput(output.path, existingContent)) {
      // Content changed - write with new marker
      if (await safeOverwrite(output, outputPath, existingContent, desiredContent)) {
        ConsoleOutput.success(outputPath);
        result.written.push(outputPath);
      }
      continue;
    }

    // Content differs or can't be read — could be a resource file we wrote before
    // or a user-created file (needs protection). Check for --force flag or overwriteAll.
    if (options.force || overwriteAll) {
      if (await safeOverwrite(output, outputPath, existingContent, desiredContent)) {
        ConsoleOutput.success(outputPath);
        result.written.push(outputPath);
      }
      continue;
    }

    // Check if we're in an interactive terminal
    if (!isTTY()) {
      // Non-interactive mode - collect conflicts for error
      conflicts.push(outputPath);
      continue;
    }

    // Interactive mode - prompt user
    const response = await promptForOverwrite(outputPath, services);

    switch (response) {
      case 'yes':
        if (await safeOverwrite(output, outputPath, existingContent, desiredContent)) {
          ConsoleOutput.success(outputPath);
          result.written.push(outputPath);
        }
        break;
      case 'no':
        ConsoleOutput.skipped(outputPath);
        result.skipped.push(outputPath);
        break;
      case 'all':
        overwriteAll = true;
        if (await safeOverwrite(output, outputPath, existingContent, desiredContent)) {
          ConsoleOutput.success(outputPath);
          result.written.push(outputPath);
        }
        break;
    }
  }

  // If there were target-level filesystem errors, fail
  if (targetErrors.length > 0) {
    throw new Error(
      `Some targets failed to write output:\n${targetErrors.map((e) => `  - ${e}`).join('\n')}`
    );
  }

  // If there were conflicts in non-interactive mode, fail with error
  if (conflicts.length > 0) {
    const fileList = conflicts.map((f) => `  - ${f}`).join('\n');
    throw new Error(
      `Cannot overwrite files not generated by PromptScript in non-interactive mode:\n${fileList}\n\nUse --force to overwrite these files.`
    );
  }

  return result;
}

/**
 * Print compilation stats.
 */
function printStats(stats: CompileResult['stats']): void {
  ConsoleOutput.newline();
  ConsoleOutput.stats(
    `Stats: ${stats.totalTime}ms ` +
      `(resolve: ${stats.resolveTime}ms, ` +
      `validate: ${stats.validateTime}ms, ` +
      `format: ${stats.formatTime}ms)`
  );
}

/**
 * Print compilation warnings.
 */
function printWarnings(warnings: CompileResult['warnings']): void {
  if (warnings.length > 0) {
    ConsoleOutput.newline();
    console.log(`Warnings (${warnings.length}):`);
    for (const warn of warnings) {
      ConsoleOutput.warning(`${warn.ruleId}: ${warn.message}`);
    }
  }
}

/**
 * Compile all named build profiles in deterministic key order.
 * Each profile is compiled independently with its own entry, output, and targets.
 */
async function compileAllBuilds(options: CompileOptions, services: CliServices): Promise<boolean> {
  const logger = createCliLogger();
  const projectRoot = options.cwd ? resolve(options.cwd) : process.cwd();
  const configPath = resolveCompileConfigPath(projectRoot, options);
  const config = await loadEffectiveConfig(configPath);

  const buildNames = Object.keys(config.builds ?? {});
  if (buildNames.length === 0) {
    ConsoleOutput.warning('No named build profiles found in config.builds');
    return true;
  }

  // Deterministic key order
  buildNames.sort();

  let failed = 0;
  let succeeded = 0;

  for (const buildName of buildNames) {
    ConsoleOutput.info(`Compiling build profile: ${buildName}`);
    try {
      const successful = await compileCommandWithResult(
        {
          ...options,
          build: buildName,
          allBuilds: false,
          watch: false,
        },
        services
      );
      if (successful) {
        succeeded++;
      } else {
        failed++;
        ConsoleOutput.error(`Build profile "${buildName}" failed`);
      }
    } catch (err) {
      failed++;
      const msg = err instanceof Error ? err.message : String(err);
      ConsoleOutput.error(`Build profile "${buildName}" failed: ${msg}`);
    }
  }

  logger.verbose(`Compiled ${succeeded} build profile(s), ${failed} failed`);
  if (failed > 0) {
    process.exitCode = 1;
  }

  if (options.watch) {
    startWatchMode(projectRoot, config, () =>
      compileCommandWithResult({ ...options, watch: false }, services)
    );
  }

  return failed === 0;
}

/**
 * Compile PromptScript files to target formats.
 */
export async function compileCommand(
  options: CompileOptions,
  services: CliServices = createDefaultServices()
): Promise<void> {
  await compileCommandWithResult(options, services);
}

async function compileCommandWithResult(
  options: CompileOptions,
  services: CliServices
): Promise<boolean> {
  if (options.target && options.format && options.target !== options.format) {
    ConsoleOutput.error('Cannot use --target and --format with different values');
    process.exitCode = 1;
    return false;
  }

  // Reject --build combined with --all-builds
  if (options.build && options.allBuilds) {
    ConsoleOutput.error('Cannot use --build with --all-builds');
    process.exitCode = 1;
    return false;
  }

  // Handle --all-builds: compile every named build profile in deterministic order
  if (options.allBuilds) {
    try {
      return await compileAllBuilds(options, services);
    } catch (error) {
      ConsoleOutput.error(error instanceof Error ? error.message : String(error));
      process.exitCode = 1;
      return false;
    }
  }

  const spinner = createSpinner('Loading configuration...').start();
  const logger = createCliLogger();

  try {
    // Resolve project root from --cwd option or current working directory
    const projectRoot = options.cwd ? resolve(options.cwd) : process.cwd();

    logger.verbose('Loading configuration...');
    const configPath = resolveCompileConfigPath(projectRoot, options);
    const config = await loadEffectiveConfig(configPath);
    const buildProfile = getBuildProfile(config, options.build);

    // --format is an alias for --target
    const selectedTarget = options.target ?? options.format;
    const targetEntries = buildProfile?.targets ?? config.targets;
    const parsedTargets = parseTargets(targetEntries);
    let targets: { name: string; config?: TargetConfig }[];
    if (selectedTarget) {
      // Find the matching target entry to preserve configured options
      // (version, convention, skillBaseDir, etc.) instead of discarding them
      const matched = parsedTargets.find((t) => t.name === selectedTarget);
      targets = matched ? [matched] : [{ name: selectedTarget }];
    } else {
      targets = parsedTargets;
    }

    // Detect output path conflicts before doing any work
    const conflicts = detectOutputConflicts(targets);
    if (conflicts.size > 0) {
      const lines = [...conflicts.entries()].map(
        ([path, names]) => `  ${path} <- ${names.join(', ')}`
      );
      if (options.strict) {
        spinner.fail('Output path conflict detected');
        ConsoleOutput.error(
          `Output path conflict detected:\n${lines.join('\n')}\n\nDisable one of the conflicting targets or assign a custom output path.`
        );
        process.exitCode = 1;
        return false;
      }
      for (const line of lines) {
        ConsoleOutput.warning(`Output path conflict: ${line.trim()}. Last target processed wins.`);
      }
    }

    const lockfile = await loadCompileLockfile(projectRoot, logger);
    const vendorDir = resolve(projectRoot, '.promptscript/vendor');

    // Resolve registry path - use CLI flag override, or resolve from config (handles git registries)
    let registryPath: string;
    let referenceRoots: Record<string, string[]> | undefined;
    if (options.registry) {
      registryPath = resolveProjectPath(projectRoot, options.registry);
    } else {
      spinner.text = 'Resolving registry...';
      const registry = await resolveRegistryPath(config, { vendorDir, lockfile });
      registryPath = resolveProjectPath(projectRoot, registry.path);
      referenceRoots =
        registry.repositoryUrl && registry.repositoryPath
          ? { [registry.repositoryUrl]: [registry.repositoryPath] }
          : undefined;
      if (registry.isRemote) {
        logger.verbose(`Using cached git registry: ${registryPath}`);
      }
    }

    spinner.text = 'Compiling...';
    logger.verbose(`Registry: ${registryPath}`);
    logger.debug(`Config: ${JSON.stringify(config, null, 2)}`);

    // Resolve Prettier options from config
    const prettierOptions = await resolvePrettierOptions(config, projectRoot);

    // Load bundled PromptScript skill if not disabled.
    // Design decision: The CLI checks the config flag and decides whether to pass skillContent.
    // The Compiler simply checks if skillContent was provided — it does NOT read config.
    // This keeps the Compiler's API clean (provide content = inject, omit = skip).
    let skillContent: string | undefined;
    if (config.includePromptScriptSkill !== false) {
      skillContent = await loadBundledSkillContent(logger);
    }

    const localPath = resolve(projectRoot, '.promptscript');
    const compiler = new Compiler({
      resolver: {
        registryPath,
        localPath,
        projectRoot,
        vendorDir,
        referenceRoots,
        skills: resolveUniversalDir(config.universalDir),
        registries: config.registries,
        lockfile,
        skillTargets: config.skillTargets,
      },
      validator: config.validation,
      formatters: targets,
      customConventions: config.customConventions,
      prettier: prettierOptions,
      logger,
      skillContent,
      ignoreHashes: options.ignoreHashes,
    });

    const entry = buildProfile?.entry ?? config.input?.entry;
    const entryPath = entry ? resolve(projectRoot, entry) : resolve(localPath, 'project.prs');

    if (!existsSync(entryPath)) {
      spinner.fail('Entry file not found');
      ConsoleOutput.error(`File not found: ${entryPath}`);
      ConsoleOutput.muted(
        options.build ? `Check config.builds.${options.build}.entry` : 'Run: prs init'
      );
      process.exitCode = 1;
      return false;
    }

    const result = await compiler.compile(entryPath);

    if (!result.success) {
      spinner.fail('Compilation failed');
      ConsoleOutput.newline();
      printErrors(result.errors);
      process.exitCode = 1;
      return false;
    }

    // Hint about lockfile if registries are configured but no lockfile exists
    if (config.registries && Object.keys(config.registries).length > 0 && !lockfile) {
      logger.verbose('Tip: Run "prs lock" to pin remote dependencies for reproducible builds.');
    }

    const configuredOutput = options.output ?? buildProfile?.output ?? config.output?.baseDir;
    // Writing to a sibling directory is a supported build-profile layout, but a
    // base directory that leaves the project comes from a checked-in file, so
    // say where the files are going instead of doing it silently.
    if (!options.output && configuredOutput && !isPathInsideDir(configuredOutput, projectRoot)) {
      ConsoleOutput.warning(
        `Configured output directory "${configuredOutput}" is outside the project root ${projectRoot}`
      );
    }
    const effectiveOptions = {
      ...options,
      output: resolveOutputBase(projectRoot, configuredOutput),
      force: options.force ?? config.output?.overwrite,
    };
    applyConfiguredHeader(result.outputs, config.output?.header);
    await postFormatWithPrettier(result.outputs, projectRoot, logger);
    const hasFactoryTarget = targets.some((target) => target.name === 'factory');
    const migrateFactoryHooks = options.migrateFactoryHooks !== false;
    const legacyMigration =
      hasFactoryTarget && migrateFactoryHooks
        ? await prepareLegacyFactoryMigration(result.outputs, effectiveOptions.output)
        : undefined;
    const legacySettingsPath =
      hasFactoryTarget && !migrateFactoryHooks
        ? await detectLegacyFactorySettingsHooks(effectiveOptions.output, true)
        : undefined;
    const writeResult = await writeOutputs(
      result.outputs,
      effectiveOptions,
      config,
      services,
      result.outputPlan
    );
    if (legacyMigration) {
      if (writeResult.skipped.includes(legacyMigration.hooksPath)) {
        throw new Error(
          `Legacy Factory migration was cancelled before ${legacyMigration.hooksPath} was written.`
        );
      }
      await finishLegacyFactoryMigration(
        legacyMigration,
        effectiveOptions.output,
        options.dryRun,
        writeResult.created.includes(legacyMigration.hooksPath)
      );
    }
    const plannedOutputMap = new Map(
      getPlannedOutputs(result.outputs, result.outputPlan).map((output) => [output.path, output])
    );
    const cleanupResult = await cleanupManagedOutputs(plannedOutputMap, {
      outputRoot: effectiveOptions.output,
      dryRun: options.dryRun,
    });
    for (const removedPath of cleanupResult.removed) {
      if (options.dryRun) {
        ConsoleOutput.dryRun(`Would remove obsolete generated file: ${removedPath}`);
      } else {
        ConsoleOutput.muted(`Removed obsolete generated file: ${removedPath}`);
      }
    }
    for (const removedDirectory of cleanupResult.removedDirectories) {
      if (options.dryRun) {
        ConsoleOutput.dryRun(`Would remove empty managed directory: ${removedDirectory}`);
      } else {
        ConsoleOutput.muted(`Removed empty managed directory: ${removedDirectory}`);
      }
    }
    // Report success only after every output and cleanup step completed, so a
    // write-phase failure never follows a "Compilation successful" line.
    spinner.succeed('Compilation successful');
    ConsoleOutput.newline();
    if (writeResult.unchanged.length > 0) {
      ConsoleOutput.muted(`Unchanged ${writeResult.unchanged.length} file(s)`);
    }
    if (writeResult.skipped.length > 0) {
      ConsoleOutput.muted(`Skipped ${writeResult.skipped.length} file(s)`);
    }

    if (legacySettingsPath) {
      result.warnings.push({
        ruleId: 'PS4002',
        ruleName: 'hook-compatibility',
        severity: 'warning',
        message:
          `${legacySettingsPath} contains a legacy "hooks" section. ` +
          'Run "prs hooks install factory" to migrate unambiguous hooks to .factory/hooks.json, ' +
          'or remove the "hooks" key manually after reviewing ambiguous entries.',
      });
    }

    printStats(result.stats);
    printWarnings(result.warnings);

    // Watch mode
    if (options.watch) {
      startWatchMode(projectRoot, config, () =>
        compileCommandWithResult({ ...options, watch: false }, services)
      );
    }
    return true;
  } catch (error) {
    if (error instanceof Error && error.name === 'ExitPromptError') {
      // User cancelled with Ctrl+C during prompt
      spinner.stop();
      ConsoleOutput.newline();
      ConsoleOutput.muted('Compilation cancelled');
      return false;
    }
    spinner.fail('Error');
    ConsoleOutput.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
    return false;
  }
}

/**
 * Start watch mode using project-relative include and exclude patterns.
 */
function startWatchMode(
  projectRoot: string,
  config: PromptScriptConfig,
  callback: () => Promise<boolean>
): void {
  ConsoleOutput.newline();
  ConsoleOutput.info('Watching for changes... (Ctrl+C to stop)');
  watchForChanges(projectRoot, config.watch, callback);
}

interface WatchEvent {
  action: 'changed' | 'added' | 'removed';
  path: string;
}

const DEFAULT_WATCH_INCLUDE = ['**/*.prs'];
const DEFAULT_WATCH_EXCLUDE = ['**/node_modules/**', '**/.git/**', '.promptscript/vendor/**'];

function watchForChanges(
  projectRoot: string,
  watchConfig: PromptScriptConfig['watch'],
  callback: () => Promise<boolean>
): void {
  let debounceTimer: NodeJS.Timeout | null = null;
  let compileRunning = false;
  let compilePending = false;
  let pendingEvent: WatchEvent | undefined;
  const debounceMs = watchConfig?.debounce ?? 300;
  const includePatterns = watchConfig?.include ?? DEFAULT_WATCH_INCLUDE;
  const excludePatterns = watchConfig?.exclude ?? DEFAULT_WATCH_EXCLUDE;
  const matcherOptions = { dot: true, nocase: process.platform === 'win32' };

  const relativePath = (path: string): string => relative(projectRoot, path).replace(/\\/g, '/');
  const matches = (path: string, patterns: string[]): boolean => {
    const relative = relativePath(path);
    return patterns.some((pattern) => minimatch(relative, pattern, matcherOptions));
  };
  const shouldCompile = (path: string): boolean =>
    matches(path, includePatterns) && !matches(path, excludePatterns);

  const watcher = chokidar.watch(projectRoot, {
    persistent: true,
    ignoreInitial: true,
    followSymlinks: false,
    ignored: (path, stats) => {
      const normalized = relativePath(path);
      const candidate = stats?.isDirectory() === true ? `${normalized}/` : normalized;
      const excluded = excludePatterns.some((pattern) =>
        minimatch(candidate, pattern, matcherOptions)
      );
      if (excluded) return true;
      return stats?.isFile() === true && !matches(path, includePatterns);
    },
    awaitWriteFinish: {
      stabilityThreshold: 50,
      pollInterval: 10,
    },
  });

  const runCompilation = async (): Promise<void> => {
    if (compileRunning) {
      compilePending = true;
      return;
    }

    compileRunning = true;
    do {
      compilePending = false;
      const event = pendingEvent;
      pendingEvent = undefined;
      if (watchConfig?.clearScreen !== false) {
        console.clear();
      }
      ConsoleOutput.newline();
      if (event) {
        ConsoleOutput.info(`File ${event.action}: ${event.path}`);
      }
      try {
        await callback();
      } catch (error) {
        ConsoleOutput.error(
          `Watch compilation failed: ${error instanceof Error ? error.message : String(error)}`
        );
        process.exitCode = 1;
      }
    } while (compilePending);
    compileRunning = false;
  };

  const scheduleCompilation = (event: WatchEvent): void => {
    if (!shouldCompile(event.path)) return;
    pendingEvent = event;
    if (debounceTimer) {
      clearTimeout(debounceTimer);
    }

    debounceTimer = setTimeout(() => {
      debounceTimer = null;
      void runCompilation();
    }, debounceMs);
  };

  watcher.on('change', (filename) => scheduleCompilation({ action: 'changed', path: filename }));
  watcher.on('add', (filename) => scheduleCompilation({ action: 'added', path: filename }));
  watcher.on('unlink', (filename) => scheduleCompilation({ action: 'removed', path: filename }));

  watcher.on('error', (error: unknown) => {
    const errorMessage = error instanceof Error ? error.message : String(error);
    ConsoleOutput.error(`Watcher error: ${errorMessage}`);
    process.exitCode = 1;
  });
}
