packages:
  - packages/*

allowBuilds:
  '@swc/core': true
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
  nx: true

autoInstallPeers: true

ignoredBuiltDependencies:
  - nx

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
