// Plain Markdown for LLMs and agents, in the same shape the MkDocs site had:
// /llms.txt links every page's /<page>/index.md, /llms-full.txt has them all.
import { posix } from 'node:path';
import { rewriteDocLinkFrom } from './plugins/remark-mkdocs-compat.mjs';
import { DOCS_BASE, SIDEBAR, SITE } from './site.mjs';

export const LLMS_SUMMARY =
  'PromptScript is an agent platform configuration language. It defines instructions, skills, agents, MCP servers, plugins, hooks, workflows, and policies once, then compiles native output for 50 AI coding agent targets.';

/** The part of a docs collection entry this module needs. */
export interface DocPage {
  id: string;
  body?: string;
  filePath?: string;
  data: { title: string; description?: string; sidebar?: { order?: number; label?: string } };
}

/** The part of the Starlight sidebar config this module reads. */
export interface SidebarItem {
  label?: string;
  slug?: string;
  link?: string;
  items?: readonly SidebarItem[];
  autogenerate?: { directory: string };
}

export interface LlmsSection {
  label: string;
  pages: DocPage[];
}

export function markdownUrl(id: string): string {
  return id === 'index' ? `${SITE}/index.md` : `${SITE}/${id}/index.md`;
}

/** Text content of an HTML snippet. A plain scan, so no regex backtracking. */
function text(html: string): string {
  let result = '';
  let inTag = false;
  for (const char of html) {
    if (char === '<') inTag = true;
    else if (char === '>') inTag = false;
    else if (!inTag) result += char;
  }
  return result.trim();
}

/** Drops a `<div class="...">` block with everything nested in it. */
function dropDiv(body: string, className: string): string {
  const lines = body.split('\n');
  const kept: string[] = [];
  let depth = 0;
  for (const line of lines) {
    if (depth === 0 && !line.includes(`<div class="${className}"`)) {
      kept.push(line);
      continue;
    }
    depth += (line.match(/<div\b/g) ?? []).length - (line.match(/<\/div>/g) ?? []).length;
  }
  return kept.join('\n');
}

/**
 * Hub pages use HTML cards for readers. Agents get the same links as a plain
 * list, without icons, demo terminals, or wrapper markup.
 */
export function cardsToMarkdown(body: string, pageId: string): string {
  const pageUrl = pageId === 'index' ? `${SITE}/` : `${SITE}/${pageId}/`;
  let result = body.replaceAll(
    /<a href="([^"]+)" class="(?:ref-item|formatter-card)">([\s\S]*?)<\/a>/g,
    (_card, href: string, inner: string) => {
      const url = new URL(href, pageUrl);
      const target =
        url.origin === SITE
          ? markdownUrl(url.pathname.replaceAll(/^\/|\/$/g, '') || 'index') + url.hash
          : href;
      const title =
        text(/<h3>([\s\S]*?)<\/h3>/.exec(inner)?.[1] ?? '') ||
        text(/formatter-card__name">([\s\S]*?)</.exec(inner)?.[1] ?? '');
      const about = /<p>([\s\S]*?)<\/p>/.exec(inner)?.[1];
      const output = /<code[^>]*>([\s\S]*?)<\/code>/.exec(inner)?.[1];
      const tags = [...inner.matchAll(/formatter-card__tag[^"]*">([^<]*)</g)].map((m) => m[1]);
      const details = about
        ? text(about)
        : [output && `\`${text(output)}\``, tags.join(', ')].filter(Boolean).join(' - ');
      const suffix = details ? `: ${details}` : '';
      return `- [${title}](${target})${suffix}`;
    }
  );
  for (const block of ['init-demo', 'formatter-tiers']) result = dropDiv(result, block);
  return result
    .replaceAll(
      /^(?:<div class="(?:ref-list|formatter-cards)">|<\/div>|<!-- prettier-ignore -->)$\n?/gm,
      ''
    )
    .replaceAll(/^<p class="[^"]*">(.*)<\/p>$/gm, '$1')
    .replaceAll(/<\/?strong>/g, '**')
    .replaceAll(/^(- \[.*)\n\n(?=- \[)/gm, '$1\n')
    .replaceAll(/\n{3,}/g, '\n\n');
}

/** Page source with its H1 and with doc links pointing at other Markdown pages. */
export function pageMarkdown(page: DocPage): string {
  const body = cardsToMarkdown(page.body ?? '', page.id).replaceAll(
    /\]\(([^)\s]+\.md(?:#[^)\s]*)?)\)/g,
    (link, url) => {
      if (!page.filePath || url.startsWith('/')) return link;
      const target = rewriteDocLinkFrom(url, posix.relative(DOCS_BASE, page.filePath));
      const match = /^\/([^#]*)(#.*)?$/.exec(target);
      if (!match) return `](${target})`;
      const id = match[1].replace(/\/$/, '') || 'index';
      return `](${markdownUrl(id)}${match[2] ?? ''})`;
    }
  );
  const trimmed = body.trimStart();
  return trimmed.startsWith('# ') ? trimmed : `# ${page.data.title}\n\n${trimmed}`;
}

function autogenerated(pages: readonly DocPage[], directory: string): DocPage[] {
  const order = (page: DocPage): number => page.data.sidebar?.order ?? Number.MAX_SAFE_INTEGER;
  const label = (page: DocPage): string => page.data.sidebar?.label ?? page.data.title;
  return pages
    .filter((page) => page.id.startsWith(`${directory}/`) || page.id === directory)
    .sort((a, b) => order(a) - order(b) || label(a).localeCompare(label(b)));
}

function collect(items: readonly SidebarItem[], byId: Map<string, DocPage>): DocPage[] {
  return items.flatMap((item) => {
    if (item.slug) {
      const page = byId.get(item.slug);
      return page ? [page] : [];
    }
    if (item.autogenerate) return autogenerated([...byId.values()], item.autogenerate.directory);
    return collect(item.items ?? [], byId);
  });
}

/** Sidebar groups with their pages, plus one section for pages outside the sidebar. */
export function llmsSections(
  pages: readonly DocPage[],
  sidebar: readonly SidebarItem[] = SIDEBAR
): LlmsSection[] {
  const docs = pages.filter((page) => !page.id.startsWith('api-reference') && page.id !== '404');
  const byId = new Map(docs.map((page) => [page.id, page]));
  const sections = sidebar.map((group) => ({
    label: group.label ?? '',
    pages: collect(group.items ?? [], byId),
  }));
  const listed = new Set(sections.flatMap((section) => section.pages.map((page) => page.id)));
  const rest = docs.filter((page) => !listed.has(page.id));
  if (rest.length > 0) sections.push({ label: 'More', pages: rest });
  return sections;
}

export function llmsIndex(sections: readonly LlmsSection[]): string {
  const lines = [
    '# PromptScript',
    '',
    '> Open-source compiler for AI coding agent rules. Write instructions, skills, agents, and MCP servers once and get native files for 50 tools.',
    '',
    LLMS_SUMMARY,
    '',
    `Every page below is plain Markdown. The whole documentation in one file: ${SITE}/llms-full.txt`,
  ];
  for (const section of sections) {
    lines.push('', `## ${section.label}`, '');
    for (const page of section.pages) {
      const description = page.data.description ? `: ${page.data.description}` : '';
      lines.push(`- [${page.data.title}](${markdownUrl(page.id)})${description}`);
    }
  }
  lines.push(
    '',
    '## Optional',
    '',
    `- [API Reference](${SITE}/api-reference/): TypeDoc reference for the PromptScript packages`,
    `- [Playground](${SITE}/playground/): compile .prs files in the browser`,
    '- [Source code](https://github.com/mrwogu/promptscript): GitHub repository',
    '- [npm packages](https://www.npmjs.com/org/promptscript): @promptscript/cli and libraries',
    ''
  );
  return lines.join('\n');
}

export function llmsFull(sections: readonly LlmsSection[]): string {
  const pages = sections.flatMap((section) => section.pages);
  return [`# PromptScript\n\n> ${LLMS_SUMMARY}`, ...pages.map(pageMarkdown)].join('\n\n---\n\n');
}
