import { realpathSync } from 'fs';
import {
  createOutputPlan,
  noopLogger,
  type Logger,
  type OutputPlanCandidate,
  type OutputPlan,
  type PSError,
} from '@promptscript/core';
import { FormatterRegistry, formatProgram } from '@promptscript/formatters';
import {
  getVendorRepositoryRelativePath,
  RegistryCache,
  Resolver,
  type ResolvedAST,
} from '@promptscript/resolver';
import { Validator, type ValidatorConfig, type ValidationMessage } from '@promptscript/validator';
import { minimatch } from 'minimatch';
import { dirname, isAbsolute, join, relative, resolve, sep } from 'path';
// eslint-disable-next-line @typescript-eslint/no-unused-vars -- imported for upcoming formatter integration
import { verifyReferenceIntegrity } from './reference-verifier.js';
import {
  findProjectRootMarker,
  inferProjectRoot,
  validateHookScriptResources,
} from './hook-script-validator.js';
import type {
  CompilerOptions,
  CompileResult,
  CompileStats,
  CompileError,
  Formatter,
  FormatterOutput,
  FormatterConstructor,
  TargetConfig,
  WatchOptions,
  Watcher,
} from './types.js';

/**
 * Internal representation of a loaded formatter with its config.
 */
interface LoadedFormatter {
  formatter: Formatter;
  config?: TargetConfig;
}

/** Maximum number of project-scoped resolvers retained by a long-lived compiler. */
export const MAX_ENTRY_RESOLVERS = 50;
/** Maximum number of resolved dependency sets retained by a compiler. */
export const MAX_RESOLVED_DEPENDENCIES = 50;

function resolverCacheKey(projectRoot: string): string {
  return realpathSync.native(projectRoot);
}

function resolveEntryPath(entryPath: string): string {
  if (entryPath.startsWith('@')) return entryPath;
  const fileName =
    entryPath.endsWith('.prs') || entryPath.endsWith('.md') ? entryPath : `${entryPath}.prs`;
  const absolutePath = isAbsolute(fileName) ? fileName : resolve(process.cwd(), fileName);
  try {
    return realpathSync.native(absolutePath);
  } catch {
    return absolutePath;
  }
}

function entryWatchPath(entryPath: string): string {
  if (entryPath.startsWith('@')) return entryPath;
  const fileName =
    entryPath.endsWith('.prs') || entryPath.endsWith('.md') ? entryPath : `${entryPath}.prs`;
  return absoluteWatchPath(fileName);
}

function normalizeRepositoryKey(value: string): string {
  return value
    .replace(/^(?:https?:\/\/|git:\/\/)/i, '')
    .replace(/^git@([^:]+):/, '$1/')
    .replace(/\.git(?=\/|$)/, '');
}

/**
 * Generate HTML marker comment that identifies files generated by PromptScript.
 * Uses HTML comment to be invisible to LLMs and rendered output.
 */
function generateHtmlMarker(source: string, target: string): string {
  const timestamp = new Date().toISOString();
  return `<!-- PromptScript ${timestamp} | source: ${source} | target: ${target} - do not edit -->`;
}

/**
 * Generate YAML comment marker for use inside YAML frontmatter.
 * Some tools (e.g. Factory AI) cannot parse HTML comments after frontmatter,
 * so we embed the marker as a YAML comment inside the frontmatter block.
 */
function generateYamlMarker(source: string, target: string): string {
  const timestamp = new Date().toISOString();
  return `# promptscript-generated: ${timestamp} | source: ${source} | target: ${target}`;
}

/**
 * Add PromptScript marker to output content if not already present.
 *
 * For files with YAML frontmatter: inserts a YAML comment inside the frontmatter.
 * This avoids breaking tools like Factory AI that cannot parse HTML comments
 * between frontmatter and content body.
 *
 * For files without frontmatter: inserts an HTML comment at the top.
 */
function addMarkerToOutput(
  output: FormatterOutput,
  source: string,
  target: string
): FormatterOutput {
  const { content, path } = output;

  // Skip if marker already present (check for both HTML and YAML patterns)
  if (content.includes('<!-- PromptScript') || content.includes('# promptscript-generated:')) {
    return output;
  }

  // Only add to markdown files
  if (!path.endsWith('.md') && !path.endsWith('.mdc')) {
    return output;
  }

  // Check for YAML frontmatter (starts with ---)
  if (content.startsWith('---')) {
    // Find the closing ---
    const closingIndex = content.indexOf('---', 3);
    if (closingIndex !== -1) {
      // Insert YAML comment marker as first line inside frontmatter
      const afterOpening = content.slice(3); // skip opening ---
      const newContent = `---\n${generateYamlMarker(source, target)}${afterOpening}`;
      return { ...output, content: newContent };
    }
  }

  // No frontmatter - add HTML marker at the beginning (after any title)
  const marker = generateHtmlMarker(source, target);
  const lines = content.split('\n');
  if (lines[0]?.startsWith('# ')) {
    // Has title - insert after title
    lines.splice(1, 0, '', marker);
  } else {
    // No title - insert at beginning
    lines.unshift(marker, '');
  }
  return { ...output, content: lines.join('\n') };
}

function normalizeOutputDir(dir: string): string {
  return dir
    .replace(/\\/g, '/')
    .replace(/^\/+/, '')
    .replace(/\/+$/g, '')
    .split('/')
    .filter((segment) => segment.length > 0 && segment !== '.' && segment !== '..')
    .join('/');
}

function matchesWatchPattern(path: string, pattern: string, baseDir: string): boolean {
  const normalizedPath = path.replace(/\\/g, '/');
  const relativePath = relative(baseDir, path).replace(/\\/g, '/');
  const candidates = [relativePath, normalizedPath].flatMap((candidate) => [
    candidate,
    candidate.endsWith('/') ? candidate : `${candidate}/`,
  ]);
  const matcherOptions = {
    dot: true,
    nocase: process.platform === 'win32' || process.platform === 'darwin',
  };
  return candidates.some((candidate) => minimatch(candidate, pattern, matcherOptions));
}

function absoluteWatchPath(path: string, baseDir: string = process.cwd()): string {
  return isAbsolute(path) ? resolve(path) : resolve(baseDir, path);
}

function canonicalWatchPath(path: string, baseDir: string = process.cwd()): string {
  const absolutePath = absoluteWatchPath(path, baseDir);
  try {
    return realpathSync.native(absolutePath);
  } catch {
    return absolutePath;
  }
}

function normalizeWatchPath(path: string): string {
  const normalizedPath = path.replace(/\\/g, '/');
  return process.platform === 'win32' || process.platform === 'darwin'
    ? normalizedPath.toLowerCase()
    : normalizedPath;
}

function watchPathVariants(path: string, baseDir: string = process.cwd()): string[] {
  const absolutePath = absoluteWatchPath(path, baseDir);
  const canonicalPath = canonicalWatchPath(absolutePath, baseDir);
  return [...new Set([absolutePath, canonicalPath])];
}

function watchPathKey(path: string, baseDir: string = process.cwd()): string {
  return normalizeWatchPath(canonicalWatchPath(path, baseDir));
}

function isPathWithin(path: string, root: string): boolean {
  const relation = relative(normalizeWatchPath(root), normalizeWatchPath(path));
  return (
    relation === '' ||
    (relation !== '..' && !relation.startsWith(`..${sep}`) && !isAbsolute(relation))
  );
}

function shouldIncludeSkill(name: string, config?: TargetConfig): boolean {
  const includeSkills = config?.includeSkills;
  if (includeSkills === false) return false;
  if (Array.isArray(includeSkills)) return includeSkills.includes(name);
  return true;
}

/**
 * Compiler that orchestrates the PromptScript compilation pipeline.
 *
 * Pipeline stages:
 * 1. Resolve - Parse and resolve inheritance/imports
 * 2. Validate - Check AST against validation rules
 * 3. Format - Generate output for target platforms
 *
 * @example
 * ```typescript
 * const compiler = new Compiler({
 *   resolver: { registryPath: './registry' },
 *   validator: { requiredGuards: ['@core/guards/compliance'] },
 *   formatters: [new GitHubFormatter()],
 * });
 *
 * const result = await compiler.compile('./project.prs');
 * if (result.success) {
 *   for (const [outputPath, output] of result.outputs) {
 *     console.log(`Generated: ${outputPath}`);
 *   }
 * }
 * ```
 */
export class Compiler {
  private readonly resolver: Resolver;
  private readonly entryResolvers = new Map<string, Resolver>();
  private readonly validator: Validator;
  private readonly loadedFormatters: LoadedFormatter[];
  private readonly logger: Logger;
  private readonly resolvedDependencies = new Map<string, Set<string>>();

  constructor(private readonly options: CompilerOptions) {
    this.logger = options.logger ?? noopLogger;
    this.resolver = new Resolver({ ...options.resolver, logger: this.logger });
    this.validator = new Validator({ ...options.validator, logger: this.logger });
    this.loadedFormatters = this.loadFormatters(options.formatters);

    this.logger.debug(`Compiler initialized with ${this.loadedFormatters.length} formatters`);
  }

  private hasExplicitResolverScope(): boolean {
    return Boolean(this.options.resolver.localPath || this.options.resolver.projectRoot);
  }

  /**
   * Get the resolver to use for an entry file.
   *
   * Hook script validation infers the project root from the entry path, so a
   * resolver left on the cwd default would discover skills, commands and
   * agents from a different directory than the one being compiled.
   *
   * @param entryPath - Path to the entry file
   * @returns Resolver scoped to the entry file's project root
   */
  private resolverFor(entryPath: string): Resolver {
    if (this.hasExplicitResolverScope()) {
      return this.resolver;
    }

    const projectRoot = findProjectRootMarker(entryPath);
    if (!projectRoot) {
      // Keep cwd-based resolution when an entry is outside a marked project.
      return this.resolver;
    }

    const cacheKey = resolverCacheKey(projectRoot);
    const cached = this.entryResolvers.get(cacheKey);
    if (cached) return cached;

    const resolver = new Resolver({
      ...this.options.resolver,
      projectRoot: cacheKey,
      logger: this.logger,
    });
    if (this.entryResolvers.size >= MAX_ENTRY_RESOLVERS) {
      // Bound per-project caches for long-lived watch and server compilers.
      const oldestKey = this.entryResolvers.keys().next().value;
      if (oldestKey !== undefined) this.entryResolvers.delete(oldestKey);
    }
    this.entryResolvers.set(cacheKey, resolver);
    return resolver;
  }

  private dependencyKey(entryPath: string): string {
    return entryPath.startsWith('@') ? entryPath : watchPathKey(entryWatchPath(entryPath));
  }

  private collectResolvedDependencies(entryPath: string, resolved: ResolvedAST): Set<string> {
    const dependencies = new Set<string>();
    const paths = [
      entryWatchPath(entryPath),
      ...(resolved.sources ?? []),
      ...(resolved.dependencies ?? []),
    ];
    for (const path of paths) {
      if (path.startsWith('@') || path.startsWith('__registry__:')) continue;
      dependencies.add(absoluteWatchPath(path));
    }
    return dependencies;
  }

  private commitResolvedDependencies(entryPath: string, dependencies: Set<string>): void {
    const key = this.dependencyKey(entryPath);
    if (
      !this.resolvedDependencies.has(key) &&
      this.resolvedDependencies.size >= MAX_RESOLVED_DEPENDENCIES
    ) {
      const oldestKey = this.resolvedDependencies.keys().next().value;
      if (oldestKey !== undefined) this.resolvedDependencies.delete(oldestKey);
    }
    this.resolvedDependencies.set(key, dependencies);
  }

  private watchProjectRoot(entryPath: string): string {
    return resolve(
      this.options.resolver.projectRoot ??
        findProjectRootMarker(entryPath) ??
        dirname(resolve(entryPath))
    );
  }

  private watchDependencyPaths(entryPath: string): string[] {
    const key = this.dependencyKey(entryPath);
    const dependencies =
      this.resolvedDependencies.get(key) ?? new Set<string>([entryWatchPath(entryPath)]);
    const projectRoot = this.watchProjectRoot(entryPath);
    const configPaths = [
      'promptscript.yaml',
      'promptscript.yml',
      '.promptscriptrc.yaml',
      '.promptscriptrc.yml',
      'promptscript.lock',
    ].map((fileName) => resolve(projectRoot, fileName));

    return [...new Set([...dependencies, ...configPaths])];
  }

  private resolvedDependencyPaths(entryPath: string): string[] {
    const key = this.dependencyKey(entryPath);
    return [
      ...(this.resolvedDependencies.get(key) ?? new Set<string>([entryWatchPath(entryPath)])),
    ];
  }

  private pathMatchesDependency(path: string, dependency: string): boolean {
    return watchPathVariants(dependency).some((dependencyPath) =>
      watchPathVariants(path).some((candidatePath) => isPathWithin(candidatePath, dependencyPath))
    );
  }

  private invalidateResolvers(entryPath: string, changedFiles: readonly string[]): void {
    const normalizedChanges = [...new Set(changedFiles.flatMap((path) => watchPathVariants(path)))];
    const configNames = new Set([
      'promptscript.yaml',
      'promptscript.yml',
      '.promptscriptrc.yaml',
      '.promptscriptrc.yml',
      'promptscript.lock',
    ]);
    const projectRoot = this.watchProjectRoot(entryPath);
    const configurationPaths = new Set(
      [...configNames].map((fileName) => watchPathKey(resolve(projectRoot, fileName)))
    );
    const hasConfigurationChange = normalizedChanges.some((path) =>
      configurationPaths.has(watchPathKey(path))
    );

    const resolvers = [this.resolver, ...this.entryResolvers.values()];
    for (const resolver of resolvers) {
      resolver.invalidate(normalizedChanges);
      if (hasConfigurationChange) resolver.clearCache();
    }
  }

  /**
   * Compile a PromptScript file through the full pipeline.
   *
   * @param entryPath - Path to the entry file
   * @returns Compilation result with outputs, errors, and stats
   */
  async compile(entryPath: string): Promise<CompileResult> {
    this.logger.verbose(`Entry: ${entryPath}`);
    this.logger.verbose(
      `Targets: ${this.loadedFormatters.map((f) => f.formatter.name).join(', ')}`
    );

    const resolvedEntryPath = this.hasExplicitResolverScope()
      ? entryPath
      : resolveEntryPath(entryPath);
    const resolver = this.resolverFor(resolvedEntryPath);
    const startTotal = Date.now();
    const stats: CompileStats = {
      resolveTime: 0,
      validateTime: 0,
      formatTime: 0,
      totalTime: 0,
    };

    // Compute a relative source label for markers so absolute user paths
    // are never leaked into generated output files.
    const sourceLabel = isAbsolute(entryPath) ? relative(process.cwd(), entryPath) : entryPath;

    // Stage 1: Resolve
    this.logger.verbose('=== Stage 1: Resolve ===');
    const startResolve = Date.now();
    let resolved: ResolvedAST;
    let candidateDependencies: Set<string> | undefined;

    try {
      resolved = await resolver.resolve(resolvedEntryPath);
      candidateDependencies = this.collectResolvedDependencies(entryPath, resolved);
    } catch (err) {
      stats.resolveTime = Date.now() - startResolve;
      stats.totalTime = Date.now() - startTotal;
      this.logger.verbose(`Resolve failed (${stats.resolveTime}ms)`);

      return {
        success: false,
        outputs: new Map(),
        errors: [
          this.toCompileError(
            err instanceof Error
              ? err
              : this.isPSErrorLike(err)
                ? (err as PSError)
                : new Error(String(err))
          ),
        ],
        warnings: [],
        stats,
      };
    }

    stats.resolveTime = Date.now() - startResolve;
    this.logger.verbose(`Resolve completed (${stats.resolveTime}ms)`);

    // ResolvedAST exposes the canonical tree as the pipeline representation.
    const canonicalAst = resolved.canonicalAst;

    // Check for resolve errors
    if (resolved.errors.length > 0 || !canonicalAst) {
      stats.totalTime = Date.now() - startTotal;
      const compatibility = canonicalAst ? this.validator.validate(canonicalAst) : undefined;
      const compatibilityErrors =
        compatibility?.errors.filter((message) => message.ruleId === 'PS018') ?? [];
      const compatibilityWarnings =
        compatibility?.warnings.filter((message) => message.ruleId === 'PS018') ?? [];

      return {
        success: false,
        outputs: new Map(),
        errors: [
          ...resolved.errors.map((error) => this.toCompileError(error)),
          ...compatibilityErrors.map((message) => this.validationToCompileError(message)),
        ],
        warnings: compatibilityWarnings,
        stats,
      };
    }

    // Stage 1.5: Reference Integrity
    const compileErrors: CompileError[] = [];
    if (!this.options.ignoreHashes && this.options.resolver.lockfile) {
      this.logger.verbose('=== Stage 1.5: Reference Integrity ===');
      // Collect registry reference paths for the validator
      const registryReferences = new Set<string>();
      const registryReferencePaths = new Map<string, Map<string, string>>();
      const cacheDir =
        this.options.resolver.cacheDir ??
        join(process.env['HOME'] ?? process.env['USERPROFILE'] ?? '/tmp', '.promptscript', 'cache');
      const registryCache = new RegistryCache(cacheDir);
      const referenceRoots: Array<{ repoUrl: string; version: string; path: string }> = [];
      for (const [repoUrl, dependency] of Object.entries(
        this.options.resolver.lockfile.dependencies
      )) {
        try {
          referenceRoots.push({
            repoUrl,
            version: dependency.version,
            path: registryCache.getCachePath(repoUrl, dependency.version),
          });
        } catch {
          // Invalid cache keys are reported by reference hash verification.
        }
        if (this.options.resolver.vendorDir) {
          try {
            referenceRoots.push({
              repoUrl,
              version: dependency.version,
              path: resolve(
                this.options.resolver.vendorDir,
                getVendorRepositoryRelativePath(repoUrl)
              ),
            });
          } catch {
            // Non-vendor repository URLs can still use configured reference roots.
          }
        }
        const configuredRoots = Object.entries(this.options.resolver.referenceRoots ?? {}).find(
          ([configuredRepoUrl]) =>
            normalizeRepositoryKey(configuredRepoUrl) === normalizeRepositoryKey(repoUrl)
        )?.[1];
        for (const path of configuredRoots ?? []) {
          referenceRoots.push({ repoUrl, version: dependency.version, path });
        }
      }
      referenceRoots.sort((left, right) => resolve(right.path).length - resolve(left.path).length);

      for (const block of canonicalAst.blocks) {
        if (block.name !== 'skills' || block.content.type !== 'ObjectContent') continue;
        const sourceFile = block.loc.file;
        const referenceRoot = sourceFile
          ? referenceRoots.find((root) => {
              const relation = relative(resolve(root.path), resolve(sourceFile));
              return (
                relation === '' ||
                (relation !== '..' && !relation.startsWith(`..${sep}`) && !isAbsolute(relation))
              );
            })
          : undefined;

        for (const [, skillValue] of Object.entries(block.content.properties)) {
          if (
            typeof skillValue !== 'object' ||
            skillValue === null ||
            !('references' in skillValue)
          )
            continue;

          const refs = (skillValue as Record<string, unknown>)['references'];
          if (!Array.isArray(refs)) continue;

          for (const ref of refs) {
            if (typeof ref !== 'string') continue;
            registryReferences.add(ref);
            if (sourceFile && referenceRoot) {
              const resolvedReference = resolve(dirname(sourceFile), ref);
              const relation = relative(resolve(referenceRoot.path), resolvedReference);
              if (
                relation !== '' &&
                relation !== '..' &&
                !relation.startsWith(`..${sep}`) &&
                !isAbsolute(relation)
              ) {
                const sourceReferences =
                  registryReferencePaths.get(sourceFile) ?? new Map<string, string>();
                const relativePath = relation.replaceAll('\\', '/');
                const referenceKey = `${referenceRoot.repoUrl}\0${relativePath}\0${referenceRoot.version}`;
                sourceReferences.set(ref, referenceKey);
                registryReferencePaths.set(sourceFile, sourceReferences);
                if (!Object.hasOwn(this.options.resolver.lockfile.references ?? {}, referenceKey)) {
                  compileErrors.push({
                    name: 'ResolveError',
                    code: 'PS2023',
                    message:
                      `Reference file "${relativePath}" has no integrity hash in lockfile. ` +
                      'Run `prs lock` to generate integrity hashes for registry references.',
                    location: block.loc,
                  });
                }
              } else {
                compileErrors.push({
                  name: 'ResolveError',
                  code: 'PS2023',
                  message: `Reference path escapes its repository: ${ref}`,
                  location: block.loc,
                });
              }
            }
          }
        }
      }

      // Verify reference file hashes against lockfile
      const hashErrors = await resolver.verifyReferenceHashes(this.options.resolver.lockfile);
      for (const err of hashErrors) {
        compileErrors.push(this.toCompileError(err));
      }

      // Pass registry references to validator for PS031 structural check
      this.validator.updateConfig({
        registryReferences,
        registryReferencePaths,
        lockfile: this.options.resolver.lockfile,
        ignoreHashes: this.options.ignoreHashes,
      });
    } else if (this.options.ignoreHashes) {
      this.logger.verbose('--ignore-hashes is set: reference integrity verification is disabled');
      console.error('⚠ --ignore-hashes is set: reference integrity verification is disabled');
      this.validator.updateConfig({ ignoreHashes: true });
    }

    // Check for reference integrity errors
    if (compileErrors.length > 0) {
      stats.totalTime = Date.now() - startTotal;
      return {
        success: false,
        outputs: new Map(),
        errors: compileErrors,
        warnings: [],
        stats,
      };
    }

    // Stage 2: Validate
    this.logger.verbose('=== Stage 2: Validate ===');
    const startValidate = Date.now();
    const validation = this.validator.validate(canonicalAst);

    // Check for validation errors
    if (!validation.valid) {
      stats.validateTime = Date.now() - startValidate;
      this.logger.verbose(`Validate completed (${stats.validateTime}ms)`);
      stats.totalTime = Date.now() - startTotal;

      return {
        success: false,
        outputs: new Map(),
        errors: validation.errors.map((e) => this.validationToCompileError(e)),
        warnings: validation.warnings,
        stats,
      };
    }

    const hookScriptErrors = await validateHookScriptResources(
      canonicalAst,
      inferProjectRoot(
        this.options.resolver.localPath,
        this.options.resolver.projectRoot,
        resolvedEntryPath
      )
    );
    stats.validateTime = Date.now() - startValidate;
    this.logger.verbose(`Validate completed (${stats.validateTime}ms)`);
    if (hookScriptErrors.length > 0) {
      stats.totalTime = Date.now() - startTotal;
      return {
        success: false,
        outputs: new Map(),
        errors: hookScriptErrors,
        warnings: validation.warnings,
        stats,
      };
    }

    // Stage 3: Format
    this.logger.verbose('=== Stage 3: Format ===');
    const startFormat = Date.now();
    const outputs = new Map<string, FormatterOutput>();
    const formatErrors: CompileError[] = [];
    const formatWarnings: ValidationMessage[] = [];
    const planCandidates: OutputPlanCandidate[] = [];

    for (const { formatter, config } of this.loadedFormatters) {
      const formatterStart = Date.now();
      this.logger.verbose(`Formatting for ${formatter.name}`);

      try {
        const formatOptions = this.getFormatOptionsForTarget(formatter.name, config);
        this.logger.debug(`  Convention: ${formatOptions.convention ?? 'default'}`);

        const output = formatProgram(formatter, canonicalAst, formatOptions);
        const formatterTime = Date.now() - formatterStart;

        this.logger.verbose(`  → ${output.path} (${formatterTime}ms)`);

        for (const warning of output.warnings ?? []) {
          formatWarnings.push({
            ruleId: warning.code,
            ruleName: 'target-hook-compatibility',
            severity: 'warning',
            message: warning.message,
            ...(warning.suggestion ? { suggestion: warning.suggestion } : {}),
            ...(warning.location ? { location: warning.location } : {}),
          });
        }

        planCandidates.push({ output, owner: formatter.name, role: 'primary' });
      } catch (err) {
        formatErrors.push({
          name: 'FormatterError',
          code: 'PS4000',
          message: `Formatter '${formatter.name}' failed: ${err instanceof Error ? err.message : String(err)}`,
        });
      }
    }

    // Inject PromptScript SKILL.md into each formatter's skill directory
    if (this.options.skillContent) {
      for (const { formatter, config } of this.loadedFormatters) {
        try {
          if (!shouldIncludeSkill('promptscript', config)) {
            this.logger.debug(
              `  Skipping skill injection for ${formatter.name} (promptscript not included)`
            );
            continue;
          }

          const skillBasePath = config?.skillBaseDir
            ? normalizeOutputDir(config.skillBaseDir)
            : formatter.getSkillBasePath();
          const skillFileName = formatter.getSkillFileName();
          if (!skillBasePath || !skillFileName) {
            this.logger.debug(
              `  Skipping skill injection for ${formatter.name} (no skill support)`
            );
            continue;
          }

          const skillPath = `${skillBasePath}/promptscript/${skillFileName}`;
          const injectedContent = formatter.transformInjectedSkillContent
            ? formatter.transformInjectedSkillContent(this.options.skillContent)
            : this.options.skillContent;
          const skillOutput: FormatterOutput = {
            path: skillPath,
            content: injectedContent,
          };
          planCandidates.push({ output: skillOutput, owner: formatter.name, role: 'injected' });
        } catch (err) {
          formatErrors.push({
            name: 'FormatterError',
            code: 'PS4000',
            message: `Formatter '${formatter.name}' failed: ${err instanceof Error ? err.message : String(err)}`,
          });
        }
      }
    }

    let outputPlan: OutputPlan;
    try {
      outputPlan = createOutputPlan(planCandidates);
      for (const collision of outputPlan.collisions) {
        if (collision.identical) {
          this.logger.debug(
            `  Output path '${collision.path}' already written by '${collision.existingOwner}' with identical content. No conflict.`
          );
          continue;
        }

        const preservesExisting = collision.resolution === 'preserve-existing';
        const skippedInjectedSkill = collision.incomingRole === 'injected' && preservesExisting;
        formatWarnings.push({
          ruleId: 'PS4001',
          ruleName: 'output-path-collision',
          severity: 'warning',
          message: skippedInjectedSkill
            ? `Output path '${collision.path}' is already written by '${collision.existingOwner}'. ` +
              `Skipping auto-injected PromptScript skill for '${collision.incomingOwner}'.`
            : `Output path '${collision.path}' is written by both '${collision.existingOwner}' and ` +
              `'${collision.incomingOwner}' with different content or write settings. ` +
              (preservesExisting
                ? 'The first output will be preserved.'
                : 'The latter will overwrite the former.'),
          suggestion: skippedInjectedSkill
            ? 'The user-defined skill takes precedence. To use the bundled skill, remove the custom one or rename it.'
            : 'Configure distinct output paths for these formatters, or disable one of them.',
        });
      }

      for (const file of outputPlan.injected) {
        this.logger.verbose(`  → ${file.path} (auto-injected promptscript skill)`);
      }

      const markedFiles = outputPlan.files.map((file) => {
        const target = file.role === 'injected' ? 'promptscript' : file.owner;
        const marked = addMarkerToOutput(
          {
            path: file.path,
            content: file.content,
            ...(file.mode !== undefined ? { mode: file.mode } : {}),
            ...(file.merge !== undefined ? { merge: file.merge } : {}),
            ...(file.managedOutputDirectories !== undefined
              ? { managedOutputDirectories: file.managedOutputDirectories }
              : {}),
            ...(file.managedOutputFiles !== undefined
              ? { managedOutputFiles: file.managedOutputFiles }
              : {}),
          },
          sourceLabel,
          target
        );
        return { ...file, content: marked.content };
      });
      const markedOutputs = new Map(markedFiles.map((file) => [file.path, file]));
      outputPlan = {
        ...outputPlan,
        files: markedFiles,
        outputs: markedOutputs,
        resources: markedFiles.filter((file) => file.role === 'resource'),
        injected: markedFiles.filter((file) => file.role === 'injected'),
      };

      for (const file of markedFiles) {
        const output: FormatterOutput = {
          path: file.path,
          content: file.content,
          ...(file.mode !== undefined ? { mode: file.mode } : {}),
          ...(file.merge !== undefined ? { merge: file.merge } : {}),
          ...(file.managedOutputDirectories !== undefined
            ? { managedOutputDirectories: file.managedOutputDirectories }
            : {}),
          ...(file.managedOutputFiles !== undefined
            ? { managedOutputFiles: file.managedOutputFiles }
            : {}),
        };
        outputs.set(file.path, output);
        if (file.role === 'resource') {
          this.logger.verbose(`  → ${file.path} (additional)`);
        }
      }
    } catch (err) {
      formatErrors.push({
        name: 'FormatterError',
        code: 'PS4000',
        message: `Output planning failed: ${err instanceof Error ? err.message : String(err)}`,
      });
      outputPlan = createOutputPlan([]);
    }

    stats.formatTime = Date.now() - startFormat;
    stats.totalTime = Date.now() - startTotal;
    this.logger.verbose(`Format completed (${stats.formatTime}ms)`);

    const allWarnings = [...validation.warnings, ...formatWarnings];

    if (formatErrors.length > 0) {
      return {
        success: false,
        outputs,
        outputPlan,
        errors: formatErrors,
        warnings: allWarnings,
        stats,
      };
    }

    if (candidateDependencies) {
      this.commitResolvedDependencies(entryPath, candidateDependencies);
    }

    return {
      success: true,
      outputs,
      outputPlan,
      errors: [],
      warnings: allWarnings,
      stats,
    };
  }

  /**
   * Get the configured formatters.
   */
  getFormatters(): readonly Formatter[] {
    return this.loadedFormatters.map((lf) => lf.formatter);
  }

  /**
   * Compile a PromptScript file from a file path.
   * This is an alias for compile() for consistency with the documented API.
   *
   * @param filePath - Path to the PromptScript file
   * @returns Compilation result
   */
  async compileFile(filePath: string): Promise<CompileResult> {
    return this.compile(filePath);
  }

  /**
   * Compile to all registered formatters.
   * Useful when you want to ensure all formatters are used regardless of config.
   *
   * @param entryPath - Path to the entry file
   * @returns Compilation result with all formatter outputs
   */
  async compileAll(entryPath: string): Promise<CompileResult> {
    // Get all registered formatters
    const allFormatters = FormatterRegistry.list();

    // Create a new compiler with all formatters
    const compiler = new Compiler({
      ...this.options,
      formatters: allFormatters,
    });

    return compiler.compile(entryPath);
  }

  /**
   * Watch for file changes and recompile automatically.
   *
   * @param entryPath - Path to the entry file to compile
   * @param options - Watch options
   * @returns Watcher handle to control the watch process
   *
   * @example
   * ```typescript
   * const watcher = await compiler.watch('./project.prs', {
   *   onCompile: (result) => {
   *     if (result.success) {
   *       console.log('Compiled successfully');
   *     }
   *   },
   * });
   *
   * // Later, stop watching
   * await watcher.close();
   * ```
   */
  async watch(entryPath: string, options: WatchOptions = {}): Promise<Watcher> {
    // Dynamic import of chokidar to avoid bundling issues
    const { default: chokidar } = await import('chokidar');
    const { dirname, resolve } = await import('path');

    const baseDir = dirname(resolve(entryPath));
    const includePatterns = options.include ?? ['**/*.prs'];
    const excludePatterns = options.exclude ?? ['**/node_modules/**'];
    const debounceMs = options.debounce ?? 300;

    let debounceTimer: ReturnType<typeof setTimeout> | null = null;
    let pendingChanges: string[] = [];
    let compileRunning = false;
    let compilePending = false;
    let closed = false;
    let pendingRebuild: Promise<void> | null = null;
    let closePromise: Promise<void> | null = null;

    if (!this.resolvedDependencies.has(this.dependencyKey(entryPath))) {
      try {
        const result = await this.compile(entryPath);
        if (!result.success) {
          if (options.onCompile) {
            options.onCompile(result, []);
          } else if (options.onError) {
            const message =
              result.errors.map((error) => error.message).join('\n') ||
              'Initial compilation failed';
            options.onError(new Error(message));
          }
        }
      } catch (error) {
        options.onError?.(error instanceof Error ? error : new Error(String(error)));
      }
    }

    const watchPaths = [...new Set([baseDir, ...this.watchDependencyPaths(entryPath)])];
    const activeWatcher = chokidar.watch(watchPaths, {
      ignored: (path) =>
        excludePatterns.some((pattern) => matchesWatchPattern(path, pattern, baseDir)),
      persistent: true,
      ignoreInitial: true,
    });

    const toDependencyMap = (paths: readonly string[]): Map<string, Set<string>> => {
      const pathMap = new Map<string, Set<string>>();
      for (const path of paths) {
        const key = watchPathKey(path);
        const pathsForKey = pathMap.get(key) ?? new Set<string>();
        pathsForKey.add(path);
        pathMap.set(key, pathsForKey);
      }
      return pathMap;
    };
    const explicitlyWatchedPaths = new Set(
      [
        baseDir,
        ...[
          'promptscript.yaml',
          'promptscript.yml',
          '.promptscriptrc.yaml',
          '.promptscriptrc.yml',
          'promptscript.lock',
        ].map((fileName) => resolve(this.watchProjectRoot(entryPath), fileName)),
      ].map((path) => watchPathKey(path))
    );
    let dynamicDependencyPaths = toDependencyMap(this.resolvedDependencyPaths(entryPath));

    const notifyError = (error: unknown): void => {
      if (closed) return;
      options.onError?.(error instanceof Error ? error : new Error(String(error)));
    };

    const isExplicitlyWatched = (path: string): boolean => {
      if (explicitlyWatchedPaths.has(watchPathKey(path))) return true;
      return (
        options.include !== undefined &&
        includePatterns.some((pattern) => matchesWatchPattern(path, pattern, baseDir))
      );
    };

    const syncDependencyPaths = async (): Promise<void> => {
      const dependencyPaths = this.watchDependencyPaths(entryPath);
      if (typeof activeWatcher.add === 'function') {
        await activeWatcher.add(dependencyPaths);
      }
      if (closed) return;

      const nextDependencyPaths = this.resolvedDependencyPaths(entryPath);
      const nextDynamicDependencyPaths = toDependencyMap(nextDependencyPaths);
      const nextDynamicPathKeys = new Set(
        nextDependencyPaths.map((path) => normalizeWatchPath(absoluteWatchPath(path)))
      );
      const stalePaths = [...dynamicDependencyPaths.entries()].flatMap(([key, paths]) => {
        const nextPaths = nextDynamicDependencyPaths.get(key);
        return [...paths].filter(
          (path) =>
            !nextPaths?.has(path) &&
            !nextDynamicPathKeys.has(normalizeWatchPath(absoluteWatchPath(path))) &&
            !isExplicitlyWatched(path)
        );
      });
      if (stalePaths.length > 0 && typeof activeWatcher.unwatch === 'function') {
        await activeWatcher.unwatch(stalePaths);
      }
      if (closed) return;
      dynamicDependencyPaths = nextDynamicDependencyPaths;
    };

    const handleChange = async (changedFiles: string[]): Promise<void> => {
      if (closed) return;
      try {
        this.invalidateResolvers(entryPath, changedFiles);
        const result = await this.compile(entryPath);
        if (closed) return;
        await syncDependencyPaths();
        if (closed) return;
        options.onCompile?.(result, changedFiles);
      } catch (error) {
        notifyError(error);
      }
    };

    try {
      await syncDependencyPaths();
    } catch (error) {
      const setupError = new Error(
        `Failed to watch dependencies for '${entryPath}': ${
          error instanceof Error ? error.message : String(error)
        }`
      );
      notifyError(setupError);
      try {
        await activeWatcher.close();
      } catch {
        // Preserve the actionable setup error when cleanup also fails.
      }
      throw setupError;
    }

    const scheduleRecompile = (path: string): void => {
      if (closed) return;
      const absolutePath = absoluteWatchPath(path, baseDir);
      const matchesInclude = includePatterns.some((pattern) =>
        matchesWatchPattern(absolutePath, pattern, baseDir)
      );
      const matchesExclude = excludePatterns.some((pattern) =>
        matchesWatchPattern(absolutePath, pattern, baseDir)
      );
      const matchesDependency = this.watchDependencyPaths(entryPath).some((dependency) =>
        this.pathMatchesDependency(absolutePath, dependency)
      );
      if (matchesExclude || (!matchesInclude && !matchesDependency)) return;

      pendingChanges.push(path);

      if (debounceTimer) {
        clearTimeout(debounceTimer);
      }

      debounceTimer = setTimeout(() => {
        debounceTimer = null;
        if (closed) return;
        const files = [...pendingChanges];
        pendingChanges = [];
        if (compileRunning) {
          compilePending = true;
          pendingChanges.push(...files);
          return;
        }

        compileRunning = true;
        const rebuild = (async (): Promise<void> => {
          let changes = files;
          try {
            do {
              if (closed) return;
              compilePending = false;
              await handleChange(changes);
              if (debounceTimer) {
                clearTimeout(debounceTimer);
                debounceTimer = null;
              }
              changes = [...pendingChanges];
              pendingChanges = [];
            } while (!closed && (compilePending || changes.length > 0));
          } finally {
            compileRunning = false;
            if (closed) {
              pendingChanges = [];
            }
          }
        })();
        pendingRebuild = rebuild;
        void rebuild.then(
          () => {
            if (pendingRebuild === rebuild) pendingRebuild = null;
          },
          () => {
            if (pendingRebuild === rebuild) pendingRebuild = null;
          }
        );
      }, debounceMs);
    };

    activeWatcher.on('change', scheduleRecompile);
    activeWatcher.on('add', scheduleRecompile);
    activeWatcher.on('unlink', scheduleRecompile);
    activeWatcher.on('unlinkDir', scheduleRecompile);

    activeWatcher.on('error', (error: unknown) => {
      notifyError(error);
    });

    const close = (): Promise<void> => {
      if (closePromise) return closePromise;
      closed = true;
      if (debounceTimer) {
        clearTimeout(debounceTimer);
        debounceTimer = null;
      }
      pendingChanges = [];
      const rebuild = pendingRebuild;
      closePromise = (async (): Promise<void> => {
        try {
          await activeWatcher.close();
        } finally {
          if (rebuild) await rebuild;
        }
      })();
      return closePromise;
    };

    return {
      close,
    };
  }

  /**
   * Get format options for a specific target.
   */
  private getFormatOptionsForTarget(
    _targetName: string,
    config?: TargetConfig
  ): import('./types.js').FormatOptions {
    const customConventions = this.options.customConventions;
    const prettierOptions = this.options.prettier;

    const options: import('./types.js').FormatOptions = {
      outputPath: config?.output,
      version: config?.version,
      prettier: prettierOptions,
      targetConfig: config,
    };

    const conventionName = config?.convention;

    // Check if it's a custom convention
    if (conventionName && customConventions?.[conventionName]) {
      options.convention = customConventions[conventionName];
    } else if (conventionName) {
      options.convention = conventionName;
    }

    return options;
  }

  /**
   * Load and instantiate formatters from options.
   */
  private loadFormatters(formatters: CompilerOptions['formatters']): LoadedFormatter[] {
    return formatters.map((f) => {
      // String name
      if (typeof f === 'string') {
        return { formatter: this.loadFormatterByName(f) };
      }

      // Check if it's a constructor (function)
      if (typeof f === 'function') {
        const Ctor = f as FormatterConstructor;
        return { formatter: new Ctor() };
      }

      // Object with name and config (not a Formatter instance)
      if (
        'name' in f &&
        typeof f.name === 'string' &&
        !('format' in f) &&
        !('formatCanonical' in f)
      ) {
        const configObj = f as { name: string; config?: TargetConfig };
        return {
          formatter: this.loadFormatterByName(configObj.name),
          config: configObj.config,
        };
      }

      // Already a Formatter instance
      return { formatter: f as Formatter };
    });
  }

  /**
   * Dynamically load a formatter by name.
   *
   * Uses the FormatterRegistry to look up registered formatters.
   */
  private loadFormatterByName(name: string): Formatter {
    const formatter = FormatterRegistry.get(name);
    if (formatter) {
      return formatter;
    }
    throw new Error(
      `Unknown formatter: '${name}'. Available formatters: ${FormatterRegistry.list().join(', ')}`
    );
  }

  /**
   * Check if a value looks like a PSError (has code, message, and format).
   */
  private isPSErrorLike(err: unknown): err is PSError {
    return (
      typeof err === 'object' &&
      err !== null &&
      'message' in err &&
      'code' in err &&
      typeof (err as PSError).message === 'string'
    );
  }

  /**
   * Convert any error to a CompileError.
   */
  private toCompileError(err: Error | PSError): CompileError {
    const psError = err as PSError;

    return {
      name: err.name,
      code: psError.code ?? 'PS0000',
      message: err.message,
      location: psError.location
        ? {
            file: psError.location.file,
            line: psError.location.line,
            column: psError.location.column,
          }
        : undefined,
      format: psError.format ? () => psError.format() : undefined,
    };
  }

  /**
   * Convert a validation message to a CompileError.
   */
  private validationToCompileError(
    msg: import('@promptscript/validator').ValidationMessage
  ): CompileError {
    return {
      name: 'ValidationError',
      code: msg.ruleId,
      message: msg.message,
      location: msg.location
        ? {
            file: msg.location.file,
            line: msg.location.line,
            column: msg.location.column,
          }
        : undefined,
    };
  }
}

/**
 * Create a new compiler instance.
 *
 * @param options - Compiler options
 * @returns New Compiler instance
 */
export function createCompiler(options: CompilerOptions): Compiler {
  return new Compiler(options);
}

/**
 * Options for the standalone compile function.
 */
export interface CompileOptions {
  /**
   * Resolver options for resolving imports and inheritance.
   * If not provided, defaults to current working directory.
   */
  resolver?: {
    /** Base path for registry lookups (@namespace/...). Defaults to cwd. */
    registryPath?: string;
    /** Base path for local/relative file resolution. Defaults to cwd. */
    localPath?: string;
    /** Project root containing .promptscript/scripts. */
    projectRoot?: string;
    /** Whether to cache resolved ASTs. Defaults to true. */
    cache?: boolean;
  };
  /**
   * Validator configuration.
   */
  validator?: ValidatorConfig;
  /**
   * Formatters to use. If not specified, all built-in formatters are used.
   */
  formatters?: CompilerOptions['formatters'];
  /**
   * Custom conventions for formatters.
   */
  customConventions?: CompilerOptions['customConventions'];
  /**
   * Prettier formatting options for markdown output.
   */
  prettier?: CompilerOptions['prettier'];
  /**
   * Content of the PromptScript SKILL.md to inject into compilation output.
   */
  skillContent?: string;
}

/**
 * Compile a PromptScript file using default or specified options.
 *
 * This is a convenience function that creates a Compiler instance
 * and runs the compilation pipeline. For repeated compilations,
 * consider creating a Compiler instance directly for better performance.
 *
 * @param entryPath - Path to the entry PromptScript file
 * @param options - Optional compilation options
 * @returns Compilation result with outputs, errors, and stats
 *
 * @example
 * ```typescript
 * import { compile } from '@promptscript/compiler';
 *
 * // Simple usage with defaults
 * const result = await compile('./project.prs');
 *
 * // With custom options
 * const result = await compile('./project.prs', {
 *   formatters: ['github', 'claude'],
 *   resolver: { registryPath: './registry' },
 * });
 *
 * if (result.success) {
 *   for (const [path, output] of result.outputs) {
 *     console.log(`Generated: ${path}`);
 *   }
 * }
 * ```
 */
export async function compile(
  entryPath: string,
  options: CompileOptions = {}
): Promise<CompileResult> {
  // Get default formatters from registry if not specified
  const formatters: CompilerOptions['formatters'] = options.formatters ?? FormatterRegistry.list();

  // Build resolver options with sensible defaults
  const resolverOptions = {
    registryPath: options.resolver?.registryPath ?? process.cwd(),
    localPath: options.resolver?.localPath,
    projectRoot: options.resolver?.projectRoot,
    cache: options.resolver?.cache,
  };

  const compiler = new Compiler({
    resolver: resolverOptions,
    validator: options.validator,
    formatters,
    customConventions: options.customConventions,
    prettier: options.prettier,
    skillContent: options.skillContent,
  });

  return compiler.compile(entryPath);
}
