import { realpathSync } from 'fs';
import { noopLogger, type Logger, type PSError } from '@promptscript/core';
import { FormatterRegistry, formatProgram } from '@promptscript/formatters';
import {
  getVendorRepositoryRelativePath,
  RegistryCache,
  Resolver,
  type ResolvedAST,
} from '@promptscript/resolver';
import { Validator, type ValidatorConfig, type ValidationMessage } from '@promptscript/validator';
import { minimatch } from 'minimatch';
import { dirname, isAbsolute, join, relative, resolve, sep } from 'path';
import { isDeepStrictEqual } from 'node:util';
// eslint-disable-next-line @typescript-eslint/no-unused-vars -- imported for upcoming formatter integration
import { verifyReferenceIntegrity } from './reference-verifier.js';
import {
  findProjectRootMarker,
  inferProjectRoot,
  validateHookScriptResources,
} from './hook-script-validator.js';
import type {
  CompilerOptions,
  CompileResult,
  CompileStats,
  CompileError,
  Formatter,
  FormatterOutput,
  FormatterConstructor,
  TargetConfig,
  WatchOptions,
  Watcher,
} from './types.js';

/**
 * Internal representation of a loaded formatter with its config.
 */
interface LoadedFormatter {
  formatter: Formatter;
  config?: TargetConfig;
}

/** Maximum number of project-scoped resolvers retained by a long-lived compiler. */
export const MAX_ENTRY_RESOLVERS = 50;

function resolverCacheKey(projectRoot: string): string {
  return realpathSync.native(projectRoot);
}

function resolveEntryPath(entryPath: string): string {
  if (entryPath.startsWith('@')) return entryPath;
  const fileName =
    entryPath.endsWith('.prs') || entryPath.endsWith('.md') ? entryPath : `${entryPath}.prs`;
  const absolutePath = isAbsolute(fileName) ? fileName : resolve(process.cwd(), fileName);
  try {
    return realpathSync.native(absolutePath);
  } catch {
    return absolutePath;
  }
}

function normalizeRepositoryKey(value: string): string {
  return value
    .replace(/^(?:https?:\/\/|git:\/\/)/i, '')
    .replace(/^git@([^:]+):/, '$1/')
    .replace(/\.git(?=\/|$)/, '');
}

/**
 * Generate HTML marker comment that identifies files generated by PromptScript.
 * Uses HTML comment to be invisible to LLMs and rendered output.
 */
function generateHtmlMarker(source: string, target: string): string {
  const timestamp = new Date().toISOString();
  return `<!-- PromptScript ${timestamp} | source: ${source} | target: ${target} - do not edit -->`;
}

/**
 * Generate YAML comment marker for use inside YAML frontmatter.
 * Some tools (e.g. Factory AI) cannot parse HTML comments after frontmatter,
 * so we embed the marker as a YAML comment inside the frontmatter block.
 */
function generateYamlMarker(source: string, target: string): string {
  const timestamp = new Date().toISOString();
  return `# promptscript-generated: ${timestamp} | source: ${source} | target: ${target}`;
}

/**
 * Add PromptScript marker to output content if not already present.
 *
 * For files with YAML frontmatter: inserts a YAML comment inside the frontmatter.
 * This avoids breaking tools like Factory AI that cannot parse HTML comments
 * between frontmatter and content body.
 *
 * For files without frontmatter: inserts an HTML comment at the top.
 */
function addMarkerToOutput(
  output: FormatterOutput,
  source: string,
  target: string
): FormatterOutput {
  const { content, path } = output;

  // Skip if marker already present (check for both HTML and YAML patterns)
  if (content.includes('<!-- PromptScript') || content.includes('# promptscript-generated:')) {
    return output;
  }

  // Only add to markdown files
  if (!path.endsWith('.md') && !path.endsWith('.mdc')) {
    return output;
  }

  // Check for YAML frontmatter (starts with ---)
  if (content.startsWith('---')) {
    // Find the closing ---
    const closingIndex = content.indexOf('---', 3);
    if (closingIndex !== -1) {
      // Insert YAML comment marker as first line inside frontmatter
      const afterOpening = content.slice(3); // skip opening ---
      const newContent = `---\n${generateYamlMarker(source, target)}${afterOpening}`;
      return { ...output, content: newContent };
    }
  }

  // No frontmatter - add HTML marker at the beginning (after any title)
  const marker = generateHtmlMarker(source, target);
  const lines = content.split('\n');
  if (lines[0]?.startsWith('# ')) {
    // Has title - insert after title
    lines.splice(1, 0, '', marker);
  } else {
    // No title - insert at beginning
    lines.unshift(marker, '');
  }
  return { ...output, content: lines.join('\n') };
}

function normalizeOutputDir(dir: string): string {
  return dir
    .replace(/\\/g, '/')
    .replace(/^\/+/, '')
    .replace(/\/+$/g, '')
    .split('/')
    .filter((segment) => segment.length > 0 && segment !== '.' && segment !== '..')
    .join('/');
}

function matchesWatchPattern(path: string, pattern: string, baseDir: string): boolean {
  const normalizedPath = path.replace(/\\/g, '/');
  const relativePath = relative(baseDir, path).replace(/\\/g, '/');
  const candidates = [relativePath, normalizedPath].flatMap((candidate) => [
    candidate,
    candidate.endsWith('/') ? candidate : `${candidate}/`,
  ]);
  const matcherOptions = { dot: true, nocase: process.platform === 'win32' };
  return candidates.some((candidate) => minimatch(candidate, pattern, matcherOptions));
}

function shouldIncludeSkill(name: string, config?: TargetConfig): boolean {
  const includeSkills = config?.includeSkills;
  if (includeSkills === false) return false;
  if (Array.isArray(includeSkills)) return includeSkills.includes(name);
  return true;
}

function hasIdenticalWriteSemantics(
  existing: FormatterOutput,
  candidate: FormatterOutput
): boolean {
  return (
    existing.content === candidate.content &&
    existing.mode === candidate.mode &&
    isDeepStrictEqual(existing.merge, candidate.merge)
  );
}

function mergeManagedOutputMetadata(
  existing: FormatterOutput,
  candidate: FormatterOutput
): FormatterOutput {
  const managedOutputDirectories = [
    ...new Set([
      ...(existing.managedOutputDirectories ?? []),
      ...(candidate.managedOutputDirectories ?? []),
    ]),
  ];
  const managedOutputFiles = [
    ...new Set([...(existing.managedOutputFiles ?? []), ...(candidate.managedOutputFiles ?? [])]),
  ];

  return {
    ...existing,
    managedOutputDirectories:
      managedOutputDirectories.length > 0 ? managedOutputDirectories : undefined,
    managedOutputFiles: managedOutputFiles.length > 0 ? managedOutputFiles : undefined,
  };
}

/**
 * Compiler that orchestrates the PromptScript compilation pipeline.
 *
 * Pipeline stages:
 * 1. Resolve - Parse and resolve inheritance/imports
 * 2. Validate - Check AST against validation rules
 * 3. Format - Generate output for target platforms
 *
 * @example
 * ```typescript
 * const compiler = new Compiler({
 *   resolver: { registryPath: './registry' },
 *   validator: { requiredGuards: ['@core/guards/compliance'] },
 *   formatters: [new GitHubFormatter()],
 * });
 *
 * const result = await compiler.compile('./project.prs');
 * if (result.success) {
 *   for (const [outputPath, output] of result.outputs) {
 *     console.log(`Generated: ${outputPath}`);
 *   }
 * }
 * ```
 */
export class Compiler {
  private readonly resolver: Resolver;
  private readonly entryResolvers = new Map<string, Resolver>();
  private readonly validator: Validator;
  private readonly loadedFormatters: LoadedFormatter[];
  private readonly logger: Logger;
  private readonly resolvedDependencies = new Map<string, Set<string>>();

  constructor(private readonly options: CompilerOptions) {
    this.logger = options.logger ?? noopLogger;
    this.resolver = new Resolver({ ...options.resolver, logger: this.logger });
    this.validator = new Validator({ ...options.validator, logger: this.logger });
    this.loadedFormatters = this.loadFormatters(options.formatters);

    this.logger.debug(`Compiler initialized with ${this.loadedFormatters.length} formatters`);
  }

  private hasExplicitResolverScope(): boolean {
    return Boolean(this.options.resolver.localPath || this.options.resolver.projectRoot);
  }

  /**
   * Get the resolver to use for an entry file.
   *
   * Hook script validation infers the project root from the entry path, so a
   * resolver left on the cwd default would discover skills, commands and
   * agents from a different directory than the one being compiled.
   *
   * @param entryPath - Path to the entry file
   * @returns Resolver scoped to the entry file's project root
   */
  private resolverFor(entryPath: string): Resolver {
    if (this.hasExplicitResolverScope()) {
      return this.resolver;
    }

    const projectRoot = findProjectRootMarker(entryPath);
    if (!projectRoot) {
      // Keep cwd-based resolution when an entry is outside a marked project.
      return this.resolver;
    }

    const cacheKey = resolverCacheKey(projectRoot);
    const cached = this.entryResolvers.get(cacheKey);
    if (cached) return cached;

    const resolver = new Resolver({
      ...this.options.resolver,
      projectRoot: cacheKey,
      logger: this.logger,
    });
    if (this.entryResolvers.size >= MAX_ENTRY_RESOLVERS) {
      // Bound per-project caches for long-lived watch and server compilers.
      const oldestKey = this.entryResolvers.keys().next().value;
      if (oldestKey !== undefined) this.entryResolvers.delete(oldestKey);
    }
    this.entryResolvers.set(cacheKey, resolver);
    return resolver;
  }

  private dependencyKey(entryPath: string): string {
    return entryPath.startsWith('@') ? entryPath : resolveEntryPath(entryPath);
  }

  private recordResolvedDependencies(entryPath: string, resolved: ResolvedAST): void {
    const dependencies = new Set<string>();
    const paths = [
      resolveEntryPath(entryPath),
      ...(resolved.sources ?? []),
      ...(resolved.dependencies ?? []),
    ];
    for (const path of paths) {
      if (path.startsWith('@') || path.startsWith('__registry__:')) continue;
      dependencies.add(isAbsolute(path) ? resolve(path) : resolve(process.cwd(), path));
    }
    this.resolvedDependencies.set(this.dependencyKey(entryPath), dependencies);
  }

  private watchProjectRoot(entryPath: string): string {
    return resolve(
      this.options.resolver.projectRoot ??
        findProjectRootMarker(entryPath) ??
        dirname(resolve(entryPath))
    );
  }

  private watchDependencyPaths(entryPath: string): string[] {
    const key = this.dependencyKey(entryPath);
    const dependencies =
      this.resolvedDependencies.get(key) ?? new Set<string>([resolveEntryPath(entryPath)]);
    const projectRoot = this.watchProjectRoot(entryPath);
    const configPaths = [
      'promptscript.yaml',
      'promptscript.yml',
      '.promptscriptrc.yaml',
      '.promptscriptrc.yml',
      'promptscript.lock',
    ].map((fileName) => resolve(projectRoot, fileName));

    return [...new Set([...dependencies, ...configPaths])];
  }

  private pathMatchesDependency(path: string, dependency: string): boolean {
    const relation = relative(resolve(dependency), resolve(path));
    return (
      relation === '' ||
      (relation !== '..' && !relation.startsWith(`..${sep}`) && !isAbsolute(relation))
    );
  }

  private invalidateResolvers(entryPath: string, changedFiles: readonly string[]): void {
    const normalizedChanges = changedFiles.map((path) => resolve(path));
    const configNames = new Set([
      'promptscript.yaml',
      'promptscript.yml',
      '.promptscriptrc.yaml',
      '.promptscriptrc.yml',
      'promptscript.lock',
    ]);
    const projectRoot = this.watchProjectRoot(entryPath);
    const configurationPaths = new Set(
      [...configNames].map((fileName) => resolve(projectRoot, fileName))
    );
    const hasConfigurationChange = normalizedChanges.some((path) => configurationPaths.has(path));

    const resolvers = [this.resolver, ...this.entryResolvers.values()];
    for (const resolver of resolvers) {
      resolver.invalidate(normalizedChanges);
      if (hasConfigurationChange) resolver.clearCache();
    }
  }

  /**
   * Compile a PromptScript file through the full pipeline.
   *
   * @param entryPath - Path to the entry file
   * @returns Compilation result with outputs, errors, and stats
   */
  async compile(entryPath: string): Promise<CompileResult> {
    this.logger.verbose(`Entry: ${entryPath}`);
    this.logger.verbose(
      `Targets: ${this.loadedFormatters.map((f) => f.formatter.name).join(', ')}`
    );

    const resolvedEntryPath = this.hasExplicitResolverScope()
      ? entryPath
      : resolveEntryPath(entryPath);
    const resolver = this.resolverFor(resolvedEntryPath);
    const startTotal = Date.now();
    const stats: CompileStats = {
      resolveTime: 0,
      validateTime: 0,
      formatTime: 0,
      totalTime: 0,
    };

    // Compute a relative source label for markers so absolute user paths
    // are never leaked into generated output files.
    const sourceLabel = isAbsolute(entryPath) ? relative(process.cwd(), entryPath) : entryPath;

    // Stage 1: Resolve
    this.logger.verbose('=== Stage 1: Resolve ===');
    const startResolve = Date.now();
    let resolved: ResolvedAST;

    try {
      resolved = await resolver.resolve(resolvedEntryPath);
      this.recordResolvedDependencies(entryPath, resolved);
    } catch (err) {
      stats.resolveTime = Date.now() - startResolve;
      stats.totalTime = Date.now() - startTotal;
      this.logger.verbose(`Resolve failed (${stats.resolveTime}ms)`);

      return {
        success: false,
        outputs: new Map(),
        errors: [
          this.toCompileError(
            err instanceof Error
              ? err
              : this.isPSErrorLike(err)
                ? (err as PSError)
                : new Error(String(err))
          ),
        ],
        warnings: [],
        stats,
      };
    }

    stats.resolveTime = Date.now() - startResolve;
    this.logger.verbose(`Resolve completed (${stats.resolveTime}ms)`);

    // Check for resolve errors
    if (resolved.errors.length > 0 || !resolved.ast) {
      stats.totalTime = Date.now() - startTotal;
      const compatibility = resolved.ast ? this.validator.validate(resolved.ast) : undefined;
      const compatibilityErrors =
        compatibility?.errors.filter((message) => message.ruleId === 'PS018') ?? [];
      const compatibilityWarnings =
        compatibility?.warnings.filter((message) => message.ruleId === 'PS018') ?? [];

      return {
        success: false,
        outputs: new Map(),
        errors: [
          ...resolved.errors.map((error) => this.toCompileError(error)),
          ...compatibilityErrors.map((message) => this.validationToCompileError(message)),
        ],
        warnings: compatibilityWarnings,
        stats,
      };
    }

    // Stage 1.5: Reference Integrity
    const compileErrors: CompileError[] = [];
    if (!this.options.ignoreHashes && this.options.resolver.lockfile) {
      this.logger.verbose('=== Stage 1.5: Reference Integrity ===');
      // Collect registry reference paths for the validator
      const registryReferences = new Set<string>();
      const registryReferencePaths = new Map<string, Map<string, string>>();
      const cacheDir =
        this.options.resolver.cacheDir ??
        join(process.env['HOME'] ?? process.env['USERPROFILE'] ?? '/tmp', '.promptscript', 'cache');
      const registryCache = new RegistryCache(cacheDir);
      const referenceRoots: Array<{ repoUrl: string; version: string; path: string }> = [];
      for (const [repoUrl, dependency] of Object.entries(
        this.options.resolver.lockfile.dependencies
      )) {
        try {
          referenceRoots.push({
            repoUrl,
            version: dependency.version,
            path: registryCache.getCachePath(repoUrl, dependency.version),
          });
        } catch {
          // Invalid cache keys are reported by reference hash verification.
        }
        if (this.options.resolver.vendorDir) {
          try {
            referenceRoots.push({
              repoUrl,
              version: dependency.version,
              path: resolve(
                this.options.resolver.vendorDir,
                getVendorRepositoryRelativePath(repoUrl)
              ),
            });
          } catch {
            // Non-vendor repository URLs can still use configured reference roots.
          }
        }
        const configuredRoots = Object.entries(this.options.resolver.referenceRoots ?? {}).find(
          ([configuredRepoUrl]) =>
            normalizeRepositoryKey(configuredRepoUrl) === normalizeRepositoryKey(repoUrl)
        )?.[1];
        for (const path of configuredRoots ?? []) {
          referenceRoots.push({ repoUrl, version: dependency.version, path });
        }
      }
      referenceRoots.sort((left, right) => resolve(right.path).length - resolve(left.path).length);

      for (const block of resolved.ast.blocks) {
        if (block.name !== 'skills' || block.content.type !== 'ObjectContent') continue;
        const sourceFile = block.loc.file;
        const referenceRoot = sourceFile
          ? referenceRoots.find((root) => {
              const relation = relative(resolve(root.path), resolve(sourceFile));
              return (
                relation === '' ||
                (relation !== '..' && !relation.startsWith(`..${sep}`) && !isAbsolute(relation))
              );
            })
          : undefined;

        for (const [, skillValue] of Object.entries(block.content.properties)) {
          if (
            typeof skillValue !== 'object' ||
            skillValue === null ||
            !('references' in skillValue)
          )
            continue;

          const refs = (skillValue as Record<string, unknown>)['references'];
          if (!Array.isArray(refs)) continue;

          for (const ref of refs) {
            if (typeof ref !== 'string') continue;
            registryReferences.add(ref);
            if (sourceFile && referenceRoot) {
              const resolvedReference = resolve(dirname(sourceFile), ref);
              const relation = relative(resolve(referenceRoot.path), resolvedReference);
              if (
                relation !== '' &&
                relation !== '..' &&
                !relation.startsWith(`..${sep}`) &&
                !isAbsolute(relation)
              ) {
                const sourceReferences =
                  registryReferencePaths.get(sourceFile) ?? new Map<string, string>();
                const relativePath = relation.replaceAll('\\', '/');
                const referenceKey = `${referenceRoot.repoUrl}\0${relativePath}\0${referenceRoot.version}`;
                sourceReferences.set(ref, referenceKey);
                registryReferencePaths.set(sourceFile, sourceReferences);
                if (!Object.hasOwn(this.options.resolver.lockfile.references ?? {}, referenceKey)) {
                  compileErrors.push({
                    name: 'ResolveError',
                    code: 'PS2023',
                    message:
                      `Reference file "${relativePath}" has no integrity hash in lockfile. ` +
                      'Run `prs lock` to generate integrity hashes for registry references.',
                    location: block.loc,
                  });
                }
              } else {
                compileErrors.push({
                  name: 'ResolveError',
                  code: 'PS2023',
                  message: `Reference path escapes its repository: ${ref}`,
                  location: block.loc,
                });
              }
            }
          }
        }
      }

      // Verify reference file hashes against lockfile
      const hashErrors = await resolver.verifyReferenceHashes(this.options.resolver.lockfile);
      for (const err of hashErrors) {
        compileErrors.push(this.toCompileError(err));
      }

      // Pass registry references to validator for PS031 structural check
      this.validator.updateConfig({
        registryReferences,
        registryReferencePaths,
        lockfile: this.options.resolver.lockfile,
        ignoreHashes: this.options.ignoreHashes,
      });
    } else if (this.options.ignoreHashes) {
      this.logger.verbose('--ignore-hashes is set: reference integrity verification is disabled');
      console.error('⚠ --ignore-hashes is set: reference integrity verification is disabled');
      this.validator.updateConfig({ ignoreHashes: true });
    }

    // Check for reference integrity errors
    if (compileErrors.length > 0) {
      stats.totalTime = Date.now() - startTotal;
      return {
        success: false,
        outputs: new Map(),
        errors: compileErrors,
        warnings: [],
        stats,
      };
    }

    // Stage 2: Validate
    this.logger.verbose('=== Stage 2: Validate ===');
    const startValidate = Date.now();
    const validation = this.validator.validate(resolved.ast);

    // Check for validation errors
    if (!validation.valid) {
      stats.validateTime = Date.now() - startValidate;
      this.logger.verbose(`Validate completed (${stats.validateTime}ms)`);
      stats.totalTime = Date.now() - startTotal;

      return {
        success: false,
        outputs: new Map(),
        errors: validation.errors.map((e) => this.validationToCompileError(e)),
        warnings: validation.warnings,
        stats,
      };
    }

    const hookScriptErrors = await validateHookScriptResources(
      resolved.ast,
      inferProjectRoot(
        this.options.resolver.localPath,
        this.options.resolver.projectRoot,
        resolvedEntryPath
      )
    );
    stats.validateTime = Date.now() - startValidate;
    this.logger.verbose(`Validate completed (${stats.validateTime}ms)`);
    if (hookScriptErrors.length > 0) {
      stats.totalTime = Date.now() - startTotal;
      return {
        success: false,
        outputs: new Map(),
        errors: hookScriptErrors,
        warnings: validation.warnings,
        stats,
      };
    }

    // Stage 3: Format
    this.logger.verbose('=== Stage 3: Format ===');
    const startFormat = Date.now();
    const outputs = new Map<string, FormatterOutput>();
    const formatErrors: CompileError[] = [];
    const formatWarnings: ValidationMessage[] = [];
    const outputPathOwners = new Map<string, string>();
    // Output as produced by the formatter, before the generated marker is added.
    // Markers embed the target name and a timestamp, so comparing marked content
    // would report every shared path as a conflict.
    const outputPathDefinitions = new Map<string, FormatterOutput>();

    for (const { formatter, config } of this.loadedFormatters) {
      const formatterStart = Date.now();
      this.logger.verbose(`Formatting for ${formatter.name}`);

      try {
        const formatOptions = this.getFormatOptionsForTarget(formatter.name, config);
        this.logger.debug(`  Convention: ${formatOptions.convention ?? 'default'}`);

        const output = formatProgram(formatter, resolved.ast, formatOptions);
        const formatterTime = Date.now() - formatterStart;

        this.logger.verbose(`  → ${output.path} (${formatterTime}ms)`);

        for (const warning of output.warnings ?? []) {
          formatWarnings.push({
            ruleId: warning.code,
            ruleName: 'target-hook-compatibility',
            severity: 'warning',
            message: warning.message,
            ...(warning.suggestion ? { suggestion: warning.suggestion } : {}),
            ...(warning.location ? { location: warning.location } : {}),
          });
        }

        // Warn if multiple formatters target the same output path with different content
        const existingOwner = outputPathOwners.get(output.path);
        const existingDefinition = outputPathDefinitions.get(output.path);
        const isIdenticalOutput =
          existingOwner !== undefined &&
          existingDefinition !== undefined &&
          hasIdenticalWriteSemantics(existingDefinition, output);
        if (existingOwner !== undefined) {
          if (isIdenticalOutput) {
            this.logger.debug(
              `  Output path '${output.path}' already written by '${existingOwner}' with identical content. No conflict.`
            );
            const existingOutput = outputs.get(output.path);
            if (existingOutput) {
              outputs.set(output.path, mergeManagedOutputMetadata(existingOutput, output));
            }
          } else {
            formatWarnings.push({
              ruleId: 'PS4001',
              ruleName: 'output-path-collision',
              severity: 'warning',
              message: `Output path '${output.path}' is written by both '${existingOwner}' and '${formatter.name}' with different content. The latter will overwrite the former.`,
              suggestion: `Configure distinct output paths for these formatters, or disable one of them.`,
            });
          }
        }

        if (!isIdenticalOutput) {
          outputPathOwners.set(output.path, formatter.name);
          outputPathDefinitions.set(output.path, output);

          // Add PromptScript marker to all outputs for overwrite detection
          const markedOutput = addMarkerToOutput(output, sourceLabel, formatter.name);
          const previousManagedDirectories =
            outputs.get(output.path)?.managedOutputDirectories ?? [];
          const previousManagedFiles = outputs.get(output.path)?.managedOutputFiles ?? [];
          const managedOutputDirectories = [
            ...new Set([
              ...previousManagedDirectories,
              ...(markedOutput.managedOutputDirectories ?? []),
            ]),
          ];
          const managedOutputFiles = [
            ...new Set([...previousManagedFiles, ...(markedOutput.managedOutputFiles ?? [])]),
          ];
          outputs.set(output.path, {
            ...markedOutput,
            managedOutputDirectories:
              managedOutputDirectories.length > 0 ? managedOutputDirectories : undefined,
            managedOutputFiles: managedOutputFiles.length > 0 ? managedOutputFiles : undefined,
          });
        }

        // Also add any additional files (e.g., .cursor/commands/, .github/prompts/)
        // Recursively collect nested additionalFiles (e.g., skill resource files)
        if (output.additionalFiles) {
          const queue = [...output.additionalFiles];
          while (queue.length > 0) {
            const additionalFile = queue.shift()!;
            this.logger.verbose(`  → ${additionalFile.path} (additional)`);

            // Check for path collisions with previously written outputs
            const existingAdditionalOwner = outputPathOwners.get(additionalFile.path);
            if (existingAdditionalOwner) {
              const existingAdditionalDefinition = outputPathDefinitions.get(additionalFile.path);
              if (
                existingAdditionalDefinition &&
                hasIdenticalWriteSemantics(existingAdditionalDefinition, additionalFile)
              ) {
                this.logger.debug(
                  `  Output path '${additionalFile.path}' already written by '${existingAdditionalOwner}' with identical content. No conflict.`
                );
              } else {
                formatWarnings.push({
                  ruleId: 'PS4001',
                  ruleName: 'output-path-collision',
                  severity: 'warning',
                  message: `Output path '${additionalFile.path}' is written by both '${existingAdditionalOwner}' and '${formatter.name}' with different content or write settings. The first output will be preserved.`,
                  suggestion: `Configure distinct output paths for these formatters, or disable one of them.`,
                });
              }
              // Skip writing this additional file — preserve the original owner's output
              if (additionalFile.additionalFiles) {
                queue.push(...additionalFile.additionalFiles);
              }
              continue;
            }
            outputPathOwners.set(additionalFile.path, formatter.name);
            outputPathDefinitions.set(additionalFile.path, additionalFile);

            outputs.set(
              additionalFile.path,
              addMarkerToOutput(additionalFile, sourceLabel, formatter.name)
            );
            if (additionalFile.additionalFiles) {
              queue.push(...additionalFile.additionalFiles);
            }
          }
        }
      } catch (err) {
        formatErrors.push({
          name: 'FormatterError',
          code: 'PS4000',
          message: `Formatter '${formatter.name}' failed: ${err instanceof Error ? err.message : String(err)}`,
        });
      }
    }

    // Inject PromptScript SKILL.md into each formatter's skill directory
    if (this.options.skillContent) {
      for (const { formatter, config } of this.loadedFormatters) {
        try {
          if (!shouldIncludeSkill('promptscript', config)) {
            this.logger.debug(
              `  Skipping skill injection for ${formatter.name} (promptscript not included)`
            );
            continue;
          }

          const skillBasePath = config?.skillBaseDir
            ? normalizeOutputDir(config.skillBaseDir)
            : formatter.getSkillBasePath();
          const skillFileName = formatter.getSkillFileName();
          if (!skillBasePath || !skillFileName) {
            this.logger.debug(
              `  Skipping skill injection for ${formatter.name} (no skill support)`
            );
            continue;
          }

          const skillPath = `${skillBasePath}/promptscript/${skillFileName}`;
          const injectedContent = formatter.transformInjectedSkillContent
            ? formatter.transformInjectedSkillContent(this.options.skillContent)
            : this.options.skillContent;
          const skillOutput: FormatterOutput = {
            path: skillPath,
            content: injectedContent,
          };
          const existingOwner = outputPathOwners.get(skillPath);
          if (existingOwner) {
            // Preserve previously written skills and warn on differing content.
            const existingDefinition = outputPathDefinitions.get(skillPath);
            if (existingDefinition && hasIdenticalWriteSemantics(existingDefinition, skillOutput)) {
              this.logger.debug(
                `  Skill path '${skillPath}' already written by '${existingOwner}' with identical content. No conflict.`
              );
            } else {
              formatWarnings.push({
                ruleId: 'PS4001',
                ruleName: 'output-path-collision',
                severity: 'warning',
                message: `Output path '${skillPath}' is already written by '${existingOwner}'. Skipping auto-injected PromptScript skill for '${formatter.name}'.`,
                suggestion: `The user-defined skill takes precedence. To use the bundled skill, remove the custom one or rename it.`,
              });
            }
            continue;
          }
          outputPathOwners.set(skillPath, `${formatter.name}:promptscript-skill`);
          outputPathDefinitions.set(skillPath, skillOutput);

          outputs.set(skillPath, addMarkerToOutput(skillOutput, sourceLabel, 'promptscript'));
          this.logger.verbose(`  → ${skillPath} (auto-injected promptscript skill)`);
        } catch (err) {
          formatErrors.push({
            name: 'FormatterError',
            code: 'PS4000',
            message: `Formatter '${formatter.name}' failed: ${err instanceof Error ? err.message : String(err)}`,
          });
        }
      }
    }

    stats.formatTime = Date.now() - startFormat;
    stats.totalTime = Date.now() - startTotal;
    this.logger.verbose(`Format completed (${stats.formatTime}ms)`);

    const allWarnings = [...validation.warnings, ...formatWarnings];

    if (formatErrors.length > 0) {
      return {
        success: false,
        outputs,
        errors: formatErrors,
        warnings: allWarnings,
        stats,
      };
    }

    return {
      success: true,
      outputs,
      errors: [],
      warnings: allWarnings,
      stats,
    };
  }

  /**
   * Get the configured formatters.
   */
  getFormatters(): readonly Formatter[] {
    return this.loadedFormatters.map((lf) => lf.formatter);
  }

  /**
   * Compile a PromptScript file from a file path.
   * This is an alias for compile() for consistency with the documented API.
   *
   * @param filePath - Path to the PromptScript file
   * @returns Compilation result
   */
  async compileFile(filePath: string): Promise<CompileResult> {
    return this.compile(filePath);
  }

  /**
   * Compile to all registered formatters.
   * Useful when you want to ensure all formatters are used regardless of config.
   *
   * @param entryPath - Path to the entry file
   * @returns Compilation result with all formatter outputs
   */
  async compileAll(entryPath: string): Promise<CompileResult> {
    // Get all registered formatters
    const allFormatters = FormatterRegistry.list();

    // Create a new compiler with all formatters
    const compiler = new Compiler({
      ...this.options,
      formatters: allFormatters,
    });

    return compiler.compile(entryPath);
  }

  /**
   * Watch for file changes and recompile automatically.
   *
   * @param entryPath - Path to the entry file to compile
   * @param options - Watch options
   * @returns Watcher handle to control the watch process
   *
   * @example
   * ```typescript
   * const watcher = await compiler.watch('./project.prs', {
   *   onCompile: (result) => {
   *     if (result.success) {
   *       console.log('Compiled successfully');
   *     }
   *   },
   * });
   *
   * // Later, stop watching
   * await watcher.close();
   * ```
   */
  async watch(entryPath: string, options: WatchOptions = {}): Promise<Watcher> {
    // Dynamic import of chokidar to avoid bundling issues
    const { default: chokidar } = await import('chokidar');
    const { dirname, resolve } = await import('path');

    const baseDir = dirname(resolve(entryPath));
    const includePatterns = options.include ?? ['**/*.prs'];
    const excludePatterns = options.exclude ?? ['**/node_modules/**'];
    const debounceMs = options.debounce ?? 300;

    let debounceTimer: ReturnType<typeof setTimeout> | null = null;
    let pendingChanges: string[] = [];
    let compileRunning = false;
    let compilePending = false;

    if (!this.resolvedDependencies.has(this.dependencyKey(entryPath))) {
      try {
        const result = await this.compile(entryPath);
        if (!result.success) {
          if (options.onCompile) {
            options.onCompile(result, []);
          } else if (options.onError) {
            const message =
              result.errors.map((error) => error.message).join('\n') ||
              'Initial compilation failed';
            options.onError(new Error(message));
          }
        }
      } catch (error) {
        options.onError?.(error instanceof Error ? error : new Error(String(error)));
      }
    }

    const watchPaths = [...new Set([baseDir, ...this.watchDependencyPaths(entryPath)])];
    const activeWatcher = chokidar.watch(watchPaths, {
      ignored: (path) =>
        excludePatterns.some((pattern) => matchesWatchPattern(path, pattern, baseDir)),
      persistent: true,
      ignoreInitial: true,
    });

    const handleChange = async (changedFiles: string[]): Promise<void> => {
      try {
        this.invalidateResolvers(entryPath, changedFiles);
        const result = await this.compile(entryPath);
        const dependencyPaths = this.watchDependencyPaths(entryPath);
        if (typeof activeWatcher.add === 'function') {
          await activeWatcher.add(dependencyPaths);
        }
        options.onCompile?.(result, changedFiles);
      } catch (error) {
        options.onError?.(error instanceof Error ? error : new Error(String(error)));
      }
    };

    if (typeof activeWatcher.add === 'function') {
      await activeWatcher.add(this.watchDependencyPaths(entryPath));
    }

    const scheduleRecompile = (path: string): void => {
      const absolutePath = isAbsolute(path) ? resolve(path) : resolve(baseDir, path);
      const matchesInclude = includePatterns.some((pattern) =>
        matchesWatchPattern(absolutePath, pattern, baseDir)
      );
      const matchesExclude = excludePatterns.some((pattern) =>
        matchesWatchPattern(absolutePath, pattern, baseDir)
      );
      const matchesDependency = this.watchDependencyPaths(entryPath).some((dependency) =>
        this.pathMatchesDependency(absolutePath, dependency)
      );
      if (matchesExclude || (!matchesInclude && !matchesDependency)) return;

      pendingChanges.push(path);

      if (debounceTimer) {
        clearTimeout(debounceTimer);
      }

      debounceTimer = setTimeout(() => {
        debounceTimer = null;
        const files = [...pendingChanges];
        pendingChanges = [];
        if (compileRunning) {
          compilePending = true;
          pendingChanges.push(...files);
          return;
        }

        compileRunning = true;
        void (async (): Promise<void> => {
          let changes = files;
          do {
            compilePending = false;
            await handleChange(changes);
            if (debounceTimer) {
              clearTimeout(debounceTimer);
              debounceTimer = null;
            }
            changes = [...pendingChanges];
            pendingChanges = [];
          } while (compilePending || changes.length > 0);
          compileRunning = false;
        })();
      }, debounceMs);
    };

    activeWatcher.on('change', scheduleRecompile);
    activeWatcher.on('add', scheduleRecompile);
    activeWatcher.on('unlink', scheduleRecompile);
    activeWatcher.on('unlinkDir', scheduleRecompile);

    activeWatcher.on('error', (error: unknown) => {
      options.onError?.(error instanceof Error ? error : new Error(String(error)));
    });

    return {
      close: async () => {
        if (debounceTimer) {
          clearTimeout(debounceTimer);
        }
        await activeWatcher.close();
      },
    };
  }

  /**
   * Get format options for a specific target.
   */
  private getFormatOptionsForTarget(
    _targetName: string,
    config?: TargetConfig
  ): import('./types.js').FormatOptions {
    const customConventions = this.options.customConventions;
    const prettierOptions = this.options.prettier;

    const options: import('./types.js').FormatOptions = {
      outputPath: config?.output,
      version: config?.version,
      prettier: prettierOptions,
      targetConfig: config,
    };

    const conventionName = config?.convention;

    // Check if it's a custom convention
    if (conventionName && customConventions?.[conventionName]) {
      options.convention = customConventions[conventionName];
    } else if (conventionName) {
      options.convention = conventionName;
    }

    return options;
  }

  /**
   * Load and instantiate formatters from options.
   */
  private loadFormatters(formatters: CompilerOptions['formatters']): LoadedFormatter[] {
    return formatters.map((f) => {
      // String name
      if (typeof f === 'string') {
        return { formatter: this.loadFormatterByName(f) };
      }

      // Check if it's a constructor (function)
      if (typeof f === 'function') {
        const Ctor = f as FormatterConstructor;
        return { formatter: new Ctor() };
      }

      // Object with name and config (not a Formatter instance)
      if ('name' in f && typeof f.name === 'string' && !('format' in f)) {
        const configObj = f as { name: string; config?: TargetConfig };
        return {
          formatter: this.loadFormatterByName(configObj.name),
          config: configObj.config,
        };
      }

      // Already a Formatter instance
      return { formatter: f as Formatter };
    });
  }

  /**
   * Dynamically load a formatter by name.
   *
   * Uses the FormatterRegistry to look up registered formatters.
   */
  private loadFormatterByName(name: string): Formatter {
    const formatter = FormatterRegistry.get(name);
    if (formatter) {
      return formatter;
    }
    throw new Error(
      `Unknown formatter: '${name}'. Available formatters: ${FormatterRegistry.list().join(', ')}`
    );
  }

  /**
   * Check if a value looks like a PSError (has code, message, and format).
   */
  private isPSErrorLike(err: unknown): err is PSError {
    return (
      typeof err === 'object' &&
      err !== null &&
      'message' in err &&
      'code' in err &&
      typeof (err as PSError).message === 'string'
    );
  }

  /**
   * Convert any error to a CompileError.
   */
  private toCompileError(err: Error | PSError): CompileError {
    const psError = err as PSError;

    return {
      name: err.name,
      code: psError.code ?? 'PS0000',
      message: err.message,
      location: psError.location
        ? {
            file: psError.location.file,
            line: psError.location.line,
            column: psError.location.column,
          }
        : undefined,
      format: psError.format ? () => psError.format() : undefined,
    };
  }

  /**
   * Convert a validation message to a CompileError.
   */
  private validationToCompileError(
    msg: import('@promptscript/validator').ValidationMessage
  ): CompileError {
    return {
      name: 'ValidationError',
      code: msg.ruleId,
      message: msg.message,
      location: msg.location
        ? {
            file: msg.location.file,
            line: msg.location.line,
            column: msg.location.column,
          }
        : undefined,
    };
  }
}

/**
 * Create a new compiler instance.
 *
 * @param options - Compiler options
 * @returns New Compiler instance
 */
export function createCompiler(options: CompilerOptions): Compiler {
  return new Compiler(options);
}

/**
 * Options for the standalone compile function.
 */
export interface CompileOptions {
  /**
   * Resolver options for resolving imports and inheritance.
   * If not provided, defaults to current working directory.
   */
  resolver?: {
    /** Base path for registry lookups (@namespace/...). Defaults to cwd. */
    registryPath?: string;
    /** Base path for local/relative file resolution. Defaults to cwd. */
    localPath?: string;
    /** Project root containing .promptscript/scripts. */
    projectRoot?: string;
    /** Whether to cache resolved ASTs. Defaults to true. */
    cache?: boolean;
  };
  /**
   * Validator configuration.
   */
  validator?: ValidatorConfig;
  /**
   * Formatters to use. If not specified, all built-in formatters are used.
   */
  formatters?: CompilerOptions['formatters'];
  /**
   * Custom conventions for formatters.
   */
  customConventions?: CompilerOptions['customConventions'];
  /**
   * Prettier formatting options for markdown output.
   */
  prettier?: CompilerOptions['prettier'];
  /**
   * Content of the PromptScript SKILL.md to inject into compilation output.
   */
  skillContent?: string;
}

/**
 * Compile a PromptScript file using default or specified options.
 *
 * This is a convenience function that creates a Compiler instance
 * and runs the compilation pipeline. For repeated compilations,
 * consider creating a Compiler instance directly for better performance.
 *
 * @param entryPath - Path to the entry PromptScript file
 * @param options - Optional compilation options
 * @returns Compilation result with outputs, errors, and stats
 *
 * @example
 * ```typescript
 * import { compile } from '@promptscript/compiler';
 *
 * // Simple usage with defaults
 * const result = await compile('./project.prs');
 *
 * // With custom options
 * const result = await compile('./project.prs', {
 *   formatters: ['github', 'claude'],
 *   resolver: { registryPath: './registry' },
 * });
 *
 * if (result.success) {
 *   for (const [path, output] of result.outputs) {
 *     console.log(`Generated: ${path}`);
 *   }
 * }
 * ```
 */
export async function compile(
  entryPath: string,
  options: CompileOptions = {}
): Promise<CompileResult> {
  // Get default formatters from registry if not specified
  const formatters: CompilerOptions['formatters'] = options.formatters ?? FormatterRegistry.list();

  // Build resolver options with sensible defaults
  const resolverOptions = {
    registryPath: options.resolver?.registryPath ?? process.cwd(),
    localPath: options.resolver?.localPath,
    projectRoot: options.resolver?.projectRoot,
    cache: options.resolver?.cache,
  };

  const compiler = new Compiler({
    resolver: resolverOptions,
    validator: options.validator,
    formatters,
    customConventions: options.customConventions,
    prettier: options.prettier,
    skillContent: options.skillContent,
  });

  return compiler.compile(entryPath);
}
