import { FormatterRegistry } from '@promptscript/formatters';
import { detectFormat, type DetectedFormat } from '@promptscript/importer';
import { isAbsolute, relative, resolve } from 'path';
import { type CliServices, createDefaultServices } from '../services.js';

/**
 * AI tool target identifier — corresponds to a registered formatter name.
 */
export type AIToolTarget = string;

/**
 * Enriched migration candidate with metadata about the instruction file.
 */
export interface MigrationCandidate {
  path: string;
  format: DetectedFormat;
  sizeBytes: number;
  sizeHuman: string;
  toolName: string;
}

/**
 * AI tool detection result.
 */
export interface AIToolsDetection {
  /** Detected AI tools with existing configuration */
  detected: AIToolTarget[];
  /** Details about detected files */
  details: Record<string, string[]>;
  /** Files that exist but were NOT generated by PromptScript (candidates for migration) */
  migrationCandidates: MigrationCandidate[];
}

/**
 * File patterns for each AI tool.
 */
interface AIToolPattern {
  target: AIToolTarget;
  files: string[];
  directories: string[];
}

/**
 * Marker comment that indicates a file was generated by PromptScript.
 */
const PROMPTSCRIPT_MARKERS = [
  '<!-- PromptScript',
  '# promptscript-generated:',
  '> Auto-generated by PromptScript',
];

/**
 * Files that are instruction files (not just config) and can be migrated.
 */
const INSTRUCTION_FILES = [
  'CLAUDE.md',
  'claude.md',
  '.cursorrules',
  '.github/copilot-instructions.md',
  'AGENTS.md',
  'AI_INSTRUCTIONS.md',
  'AI.md',
  'OPENCODE.md',
  'GEMINI.md',
  '.windsurfrules',
  '.clinerules',
  '.goosehints',
  'augment-guidelines.md',
  'codex.md',
];

function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  return `${(bytes / 1024).toFixed(1)} KB`;
}

const FILE_TOOL_NAMES: Record<string, string> = {
  'CLAUDE.md': 'Claude Code',
  'claude.md': 'Claude Code',
  '.cursorrules': 'Cursor',
  '.github/copilot-instructions.md': 'GitHub Copilot',
  'AGENTS.md': 'Shared AGENTS.md',
  'OPENCODE.md': 'OpenCode',
  'GEMINI.md': 'Gemini CLI',
  '.windsurfrules': 'Windsurf',
  '.clinerules': 'Cline',
  '.goosehints': 'Goose',
  'augment-guidelines.md': 'Augment',
  'codex.md': 'Codex',
  'AI_INSTRUCTIONS.md': 'Generic',
  'AI.md': 'Generic',
};

function toolNameForFile(file: string): string {
  const normalized = file.replace(/\\/g, '/');
  if (normalized.startsWith('.github/instructions/')) return 'GitHub Copilot';
  if (normalized.startsWith('.cursor/rules/')) return 'Cursor';
  if (normalized.startsWith('.windsurf/rules/')) return 'Windsurf';
  if (normalized.startsWith('.roo/rules/')) return 'Roo Code';
  if (normalized.startsWith('.cline/rules/')) return 'Cline';
  return FILE_TOOL_NAMES[file] ?? 'Unknown';
}

/**
 * Known detection patterns for AI tools.
 * Used to detect existing configurations on disk.
 * Formatters without explicit patterns here can still be selected as targets.
 */
const AI_TOOL_PATTERNS: AIToolPattern[] = [
  {
    target: 'github',
    files: ['.github/copilot-instructions.md'],
    directories: ['.github/instructions', '.github/prompts', '.github/skills'],
  },
  {
    target: 'claude',
    files: ['CLAUDE.md', '.claude/settings.json', 'claude.md'],
    directories: ['.claude'],
  },
  {
    target: 'cursor',
    files: ['.cursor/rules/project.mdc', '.cursorrules', '.cursor/rules.md'],
    directories: ['.cursor', '.cursor/rules'],
  },
  {
    target: 'antigravity',
    files: ['.agent/rules/project.md'],
    directories: ['.agent', '.agent/rules'],
  },
  {
    target: 'factory',
    files: ['.factory/config.json'],
    directories: ['.factory', '.factory/skills'],
  },
  {
    target: 'opencode',
    files: ['OPENCODE.md'],
    directories: ['.opencode', '.opencode/commands', '.opencode/skills', '.opencode/agents'],
  },
  {
    target: 'gemini',
    files: ['GEMINI.md', '.gemini/settings.json'],
    directories: ['.gemini', '.gemini/commands', '.gemini/skills'],
  },
  {
    target: 'windsurf',
    files: ['.windsurfrules'],
    directories: ['.windsurf'],
  },
  {
    target: 'cline',
    files: ['.clinerules'],
    directories: ['.cline'],
  },
  {
    target: 'roo',
    files: ['.roo/rules/project.md'],
    directories: ['.roo', '.roo/rules'],
  },
  {
    target: 'codex',
    files: ['codex.md'],
    directories: ['.codex'],
  },
  {
    target: 'continue',
    files: ['.continue/config.json', '.continue/rules/project.md'],
    directories: ['.continue'],
  },
  {
    target: 'augment',
    files: ['augment-guidelines.md', '.augment/config.json'],
    directories: ['.augment'],
  },
  {
    target: 'goose',
    files: ['.goosehints'],
    directories: [],
  },
  {
    target: 'kilo',
    files: ['.kilo/rules/project.md'],
    directories: ['.kilo'],
  },
  {
    target: 'amp',
    files: [],
    directories: ['.ampt'],
  },
  {
    target: 'trae',
    files: ['.trae/rules/project.md'],
    directories: ['.trae'],
  },
  {
    target: 'junie',
    files: ['.junie/guidelines.md'],
    directories: ['.junie'],
  },
  {
    target: 'kiro',
    files: ['.kiro/rules/project.md'],
    directories: ['.kiro'],
  },
];

interface InstructionDirectoryPattern {
  directory: string;
  matches: (fileName: string) => boolean;
}

const INSTRUCTION_DIRECTORY_PATTERNS: InstructionDirectoryPattern[] = [
  {
    directory: '.github/instructions',
    matches: (fileName) => fileName.endsWith('.instructions.md'),
  },
  {
    directory: '.cursor/rules',
    matches: (fileName) => fileName.endsWith('.mdc'),
  },
  {
    directory: '.windsurf/rules',
    matches: (fileName) => fileName.endsWith('.md'),
  },
  {
    directory: '.roo/rules',
    matches: (fileName) => fileName.endsWith('.md'),
  },
  {
    directory: '.cline/rules',
    matches: (fileName) => fileName.endsWith('.md'),
  },
];

/**
 * Check if a directory exists and is not empty.
 */
async function directoryHasContent(dir: string, services: CliServices): Promise<boolean> {
  if (!services.fs.existsSync(dir)) return false;
  try {
    const entries = await services.fs.readdir(dir);
    return entries.length > 0;
  } catch {
    return false;
  }
}

/**
 * Check if a file was generated by PromptScript.
 * PromptScript-generated files contain a marker comment near the top.
 */
function isPromptScriptGenerated(content: string): boolean {
  const header = content.slice(0, 500);
  return PROMPTSCRIPT_MARKERS.some((marker) => header.includes(marker));
}

async function assertSafeInstructionFile(filePath: string, services: CliServices): Promise<void> {
  const absolutePath = resolve(services.cwd, filePath);
  if (services.fs.lstat) {
    const stat = await services.fs.lstat(absolutePath);
    if (!stat.isFile() || stat.isSymbolicLink()) {
      throw new Error(`Instruction candidate must be a regular file: ${filePath}`);
    }
  }
  if (services.fs.realpath) {
    const [projectRoot, candidatePath] = await Promise.all([
      services.fs.realpath(services.cwd),
      services.fs.realpath(absolutePath),
    ]);
    const relativePath = relative(projectRoot, candidatePath);
    if (
      relativePath === '..' ||
      relativePath.startsWith(`..${process.platform === 'win32' ? '\\' : '/'}`) ||
      isAbsolute(relativePath)
    ) {
      throw new Error(`Instruction candidate must stay inside the project: ${filePath}`);
    }
  }
}

async function discoverInstructionFiles(services: CliServices): Promise<string[]> {
  const files = [...INSTRUCTION_FILES];

  for (const pattern of INSTRUCTION_DIRECTORY_PATTERNS) {
    if (!services.fs.existsSync(pattern.directory)) continue;
    try {
      const entries = await services.fs.readdir(pattern.directory);
      for (const entry of entries) {
        if (typeof entry === 'string' && pattern.matches(entry)) {
          files.push(`${pattern.directory}/${entry}`);
        }
      }
    } catch {
      continue;
    }
  }

  return Array.from(new Set(files));
}

/**
 * Detect existing AI tool configurations.
 */
export async function detectAITools(
  services: CliServices = createDefaultServices()
): Promise<AIToolsDetection> {
  const detected: AIToolTarget[] = [];
  const details: Record<string, string[]> = {};
  const migrationCandidates: MigrationCandidate[] = [];

  for (const pattern of AI_TOOL_PATTERNS) {
    const foundFiles: string[] = [];

    // Check specific files
    for (const file of pattern.files) {
      if (services.fs.existsSync(file)) {
        foundFiles.push(file);
      }
    }

    // Check directories
    for (const dir of pattern.directories) {
      if (await directoryHasContent(dir, services)) {
        foundFiles.push(`${dir}/`);
      }
    }

    if (foundFiles.length > 0) {
      detected.push(pattern.target);
      details[pattern.target] = foundFiles;
    }
  }

  // Check for instruction files that are NOT PromptScript-generated
  const instructionFiles = await discoverInstructionFiles(services);
  for (const file of instructionFiles) {
    if (services.fs.existsSync(file)) {
      await assertSafeInstructionFile(file, services);
      let content: string;
      try {
        content = await services.fs.readFile(file, 'utf-8');
      } catch (error) {
        throw new Error(
          `Cannot read instruction candidate ${file}: ${
            error instanceof Error ? error.message : String(error)
          }`,
          { cause: error }
        );
      }
      if (!isPromptScriptGenerated(content)) {
        const sizeBytes = Buffer.byteLength(content, 'utf-8');
        migrationCandidates.push({
          path: file,
          format: detectFormat(file),
          sizeBytes,
          sizeHuman: formatFileSize(sizeBytes),
          toolName: toolNameForFile(file),
        });
      }
    }
  }

  return { detected, details, migrationCandidates };
}

/**
 * Get all available targets from the FormatterRegistry.
 */
export function getAllTargets(): AIToolTarget[] {
  return FormatterRegistry.list();
}

/**
 * Get suggested targets based on detection.
 * Only strongly detected tools are suggested.
 */
export function getSuggestedTargets(detection: AIToolsDetection): AIToolTarget[] {
  return detection.detected;
}

/**
 * Format detection results for display.
 */
export function formatDetectionResults(detection: AIToolsDetection): string[] {
  const lines: string[] = [];

  if (detection.detected.length === 0) {
    lines.push('No existing AI tool configurations detected.');
    return lines;
  }

  lines.push('Detected AI tool configurations:');

  for (const target of detection.detected) {
    const files = detection.details[target];
    if (files) {
      lines.push(`  • ${target}: ${files.join(', ')}`);
    }
  }

  return lines;
}

/**
 * Check if there are migration candidates (non-PromptScript instruction files).
 */
export function hasMigrationCandidates(detection: AIToolsDetection): boolean {
  return detection.migrationCandidates.length > 0;
}

/**
 * Format migration hint for display.
 */
export function formatMigrationHint(detection: AIToolsDetection): string[] {
  if (detection.migrationCandidates.length === 0) {
    return [];
  }

  const lines: string[] = [];
  lines.push('');
  lines.push('Existing instruction files detected:');
  for (const c of detection.migrationCandidates) {
    lines.push(`   - ${c.path} (${c.sizeHuman}, ${c.toolName})`);
  }
  lines.push('');
  lines.push('   These can be migrated to PromptScript for unified management.');
  lines.push('   Run: prs migrate');
  lines.push('   See: https://getpromptscript.dev/latest/guides/ai-migration-best-practices');

  return lines;
}
