import { type CliServices, createDefaultServices } from '../services.js';

/**
 * Supported AI tool targets.
 */
export type AIToolTarget = 'github' | 'claude' | 'cursor' | 'antigravity';

/**
 * AI tool detection result.
 */
export interface AIToolsDetection {
  /** Detected AI tools with existing configuration */
  detected: AIToolTarget[];
  /** Details about detected files */
  details: Record<AIToolTarget, string[]>;
  /** Files that exist but were NOT generated by PromptScript (candidates for migration) */
  migrationCandidates: string[];
}

/**
 * File patterns for each AI tool.
 */
interface AIToolPattern {
  target: AIToolTarget;
  files: string[];
  directories: string[];
}

/**
 * Marker comment that indicates a file was generated by PromptScript.
 */
const PROMPTSCRIPT_MARKER = 'PromptScript';

/**
 * Files that are instruction files (not just config) and can be migrated.
 */
const INSTRUCTION_FILES = [
  'CLAUDE.md',
  'claude.md',
  '.cursorrules',
  '.github/copilot-instructions.md',
  'AGENTS.md',
  'AI_INSTRUCTIONS.md',
  'AI.md',
];

const AI_TOOL_PATTERNS: AIToolPattern[] = [
  {
    target: 'github',
    files: ['.github/copilot-instructions.md'],
    directories: ['.github'],
  },
  {
    target: 'claude',
    files: ['CLAUDE.md', '.claude/settings.json', 'claude.md'],
    directories: ['.claude'],
  },
  {
    target: 'cursor',
    files: ['.cursor/rules/project.mdc', '.cursorrules', '.cursor/rules.md'],
    directories: ['.cursor', '.cursor/rules'],
  },
  {
    target: 'antigravity',
    files: ['.agent/rules/project.md'],
    directories: ['.agent', '.agent/rules'],
  },
];

/**
 * Check if a directory exists and is not empty.
 */
async function directoryHasContent(dir: string, services: CliServices): Promise<boolean> {
  if (!services.fs.existsSync(dir)) return false;
  try {
    const entries = await services.fs.readdir(dir);
    return entries.length > 0;
  } catch {
    return false;
  }
}

/**
 * Check if a file was generated by PromptScript.
 * PromptScript-generated files contain a marker comment near the top.
 */
async function isPromptScriptGenerated(filePath: string, services: CliServices): Promise<boolean> {
  try {
    const content = await services.fs.readFile(filePath, 'utf-8');
    // Check first 500 characters for the marker (it's usually in the first few lines)
    const header = content.slice(0, 500);
    return header.includes(PROMPTSCRIPT_MARKER);
  } catch {
    return false;
  }
}

/**
 * Detect existing AI tool configurations.
 */
export async function detectAITools(
  services: CliServices = createDefaultServices()
): Promise<AIToolsDetection> {
  const detected: AIToolTarget[] = [];
  const details: Record<AIToolTarget, string[]> = {
    github: [],
    claude: [],
    cursor: [],
    antigravity: [],
  };
  const migrationCandidates: string[] = [];

  for (const pattern of AI_TOOL_PATTERNS) {
    const foundFiles: string[] = [];

    // Check specific files
    for (const file of pattern.files) {
      if (services.fs.existsSync(file)) {
        foundFiles.push(file);
      }
    }

    // Check directories
    for (const dir of pattern.directories) {
      if (await directoryHasContent(dir, services)) {
        foundFiles.push(`${dir}/`);
      }
    }

    if (foundFiles.length > 0) {
      detected.push(pattern.target);
      details[pattern.target] = foundFiles;
    }
  }

  // Check for instruction files that are NOT PromptScript-generated
  for (const file of INSTRUCTION_FILES) {
    if (services.fs.existsSync(file)) {
      const isGenerated = await isPromptScriptGenerated(file, services);
      if (!isGenerated) {
        migrationCandidates.push(file);
      }
    }
  }

  return { detected, details, migrationCandidates };
}

/**
 * Get all available targets.
 */
export function getAllTargets(): AIToolTarget[] {
  return ['github', 'claude', 'cursor', 'antigravity'];
}

/**
 * Get suggested targets based on detection.
 * If no tools detected, suggest all. Otherwise, suggest detected ones.
 */
export function getSuggestedTargets(detection: AIToolsDetection): AIToolTarget[] {
  return detection.detected.length > 0 ? detection.detected : getAllTargets();
}

/**
 * Format detection results for display.
 */
export function formatDetectionResults(detection: AIToolsDetection): string[] {
  const lines: string[] = [];

  if (detection.detected.length === 0) {
    lines.push('No existing AI tool configurations detected.');
    return lines;
  }

  lines.push('Detected AI tool configurations:');

  for (const target of detection.detected) {
    const files = detection.details[target];
    lines.push(`  • ${target}: ${files.join(', ')}`);
  }

  return lines;
}

/**
 * Check if there are migration candidates (non-PromptScript instruction files).
 */
export function hasMigrationCandidates(detection: AIToolsDetection): boolean {
  return detection.migrationCandidates.length > 0;
}

/**
 * Format migration hint for display.
 */
export function formatMigrationHint(detection: AIToolsDetection): string[] {
  if (detection.migrationCandidates.length === 0) {
    return [];
  }

  const lines: string[] = [];
  lines.push('');
  lines.push('📋 Existing instruction files detected:');
  for (const file of detection.migrationCandidates) {
    lines.push(`   • ${file}`);
  }
  lines.push('');
  lines.push('   These can be migrated to PromptScript for unified management.');
  lines.push('   See: https://getpromptscript.dev/latest/guides/ai-migration-best-practices');
  lines.push('   Or use the /migrate skill in Claude Code.');

  return lines;
}
