import { constants, existsSync } from 'node:fs';
import { execFile, spawn } from 'node:child_process';
import { createHash } from 'node:crypto';
import {
  lstat,
  mkdir,
  open,
  readFile,
  readdir,
  rmdir,
  unlink,
  type FileHandle,
} from 'node:fs/promises';
import { basename, dirname, isAbsolute, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';
import type { FormatterOutput } from '@promptscript/compiler';
import { resolveSelfInvocation, type SelfInvocation } from '../runtime/self-invocation.js';
import { MANAGED_OUTPUT_WORKER_COMMAND } from '../managed-output-worker.js';

const execFileAsync = promisify(execFile);
const PROMPTSCRIPT_MARKER_PATTERNS = [
  /^<!-- PromptScript \d{4}-\d{2}-\d{2}T[\d:.]+Z \| source: .+ \| target: .+ - do not edit -->$/,
  /^# promptscript-generated: \d{4}-\d{2}-\d{2}T[\d:.]+Z \| source: .+ \| target: .+$/,
  /^\/\/ promptscript-generated: opencode-plugin$/,
  /^\/\/ Generated by PromptScript - do not edit\.$/,
  /^> Auto-generated by PromptScript(?:\s.*)?$/,
] as const;
const OWNED_COMMAND_FIELDS = new Set([
  'bash',
  'command',
  'commandWindows',
  'command_windows',
  'cwd',
  'matcher',
  'powershell',
  'statusMessage',
  'status_message',
  'timeout',
  'timeoutSec',
  'type',
  'windows',
  'working_directory',
]);
/**
 * Resolve the managed output worker module path relative to this module.
 *
 * Published installs bundle the worker next to the main bundle
 * (dist/managed-output-worker.js); in development the TypeScript source
 * (src/managed-output-worker.ts) is spawned directly via Node type
 * stripping. Deno standalone binaries never use this path - they re-execute
 * the binary itself.
 */
function resolveWorkerModulePath(): string | undefined {
  const bundled = fileURLToPath(new URL('./managed-output-worker.js', import.meta.url));
  if (existsSync(bundled)) return bundled;
  const source = fileURLToPath(new URL('../managed-output-worker.ts', import.meta.url));
  return existsSync(source) ? source : undefined;
}

let cachedWorkerModulePath: string | undefined | null = null;

/**
 * Resolve how this process spawns the managed output worker. The worker
 * module path is resolved once; the invocation itself is resolved per
 * operation so the runtime and process.execPath are read fresh, matching
 * the per-spawn reads of the previous inline-script implementation.
 * Undefined means no safe self-invocation exists and every guarded
 * operation fails closed.
 */
function getWorkerSelfInvocation(): SelfInvocation | undefined {
  if (cachedWorkerModulePath === null) {
    cachedWorkerModulePath = resolveWorkerModulePath();
  }
  return resolveSelfInvocation({ workerPath: cachedWorkerModulePath });
}

/** Build the worker argv: <prefix> <hidden command> <operation> <args...> */
function workerSpawnArgs(
  invocation: SelfInvocation,
  operation: string,
  ...operationArgs: string[]
): string[] {
  return [...invocation.prefixArgs, MANAGED_OUTPUT_WORKER_COMMAND, operation, ...operationArgs];
}

export interface ManagedOutputCleanupResult {
  /** Obsolete files removed, or that would be removed in dry-run mode */
  removed: string[];
  /** Mixed hook files rewritten to remove PromptScript-owned entries */
  rewritten?: string[];
  /** Managed directories pruned because they became empty */
  removedDirectories: string[];
  /**
   * True when this runtime could not resolve a safe way to run the guarded
   * worker, so cleanup was skipped and obsolete output was left in place.
   * Callers must warn and exit non-zero.
   */
  unresolvedSelfInvocation?: boolean;
}

export interface ManagedOutputCleanupOptions {
  /** Absolute base directory used to resolve formatter output paths */
  outputRoot: string;
  /** Report actions without modifying the filesystem */
  dryRun?: boolean;
}

interface DirectoryGuard {
  path: string;
  handle: FileHandle;
}

interface FileIdentity {
  dev: number | bigint;
  ino: number | bigint;
}

/**
 * Remove obsolete generated files from formatter-declared managed directories.
 *
 * Only regular files carrying a PromptScript marker are eligible. Directory
 * symlinks and file symlinks are skipped, and unmarked files are preserved.
 */
export async function cleanupManagedOutputs(
  outputs: Map<string, FormatterOutput>,
  options: ManagedOutputCleanupOptions
): Promise<ManagedOutputCleanupResult> {
  const outputRoot = resolve(options.outputRoot);
  const managedDirectories = collectManagedDirectories(outputs, outputRoot);
  const managedFiles = collectManagedFiles(outputs, outputRoot);
  const desiredFiles = collectDesiredFiles(outputs, outputRoot);
  const removed: string[] = [];
  const rewritten: string[] = [];
  const removedDirectories: string[] = [];
  let unresolvedWorker = false;
  const reportUnresolvedWorker = (): void => {
    unresolvedWorker = true;
  };

  for (const directory of managedDirectories) {
    const ancestorGuards = await openAncestorDirectories(outputRoot, directory);
    if (!ancestorGuards) continue;
    try {
      await visitDirectory(
        directory,
        desiredFiles,
        options.dryRun === true,
        removed,
        ancestorGuards,
        reportUnresolvedWorker
      );
    } finally {
      await closeDirectoryGuards(ancestorGuards);
    }
  }

  for (const file of managedFiles) {
    if (desiredFiles.has(file)) continue;
    await removeManagedFile(
      file,
      outputRoot,
      options.dryRun === true,
      removed,
      rewritten,
      reportUnresolvedWorker
    );
  }

  // Prune managed directories left empty by the removals (e.g. .github/hooks
  // after the obsolete promptscript.json is deleted). Deepest first so a
  // parent can be pruned right after its last child directory disappears.
  // Skipped entirely when nothing was removed so read-only runs never touch
  // directories the cleanup did not empty itself.
  if (removed.length > 0) {
    const prunable = managedDirectories
      .filter((directory) => removed.some((file) => isWithin(directory, file)))
      .sort((a, b) => b.length - a.length);
    const managedDirectorySet = new Set(managedDirectories);
    for (const directory of prunable) {
      await pruneEmptyDirectory(directory, outputRoot, options.dryRun === true, {
        removed,
        removedDirectories,
        managedDirectories: managedDirectorySet,
      });
    }
  }

  return {
    removed,
    ...(rewritten.length > 0 ? { rewritten } : {}),
    removedDirectories,
    ...(unresolvedWorker ? { unresolvedSelfInvocation: true } : {}),
  };
}

interface PruneTracker {
  removed: string[];
  removedDirectories: string[];
  managedDirectories: ReadonlySet<string>;
}

/**
 * Remove a directory when every entry inside it is gone (or, in dry-run mode,
 * would be gone). Returns true when the directory is (or would be) removed.
 * Never removes the output root itself or follows symlinks.
 */
async function pruneEmptyDirectory(
  directory: string,
  outputRoot: string,
  dryRun: boolean,
  tracker: PruneTracker
): Promise<boolean> {
  if (resolve(directory) === outputRoot) return false;
  const ancestorGuards = await openAncestorDirectories(outputRoot, directory);
  if (!ancestorGuards) return false;
  try {
    if (!(await directoryGuardsMatch(ancestorGuards))) return false;
    const directoryStat = await safeLstat(directory);
    if (!directoryStat?.isDirectory() || directoryStat.isSymbolicLink()) return false;
    const directoryHandle = await safeOpenDirectory(directory);
    if (!directoryHandle) return false;

    try {
      const entries = await readdir(directory, { withFileTypes: true });
      let empty = true;
      for (const entry of entries) {
        const entryPath = resolve(directory, entry.name);
        if (entry.isDirectory()) {
          if (!tracker.managedDirectories.has(entryPath)) {
            empty = false;
            continue;
          }
          if (!(await pruneEmptyDirectory(entryPath, outputRoot, dryRun, tracker))) {
            empty = false;
          }
          continue;
        }
        if (!(dryRun && tracker.removed.includes(entryPath))) {
          empty = false;
        }
      }
      if (!empty) return false;

      if (dryRun) {
        tracker.removedDirectories.push(directory);
        return true;
      }

      if (!(await directoryGuardsMatch(ancestorGuards))) return false;
      try {
        await rmdir(directory);
        tracker.removedDirectories.push(directory);
        return true;
      } catch (error: unknown) {
        // Lost a race with an external writer or the directory is already gone.
        if (isNodeError(error) && (error.code === 'ENOTEMPTY' || error.code === 'ENOENT')) {
          return false;
        }
        throw error;
      }
    } finally {
      await directoryHandle.close();
    }
  } finally {
    await closeDirectoryGuards(ancestorGuards);
  }
}

function collectManagedDirectories(
  outputs: Map<string, FormatterOutput>,
  outputRoot: string
): string[] {
  const directories = new Set<string>();

  for (const output of outputs.values()) {
    for (const directory of output.managedOutputDirectories ?? []) {
      const normalized = directory.replace(/\\/g, '/');
      if (!normalized || isAbsolute(normalized)) continue;
      if (normalized.split('/').some((segment) => segment === '..')) continue;

      const absolutePath = resolve(outputRoot, normalized);
      if (isWithin(outputRoot, absolutePath)) directories.add(absolutePath);
    }
  }

  return [...directories].sort();
}

function collectDesiredFiles(
  outputs: Map<string, FormatterOutput>,
  outputRoot: string
): Set<string> {
  const files = new Set<string>();
  for (const output of outputs.values()) {
    const absolutePath = resolve(outputRoot, output.path);
    if (isWithin(outputRoot, absolutePath)) files.add(absolutePath);
  }
  return files;
}

function collectManagedFiles(outputs: Map<string, FormatterOutput>, outputRoot: string): string[] {
  const files = new Set<string>();

  for (const output of outputs.values()) {
    for (const file of output.managedOutputFiles ?? []) {
      const normalized = file.replace(/\\/g, '/');
      if (!normalized || isAbsolute(normalized)) continue;
      if (normalized.split('/').some((segment) => segment === '..')) continue;

      const absolutePath = resolve(outputRoot, normalized);
      if (isWithin(outputRoot, absolutePath)) files.add(absolutePath);
    }
  }

  return [...files].sort();
}

async function removeManagedFile(
  file: string,
  outputRoot: string,
  dryRun: boolean,
  removed: string[],
  rewritten: string[],
  onUnresolvedWorker: () => void
): Promise<void> {
  const fileStat = await safeLstat(file);
  if (!fileStat?.isFile() || fileStat.isSymbolicLink()) return;
  const content = await readFile(file, 'utf-8');
  const prunedHooks =
    removePromptScriptOwnedHooks(file, content) ?? removePromptScriptOwnedCodexHooks(file, content);
  if (!prunedHooks && !(await isPromptScriptGenerated(file, true))) return;

  const guards = await openAncestorDirectories(outputRoot, file);
  if (!guards) return;
  try {
    if (!(await directoryGuardsMatch(guards))) return;
    if (dryRun) {
      if (!prunedHooks || prunedHooks.empty) {
        removed.push(file);
      } else {
        rewritten.push(file);
      }
      return;
    }

    const directory = dirname(file);
    const directoryStat = await safeLstat(directory);
    if (!directoryStat?.isDirectory() || directoryStat.isSymbolicLink()) return;

    if (prunedHooks && !prunedHooks.empty) {
      const didRewrite = await guardedRewrite(
        {
          directory,
          name: basename(file),
          directoryStat,
          fileStat,
          expectedContent: content,
          content: prunedHooks.content,
        },
        onUnresolvedWorker
      );
      if (didRewrite) rewritten.push(file);
      return;
    }

    if (
      await guardedUnlink(
        directory,
        basename(file),
        directoryStat,
        fileStat,
        undefined,
        onUnresolvedWorker
      )
    ) {
      removed.push(file);
    }
  } finally {
    await closeDirectoryGuards(guards);
  }
}

export async function rewriteHookOutputIfUnchanged(
  file: string,
  outputRoot: string,
  expectedContent: string,
  content: string,
  mode?: number
): Promise<boolean> {
  const root = resolve(outputRoot);
  const candidate = resolve(file);
  if (!isWithin(root, candidate)) return false;

  const fileStat = await safeLstat(candidate);
  if (!fileStat?.isFile() || fileStat.isSymbolicLink()) return false;
  const guards = await openAncestorDirectories(root, candidate);
  if (!guards) return false;
  try {
    if (!(await directoryGuardsMatch(guards))) return false;
    const directory = dirname(candidate);
    const directoryStat = await safeLstat(directory);
    if (!directoryStat?.isDirectory() || directoryStat.isSymbolicLink()) return false;

    return guardedRewrite({
      directory,
      name: basename(candidate),
      directoryStat,
      fileStat,
      expectedContent,
      content,
      mode,
    });
  } finally {
    await closeDirectoryGuards(guards);
  }
}

export async function createHookOutputSafely(
  file: string,
  outputRoot: string,
  content: string,
  mode = 0o666
): Promise<boolean> {
  const root = resolve(outputRoot);
  const candidate = resolve(file);
  if (!isWithin(root, candidate)) return false;

  const guards = await openOrCreateAncestorDirectories(root, candidate);
  if (!guards) return false;
  try {
    if (!(await directoryGuardsMatch(guards))) return false;
    const directory = dirname(candidate);
    const directoryStat = await safeLstat(directory);
    if (!directoryStat?.isDirectory() || directoryStat.isSymbolicLink()) {
      return false;
    }

    return guardedCreate(directory, basename(candidate), directoryStat, content, mode);
  } finally {
    await closeDirectoryGuards(guards);
  }
}

export async function removeHookOutputIfUnchanged(
  file: string,
  outputRoot: string,
  expectedContent: string
): Promise<boolean> {
  const root = resolve(outputRoot);
  const candidate = resolve(file);
  if (!isWithin(root, candidate)) return false;

  const fileStat = await safeLstat(candidate);
  if (!fileStat?.isFile() || fileStat.isSymbolicLink()) return false;
  const guards = await openAncestorDirectories(root, candidate);
  if (!guards) return false;
  try {
    if (!(await directoryGuardsMatch(guards))) return false;
    const directory = dirname(candidate);
    const directoryStat = await safeLstat(directory);
    if (!directoryStat?.isDirectory() || directoryStat.isSymbolicLink()) return false;

    return guardedUnlink(directory, basename(candidate), directoryStat, fileStat, expectedContent);
  } finally {
    await closeDirectoryGuards(guards);
  }
}

/** One guarded rewrite request: what to replace and with what. */
interface GuardedRewriteRequest {
  directory: string;
  name: string;
  directoryStat: FileIdentity;
  fileStat: FileIdentity;
  expectedContent: string;
  content: string;
  mode?: number;
}

async function guardedRewrite(
  request: GuardedRewriteRequest,
  onUnresolvedWorker?: () => void
): Promise<boolean> {
  const invocation = getWorkerSelfInvocation();
  if (invocation === undefined) {
    onUnresolvedWorker?.();
    return false;
  }
  const expectedHash = createHash('sha256').update(request.expectedContent).digest('hex');

  return new Promise((resolveResult) => {
    const child = spawn(
      invocation.executable,
      workerSpawnArgs(
        invocation,
        'rewrite',
        request.name,
        String(request.directoryStat.dev),
        String(request.directoryStat.ino),
        String(request.fileStat.dev),
        String(request.fileStat.ino),
        expectedHash,
        request.mode === undefined ? '' : String(request.mode)
      ),
      {
        cwd: request.directory,
        stdio: ['pipe', 'pipe', 'ignore'],
        windowsHide: true,
      }
    );
    let stdout = '';
    child.stdout.setEncoding('utf-8');
    child.stdout.on('data', (chunk: string) => {
      stdout += chunk;
    });
    child.on('error', () => {
      resolveResult(false);
    });
    child.on('close', (code) => {
      resolveResult(code === 0 && stdout === 'rewritten');
    });
    child.stdin.on('error', () => {
      resolveResult(false);
    });
    child.stdin.end(request.content);
  });
}

async function guardedCreate(
  directory: string,
  name: string,
  directoryStat: FileIdentity,
  content: string,
  mode: number
): Promise<boolean> {
  const invocation = getWorkerSelfInvocation();
  if (invocation === undefined) {
    return false;
  }
  return new Promise((resolveResult) => {
    const child = spawn(
      invocation.executable,
      workerSpawnArgs(
        invocation,
        'create',
        name,
        String(directoryStat.dev),
        String(directoryStat.ino),
        String(mode)
      ),
      {
        cwd: directory,
        stdio: ['pipe', 'pipe', 'ignore'],
        windowsHide: true,
      }
    );
    let stdout = '';
    child.stdout.setEncoding('utf-8');
    child.stdout.on('data', (chunk: string) => {
      stdout += chunk;
    });
    child.on('error', () => {
      resolveResult(false);
    });
    child.on('close', (code) => {
      resolveResult(code === 0 && stdout === 'created');
    });
    child.stdin.on('error', () => {
      resolveResult(false);
    });
    child.stdin.end(content);
  });
}

async function visitDirectory(
  directory: string,
  desiredFiles: Set<string>,
  dryRun: boolean,
  removed: string[],
  ancestorGuards: DirectoryGuard[],
  onUnresolvedWorker: () => void
): Promise<void> {
  const directoryHandle = await safeOpenDirectory(directory);
  if (!directoryHandle) return;
  const guards = [...ancestorGuards, { path: directory, handle: directoryHandle }];

  try {
    if (!(await directoryGuardsMatch(guards))) return;

    const entries = await readdir(directory, { withFileTypes: true });
    entries.sort((left, right) => left.name.localeCompare(right.name));
    for (const entry of entries) {
      const entryPath = resolve(directory, entry.name);
      const entryStat = await safeLstat(entryPath);
      if (!entryStat || entryStat.isSymbolicLink()) continue;

      if (entryStat.isDirectory()) {
        await visitDirectory(entryPath, desiredFiles, dryRun, removed, guards, onUnresolvedWorker);
        continue;
      }

      if (!entryStat.isFile() || desiredFiles.has(entryPath)) continue;
      if (!(await isPromptScriptGenerated(entryPath))) continue;
      if (!(await directoryGuardsMatch(guards))) continue;

      if (dryRun) {
        removed.push(entryPath);
        continue;
      }

      const currentStat = await safeLstat(entryPath);
      if (
        currentStat?.isFile() &&
        !currentStat.isSymbolicLink() &&
        isSameFile(entryStat, currentStat) &&
        (await directoryGuardsMatch(guards))
      ) {
        const directoryStat = await directoryHandle.stat();
        if (
          await guardedUnlink(
            directory,
            entry.name,
            directoryStat,
            entryStat,
            undefined,
            onUnresolvedWorker
          )
        ) {
          removed.push(entryPath);
        }
      }
    }
  } finally {
    await directoryHandle.close();
  }
}

async function guardedUnlink(
  directory: string,
  name: string,
  directoryStat: FileIdentity,
  fileStat: FileIdentity,
  expectedContent?: string,
  onUnresolvedWorker?: () => void
): Promise<boolean> {
  const invocation = getWorkerSelfInvocation();
  if (invocation === undefined) {
    // Fail closed: without a resolvable self-invocation there is no way to
    // run the worker, and guarded operations never degrade to in-process
    // filesystem writes.
    onUnresolvedWorker?.();
    return false;
  }
  const expectedHash =
    expectedContent === undefined
      ? undefined
      : createHash('sha256').update(expectedContent).digest('hex');
  try {
    const result = await execFileAsync(
      invocation.executable,
      workerSpawnArgs(
        invocation,
        'unlink',
        name,
        String(directoryStat.dev),
        String(directoryStat.ino),
        String(fileStat.dev),
        String(fileStat.ino),
        ...(expectedHash === undefined ? [] : [expectedHash])
      ),
      {
        cwd: directory,
        encoding: 'utf-8',
        windowsHide: true,
      }
    );
    return result.stdout === 'removed';
  } catch {
    // Runtimes where the worker cannot be spawned (packaged binaries with a
    // broken executable path, restricted spawn environments) fall back to an
    // in-process guarded unlink that re-verifies the file identity immediately
    // before removing it. Only the unlink without expected content has this
    // fallback; everything else stays failed.
    if (expectedContent !== undefined) return false;
    return removeIfUnchanged(resolve(directory, name), fileStat);
  }
}

/**
 * Remove a file only when it is still a regular (non-symlink) file whose device
 * and inode match the previously observed identity. Used as an in-process
 * fallback when a child process cannot perform the cwd-relative guarded unlink.
 */
export async function removeIfUnchanged(
  entryPath: string,
  fileStat: FileIdentity
): Promise<boolean> {
  const current = await safeLstat(entryPath);
  if (!current?.isFile() || current.isSymbolicLink() || !isSameIdentity(current, fileStat)) {
    return false;
  }

  try {
    await unlink(entryPath);
  } catch (error: unknown) {
    /* v8 ignore next 2 -- unlink races with external removal between check and delete */
    if (isNodeError(error) && error.code === 'ENOENT') return false;
    throw error;
  }
  return true;
}

async function openAncestorDirectories(
  root: string,
  directory: string
): Promise<DirectoryGuard[] | undefined> {
  const relativePath = relative(root, directory);
  const segments = relativePath === '' ? [] : relativePath.split(/[\\/]+/);
  const paths = [root];
  let current = root;
  for (const segment of segments.slice(0, -1)) {
    current = resolve(current, segment);
    paths.push(current);
  }

  const guards: DirectoryGuard[] = [];
  for (const path of paths) {
    const handle = await safeOpenDirectory(path);
    if (!handle) {
      await closeDirectoryGuards(guards);
      return undefined;
    }
    guards.push({ path, handle });
    if (!(await directoryGuardsMatch(guards))) {
      await closeDirectoryGuards(guards);
      return undefined;
    }
  }
  return guards;
}

async function openOrCreateAncestorDirectories(
  root: string,
  file: string
): Promise<DirectoryGuard[] | undefined> {
  const relativePath = relative(root, file);
  if (relativePath.startsWith('..') || isAbsolute(relativePath)) {
    return undefined;
  }

  await mkdir(root, { recursive: true });
  const guards: DirectoryGuard[] = [];
  const rootHandle = await safeOpenDirectory(root);
  if (!rootHandle) return undefined;
  guards.push({ path: root, handle: rootHandle });

  let current = root;
  const segments = relativePath.split(/[\\/]+/).slice(0, -1);
  for (const segment of segments) {
    if (!(await directoryGuardsMatch(guards))) {
      await closeDirectoryGuards(guards);
      return undefined;
    }
    const parentStat = await guards.at(-1)!.handle.stat();
    if (!(await guardedMkdir(current, segment, parentStat))) {
      await closeDirectoryGuards(guards);
      return undefined;
    }
    current = resolve(current, segment);
    const handle = await safeOpenDirectory(current);
    if (!handle) {
      await closeDirectoryGuards(guards);
      return undefined;
    }
    guards.push({ path: current, handle });
  }

  return guards;
}

async function guardedMkdir(
  directory: string,
  name: string,
  directoryStat: FileIdentity
): Promise<boolean> {
  const invocation = getWorkerSelfInvocation();
  if (invocation === undefined) {
    return false;
  }
  try {
    const result = await execFileAsync(
      invocation.executable,
      workerSpawnArgs(
        invocation,
        'mkdir',
        name,
        String(directoryStat.dev),
        String(directoryStat.ino)
      ),
      {
        cwd: directory,
        encoding: 'utf-8',
        windowsHide: true,
      }
    );
    return result.stdout === 'ready';
  } catch {
    return false;
  }
}

async function closeDirectoryGuards(guards: DirectoryGuard[]): Promise<void> {
  for (const guard of [...guards].reverse()) {
    await guard.handle.close();
  }
}

/** Platform-optional open flags, probed on first use: 0 where the runtime lacks them. */
let openNofollowFlag: number | undefined;
let openDirectoryFlag: number | undefined;

async function safeOpenDirectory(path: string): Promise<FileHandle | undefined> {
  try {
    // Probed lazily (not at module load) so test doubles that replace
    // node:fs wholesale still load this module.
    openNofollowFlag ??= constants.O_NOFOLLOW ?? 0;
    openDirectoryFlag ??= constants.O_DIRECTORY ?? 0;
    return await open(path, constants.O_RDONLY | openDirectoryFlag | openNofollowFlag);
  } catch (error: unknown) {
    if (
      isNodeError(error) &&
      (error.code === 'ENOENT' || error.code === 'ENOTDIR' || error.code === 'ELOOP')
    ) {
      return undefined;
    }
    throw error;
  }
}

async function directoryGuardsMatch(guards: DirectoryGuard[]): Promise<boolean> {
  for (const guard of guards) {
    const pathStat = await safeLstat(guard.path);
    if (!pathStat?.isDirectory() || pathStat.isSymbolicLink()) return false;
    const handleStat = await guard.handle.stat();
    if (!isSameFile(pathStat, handleStat)) return false;
  }
  return true;
}

function isSameFile(
  left: Awaited<ReturnType<typeof lstat>>,
  right: Awaited<ReturnType<typeof lstat>>
): boolean {
  return left.dev === right.dev && left.ino === right.ino;
}

function isSameIdentity(
  stat: { dev: number | bigint; ino: number | bigint },
  identity: FileIdentity
): boolean {
  return stat.dev === identity.dev && stat.ino === identity.ino;
}

async function safeLstat(path: string): Promise<Awaited<ReturnType<typeof lstat>> | undefined> {
  try {
    return await lstat(path);
  } catch (error: unknown) {
    if (isNodeError(error) && error.code === 'ENOENT') return undefined;
    throw error;
  }
}

async function isPromptScriptGenerated(path: string, allowInlineMarker = false): Promise<boolean> {
  try {
    const content = await readFile(path, 'utf-8');
    const lines = content
      .replace(/^\uFEFF/, '')
      .split(/\r?\n/)
      .slice(0, 4);
    const candidateLines =
      lines[0] === '---'
        ? [lines[1]]
        : [lines[0], ...(lines[0]?.startsWith('# ') && lines[1] === '' ? [lines[2]] : [])];
    const hasStandardMarker = candidateLines.some(
      (line) =>
        line !== undefined && PROMPTSCRIPT_MARKER_PATTERNS.some((pattern) => pattern.test(line))
    );
    return hasStandardMarker || (allowInlineMarker && isPromptScriptOwnedHookOutput(path, content));
  } catch (error: unknown) {
    if (isNodeError(error) && error.code === 'ENOENT') return false;
    throw error;
  }
}

interface HookOwnershipScan {
  found: boolean;
  valid: boolean;
}

export function hasOnlyOwnedHookCommands(content: string): boolean {
  try {
    const parsed: unknown = JSON.parse(content);
    if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) return false;
    const hooks = (parsed as Record<string, unknown>)['hooks'];
    const scan = scanHookOwnership(hooks);
    return scan.found && scan.valid;
  } catch {
    return false;
  }
}

const OWNED_HOOK_OUTPUT_FIELDS: ReadonlyArray<{
  suffix: string;
  fields: ReadonlySet<string>;
}> = [
  { suffix: '.factory/hooks.json', fields: new Set(['hooks']) },
  { suffix: '.codex/hooks.json', fields: new Set(['hooks']) },
  {
    suffix: '.github/hooks/promptscript.json',
    fields: new Set(['version', 'hooks']),
  },
  {
    suffix: '.github/hooks/promptscript-vscode.json',
    fields: new Set(['hooks']),
  },
  {
    suffix: '.claude/settings.json',
    fields: new Set(['hooks']),
  },
  {
    suffix: '.cursor/hooks.json',
    fields: new Set(['version', 'hooks']),
  },
  { suffix: '.gemini/settings.json', fields: new Set(['hooks']) },
  { suffix: '.windsurf/hooks.json', fields: new Set(['hooks']) },
  {
    suffix: '.grok/hooks/promptscript.json',
    fields: new Set(['hooks']),
  },
];

export function isPromptScriptOwnedHookOutput(path: string, content: string): boolean {
  const normalizedPath = path.replaceAll('\\', '/');
  const contract = getHookOutputContract(normalizedPath);
  if (!contract) return false;

  try {
    const parsed: unknown = JSON.parse(content);
    if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
      return false;
    }
    const object = parsed as Record<string, unknown>;
    if (Object.keys(object).some((field) => !contract.fields.has(field))) {
      return false;
    }
    const scan = scanHookOwnership(object['hooks']);
    return scan.found && scan.valid;
  } catch {
    return false;
  }
}

export function isHookOutputPath(path: string): boolean {
  const normalized = path.replaceAll('\\', '/');
  return (
    getHookOutputContract(normalized) !== undefined || normalized.endsWith('.codex/config.toml')
  );
}

function getHookOutputContract(
  path: string
): (typeof OWNED_HOOK_OUTPUT_FIELDS)[number] | undefined {
  return OWNED_HOOK_OUTPUT_FIELDS.find((candidate) => path.endsWith(candidate.suffix));
}

export function mergePromptScriptHookOutput(
  path: string,
  existingContent: string,
  generatedContent: string
): string | undefined {
  if (!isHookOutputPath(path)) return undefined;

  const existing = parseJsonObject(existingContent);
  const generated = parseJsonObject(generatedContent);
  if (!existing || !generated) return undefined;

  const existingHooks = getJsonObject(existing['hooks']);
  const generatedHooks = getJsonObject(generated['hooks']);
  if (existing['hooks'] !== undefined && !existingHooks) return undefined;
  if (!generatedHooks) {
    const generatedFields = Object.keys(generated);
    if (
      !path.replaceAll('\\', '/').endsWith('.claude/settings.json') ||
      generatedFields.length !== 1 ||
      generatedFields[0] !== 'autoMode'
    ) {
      return undefined;
    }
    return JSON.stringify({ ...existing, ...generated }, null, 2) + '\n';
  }

  return (
    JSON.stringify(
      {
        ...existing,
        ...generated,
        hooks: mergeHookEvents(existingHooks ?? {}, generatedHooks),
      },
      null,
      2
    ) + '\n'
  );
}

export interface RemovedOwnedHooks {
  content: string;
  empty: boolean;
}

export function removePromptScriptOwnedCodexHooks(
  path: string,
  content: string
): RemovedOwnedHooks | undefined {
  if (!path.replaceAll('\\', '/').endsWith('.codex/config.toml')) {
    return undefined;
  }

  const lines = content.split('\n');
  const remaining: string[] = [];
  let removed = false;
  for (let index = 0; index < lines.length;) {
    const eventMatch = lines[index]!.match(/^\s*\[\[hooks\.([A-Za-z][A-Za-z0-9_]*)\]\]\s*$/);
    if (!eventMatch) {
      remaining.push(lines[index]!);
      index += 1;
      continue;
    }

    const event = eventMatch[1]!;
    const group: string[] = [];
    while (index < lines.length) {
      const line = lines[index]!;
      if (
        group.length > 0 &&
        /^\s*\[/.test(line) &&
        !new RegExp(`^\\s*\\[\\[hooks\\.${event}\\.hooks\\]\\]\\s*$`).test(line)
      ) {
        break;
      }
      group.push(line);
      index += 1;
    }

    if (isOwnedCodexHookGroup(group, event) || isLegacyOwnedCodexHookGroup(group, event)) {
      removed = true;
    } else {
      remaining.push(...group);
    }
  }

  if (!removed) return undefined;
  const prunedContent = remaining.join('\n');
  return {
    content: prunedContent,
    empty: prunedContent.trim().length === 0,
  };
}

export function mergePromptScriptCodexConfig(
  existingContent: string,
  generatedContent: string
): string | undefined {
  const managedRootKeys = new Set(['max_threads', 'max_depth', 'agents_file']);
  const isManagedRootAssignment = (line: string): boolean => {
    const trimmed = line.trimStart();
    const separatorIndex = trimmed.indexOf('=');
    if (separatorIndex <= 0) return false;

    let key = trimmed.slice(0, separatorIndex).trim();
    if (
      key.length >= 2 &&
      ((key.startsWith('"') && key.endsWith('"')) || (key.startsWith("'") && key.endsWith("'")))
    ) {
      key = key.slice(1, -1);
    }
    return managedRootKeys.has(key);
  };
  const isValidGeneratedAssignment = (line: string): boolean => {
    const trimmed = line.trim();
    const separatorIndex = trimmed.indexOf('=');
    if (separatorIndex <= 0 || separatorIndex === trimmed.length - 1) {
      return false;
    }
    return (
      managedRootKeys.has(trimmed.slice(0, separatorIndex).trim()) &&
      trimmed.slice(separatorIndex + 1).trim().length > 0
    );
  };
  const generatedLines = generatedContent.split('\n').filter((line) => line.trim().length > 0);
  if (
    generatedLines.length === 0 ||
    generatedLines.some((line) => !isValidGeneratedAssignment(line))
  ) {
    return undefined;
  }

  let insideTable = false;
  const preserved = existingContent.split('\n').filter((line) => {
    if (/^\s*\[/.test(line)) insideTable = true;
    return insideTable || !isManagedRootAssignment(line);
  });
  const preservedContent = preserved.join('\n').trim();
  return `${generatedLines.join('\n')}${preservedContent ? `\n\n${preservedContent}` : ''}\n`;
}

export function removePromptScriptOwnedHooks(
  path: string,
  content: string
): RemovedOwnedHooks | undefined {
  const contract = getHookOutputContract(path.replaceAll('\\', '/'));
  if (!contract) return undefined;

  const parsed = parseJsonObject(content);
  const hooks = parsed ? getJsonObject(parsed['hooks']) : undefined;
  if (!parsed || !hooks) return undefined;

  let removed = false;
  const remainingHooks: Record<string, unknown> = {};
  for (const [event, entries] of Object.entries(hooks)) {
    if (!Array.isArray(entries)) {
      remainingHooks[event] = entries;
      continue;
    }
    const pruned = pruneOwnedHookEntries(entries);
    if (pruned.removed) removed = true;
    const remaining = pruned.entries;
    if (remaining.length > 0) remainingHooks[event] = remaining;
  }
  if (!removed) return undefined;

  const remainingTopLevel = Object.keys(parsed).filter(
    (field) => field !== 'hooks' && !isDisposableHookMetadata(contract.suffix, field)
  );
  const empty = Object.keys(remainingHooks).length === 0 && remainingTopLevel.length === 0;
  return {
    content: JSON.stringify({ ...parsed, hooks: remainingHooks }, null, 2) + '\n',
    empty,
  };
}

function mergeHookEvents(
  existing: Record<string, unknown>,
  generated: Record<string, unknown>
): Record<string, unknown> {
  const merged: Record<string, unknown> = {};
  for (const [event, entries] of Object.entries(existing)) {
    if (!Array.isArray(entries)) {
      merged[event] = entries;
      continue;
    }
    const unowned = pruneOwnedHookEntries(entries).entries;
    if (unowned.length > 0) merged[event] = unowned;
  }
  for (const [event, entries] of Object.entries(generated)) {
    if (!Array.isArray(entries)) {
      merged[event] = entries;
      continue;
    }
    const previous = Array.isArray(merged[event]) ? merged[event] : [];
    merged[event] = [...previous, ...entries];
  }
  return merged;
}

function isOwnedHookEntry(value: unknown): boolean {
  const scan = scanHookOwnership(value);
  return scan.found && scan.valid;
}

interface PrunedHookEntries {
  entries: unknown[];
  removed: boolean;
}

function pruneOwnedHookEntries(entries: unknown[]): PrunedHookEntries {
  const remaining: unknown[] = [];
  let removed = false;

  for (const entry of entries) {
    const object = getJsonObject(entry);
    const handlers = object?.['hooks'];
    if (Array.isArray(handlers)) {
      const prunedHandlers = pruneOwnedHookEntries(handlers);
      if (prunedHandlers.removed) {
        removed = true;
        if (prunedHandlers.entries.length > 0) {
          remaining.push({ ...object, hooks: prunedHandlers.entries });
        }
        continue;
      }
    }

    if (isOwnedHookEntry(entry)) {
      removed = true;
    } else {
      remaining.push(entry);
    }
  }

  return { entries: remaining, removed };
}

function parseJsonObject(content: string): Record<string, unknown> | undefined {
  try {
    const parsed: unknown = JSON.parse(content);
    return getJsonObject(parsed);
  } catch {
    return undefined;
  }
}

function getJsonObject(value: unknown): Record<string, unknown> | undefined {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : undefined;
}

function isDisposableHookMetadata(suffix: string, field: string): boolean {
  return (
    field === 'version' &&
    (suffix === '.github/hooks/promptscript.json' || suffix === '.cursor/hooks.json')
  );
}

function isOwnedCodexHookGroup(lines: string[], event: string): boolean {
  let commandCount = 0;
  for (const line of lines) {
    const trimmed = line.trim();
    if (
      trimmed.length === 0 ||
      trimmed === `[[hooks.${event}]]` ||
      trimmed === `[[hooks.${event}.hooks]]` ||
      isTomlStringAssignment(trimmed, 'matcher') ||
      isTomlStringAssignment(trimmed, 'statusMessage') ||
      /^timeout\s*=\s*\d+\s*$/.test(trimmed) ||
      /^type\s*=\s*"command"\s*$/.test(trimmed)
    ) {
      continue;
    }

    const command = trimmed.match(/^(?:command|command_windows)\s*=\s*"(.*)"\s*$/);
    // Ownership contract: hook-adapters.ts (HOOK_OWNERSHIP_MARKER) appends the
    // marker as the final token of every emitted command; keep both in sync.
    if (!command || !/# promptscript-generated:[A-Za-z0-9._-]+$/.test(command[1]!)) {
      return false;
    }
    commandCount += 1;
  }
  return commandCount > 0;
}

/**
 * Codex event names emitted by PromptScript through syntax 1.15.x.
 *
 * Those releases wrote hooks as inline `[[hooks.<snake_case_event>]]` tables in
 * `.codex/config.toml` with no ownership marker. Codex still discovers inline
 * config tables next to `.codex/hooks.json`, so a stale group left behind by an
 * upgrade would run alongside the current output.
 */
const LEGACY_CODEX_EVENTS = new Set([
  'pre_tool_use',
  'post_tool_use',
  'session_start',
  'subagent_start',
  'notification',
  'stop',
]);

const LEGACY_CODEX_METADATA_FIELDS = ['matcher', 'status_message'] as const;

/**
 * Detect an unmarked hook group emitted by PromptScript through syntax 1.15.x.
 *
 * The legacy shape is unambiguous: native Codex hooks use PascalCase events,
 * a nested `[[hooks.<Event>.hooks]]` table, a string `command`, and neither
 * `id` nor the snake_case metadata keys below. A group only counts as owned
 * when it carries an `id`, an array `command`, no nested table, and nothing
 * beyond the fields the legacy emitter produced.
 */
function isLegacyOwnedCodexHookGroup(lines: string[], event: string): boolean {
  if (!LEGACY_CODEX_EVENTS.has(event)) return false;

  let hasId = false;
  let hasArrayCommand = false;
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.length === 0 || trimmed === `[[hooks.${event}]]`) continue;

    // A nested handler table means the group follows the native Codex schema.
    if (trimmed.startsWith('[')) return false;

    if (isTomlStringAssignment(trimmed, 'id')) {
      if (hasId) return false;
      hasId = true;
      continue;
    }
    if (/^command\s*=\s*\[.*\]$/.test(trimmed)) {
      if (hasArrayCommand) return false;
      hasArrayCommand = true;
      continue;
    }
    if (/^timeout_ms\s*=\s*\d+$/.test(trimmed)) continue;
    if (/^continue_on_failure\s*=\s*(?:true|false)$/.test(trimmed)) continue;
    if (LEGACY_CODEX_METADATA_FIELDS.some((field) => isTomlStringAssignment(trimmed, field))) {
      continue;
    }

    return false;
  }

  return hasId && hasArrayCommand;
}

function isTomlStringAssignment(line: string, field: string): boolean {
  if (!line.startsWith(field)) return false;
  let index = field.length;
  while (index < line.length && /\s/.test(line[index]!)) index++;
  if (line[index] !== '=') return false;
  index++;
  while (index < line.length && /\s/.test(line[index]!)) index++;
  if (line[index] !== '"' || line.at(-1) !== '"' || index === line.length - 1) {
    return false;
  }

  for (let valueIndex = index + 1; valueIndex < line.length - 1; valueIndex++) {
    if (line[valueIndex] === '\\') valueIndex++;
    else if (line[valueIndex] === '"') return false;
  }
  return true;
}

function scanHookOwnership(value: unknown): HookOwnershipScan {
  if (Array.isArray(value)) {
    return value.reduce<HookOwnershipScan>(
      (result, item) => {
        const itemScan = scanHookOwnership(item);
        return {
          found: result.found || itemScan.found,
          valid: result.valid && itemScan.valid,
        };
      },
      { found: false, valid: true }
    );
  }

  if (typeof value !== 'object' || value === null) {
    return { found: false, valid: true };
  }

  const object = value as Record<string, unknown>;
  const commands = ['command', 'commandWindows', 'command_windows', 'bash', 'powershell', 'windows']
    .map((field) => object[field])
    .filter((command): command is string => typeof command === 'string');
  if (typeof object['type'] === 'string' || commands.length > 0) {
    if (typeof object['type'] === 'string' && object['type'] !== 'command') {
      return { found: true, valid: false };
    }
    return {
      found: true,
      valid:
        Object.keys(object).every((field) => OWNED_COMMAND_FIELDS.has(field)) &&
        commands.length > 0 &&
        // Ownership contract: the marker must be the final token of the command
        // (see HOOK_OWNERSHIP_MARKER in packages/formatters/src/hook-adapters.ts).
        commands.every((command) => /# promptscript-generated:[A-Za-z0-9._-]+\s*$/.test(command)),
    };
  }

  if (Array.isArray(object['hooks'])) {
    const nested = scanHookOwnership(object['hooks']);
    if (
      nested.found &&
      !Object.keys(object).every((field) => field === 'matcher' || field === 'hooks')
    ) {
      return { found: true, valid: false };
    }
    return nested;
  }

  return scanHookOwnership(Object.values(object));
}

function isWithin(root: string, candidate: string): boolean {
  const relativePath = relative(root, candidate);
  return relativePath === '' || (!relativePath.startsWith('..') && !isAbsolute(relativePath));
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && 'code' in error;
}
