import {
  createOutputPlan,
  type Logger,
  type OutputPlan,
  type OutputPlanCandidate,
  type OutputPlanFile,
} from '@promptscript/core';
import type { CompileResult, FormatterOutput } from '@promptscript/compiler';
import { postFormatWithPrettier } from '../prettier/post-format.js';

const PROMPTSCRIPT_MARKERS = [
  '<!-- PromptScript',
  '# promptscript-generated:',
  '> Auto-generated by PromptScript',
];

/**
 * Apply the configured header before the final output plan is rebuilt.
 */
export function applyConfiguredHeader(
  outputs: Map<string, FormatterOutput>,
  header: string | undefined
): void {
  const normalizedHeader = header?.trim();
  if (!normalizedHeader) return;

  for (const output of outputs.values()) {
    applyHeaderToOutput(output, normalizedHeader);
  }
}

function applyHeaderToOutput(output: FormatterOutput, header: string): void {
  const lines = output.content.split('\n');
  const markerIndex = lines.findIndex((line) =>
    PROMPTSCRIPT_MARKERS.some((marker) => line.includes(marker))
  );
  if (markerIndex !== -1) {
    let insertionIndex = markerIndex + 1;
    if (lines[0] === '---') {
      const frontmatterEnd = lines.indexOf('---', 1);
      if (frontmatterEnd !== -1) {
        insertionIndex = frontmatterEnd + 1;
      }
    }

    lines.splice(insertionIndex, 0, '', header);
    output.content = lines.join('\n');
  }

  for (const child of output.additionalFiles ?? []) {
    applyHeaderToOutput(child, header);
  }
}

function outputFromPlanFile(file: OutputPlanFile): FormatterOutput {
  return {
    path: file.path,
    content: file.content,
    ...(file.mode !== undefined ? { mode: file.mode } : {}),
    ...(file.merge !== undefined ? { merge: file.merge } : {}),
    ...(file.managedOutputDirectories !== undefined
      ? { managedOutputDirectories: file.managedOutputDirectories }
      : {}),
    ...(file.managedOutputFiles !== undefined
      ? { managedOutputFiles: file.managedOutputFiles }
      : {}),
  };
}

function mergeOutputWithPlan(
  output: FormatterOutput | undefined,
  file: OutputPlanFile
): FormatterOutput {
  return {
    path: file.path,
    content: output?.content ?? file.content,
    ...(output?.mode !== undefined
      ? { mode: output.mode }
      : file.mode !== undefined
        ? { mode: file.mode }
        : {}),
    ...(output?.merge !== undefined
      ? { merge: output.merge }
      : file.merge !== undefined
        ? { merge: file.merge }
        : {}),
    ...(output?.managedOutputDirectories !== undefined
      ? { managedOutputDirectories: output.managedOutputDirectories }
      : file.managedOutputDirectories !== undefined
        ? { managedOutputDirectories: file.managedOutputDirectories }
        : {}),
    ...(output?.managedOutputFiles !== undefined
      ? { managedOutputFiles: output.managedOutputFiles }
      : file.managedOutputFiles !== undefined
        ? { managedOutputFiles: file.managedOutputFiles }
        : {}),
  };
}

function flattenOutputMap(outputs: Map<string, FormatterOutput>): Map<string, FormatterOutput> {
  const flattened = new Map<string, FormatterOutput>();

  const visit = (output: FormatterOutput): void => {
    flattened.set(output.path, output);
    for (const child of output.additionalFiles ?? []) {
      visit(child);
    }
  };

  for (const output of outputs.values()) {
    visit(output);
  }
  return flattened;
}

function createFinalCandidates(
  outputs: Map<string, FormatterOutput>,
  previousPlan: OutputPlan | undefined,
  additionalOutputPaths: readonly string[]
): OutputPlanCandidate[] {
  const previousFiles = new Map(previousPlan?.files.map((file) => [file.path, file]));
  const finalOutputs = new Map<string, FormatterOutput>();

  if (previousPlan) {
    for (const file of previousPlan.files) {
      finalOutputs.set(file.path, mergeOutputWithPlan(outputs.get(file.path), file));
    }
  } else {
    for (const output of outputs.values()) {
      finalOutputs.set(output.path, output);
    }
  }

  for (const path of additionalOutputPaths) {
    const output = outputs.get(path);
    if (output) finalOutputs.set(path, output);
  }

  return [...finalOutputs.values()].map((output) => {
    const previous = previousFiles.get(output.path);
    return {
      output,
      owner: previous?.owner ?? 'cli',
      role: previous?.role ?? 'primary',
    };
  });
}

/**
 * Apply CLI output transformations and rebuild the only plan consumed by
 * writes, dry-runs, and diffs.
 */
export async function finalizeOutputPlan(
  result: Pick<CompileResult, 'outputs' | 'outputPlan'>,
  options: {
    header?: string;
    projectRoot: string;
    logger: Logger;
    additionalOutputPaths?: readonly string[];
  }
): Promise<{ outputs: Map<string, FormatterOutput>; outputPlan: OutputPlan }> {
  applyConfiguredHeader(result.outputs, options.header);
  await postFormatWithPrettier(result.outputs, options.projectRoot, options.logger);

  const flattenedOutputs = flattenOutputMap(result.outputs);
  const outputPlan = createOutputPlan(
    createFinalCandidates(flattenedOutputs, result.outputPlan, options.additionalOutputPaths ?? [])
  );
  const priorCollisions = result.outputPlan?.collisions ?? [];
  const finalOutputs = new Map<string, FormatterOutput>();
  for (const file of outputPlan.files) {
    finalOutputs.set(file.path, outputFromPlanFile(file));
  }

  return {
    outputs: finalOutputs,
    outputPlan: {
      ...outputPlan,
      collisions: [...priorCollisions, ...outputPlan.collisions],
    },
  };
}
