#!/usr/bin/env bash
# Syncs root SKILL.md to the copies that feed the compiler.
#
# Target skill directories such as .claude/skills/ are compiler output: they are
# written by `prs compile` through includePromptScriptSkill and carry a
# generation marker. Copying an unmarked file over them makes compilation refuse
# to overwrite its own output.
#
# This also regenerates the embedded skill module
# (packages/cli/src/generated/promptscript-skill.ts) so the CLI works without
# filesystem skill discovery, including under `deno compile` binaries.
#
# Usage:
#   ./scripts/sync-skill.sh          # copy root -> destinations
#   ./scripts/sync-skill.sh --check  # verify all copies match (CI mode)

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SOURCE="$ROOT/skills/promptscript/SKILL.md"

DESTINATIONS=(
  "$ROOT/packages/cli/skills/promptscript/SKILL.md"
  "$ROOT/.promptscript/skills/promptscript/SKILL.md"
)

GENERATED_DIR="$ROOT/packages/cli/src/generated"
GENERATED_FILE="$GENERATED_DIR/promptscript-skill.ts"

if [ ! -f "$SOURCE" ]; then
  echo "ERROR: $SOURCE not found" >&2
  exit 1
fi

# Writes the embedded skill module generated from SKILL.md to the given path.
# The output is normalized with Prettier so regeneration is byte-stable.
generate_embedded_skill() {
  node -e '
    const fs = require("node:fs");
    const source = fs.readFileSync(process.argv[1], "utf8");
    const output = [
      "/**",
      " * Generated by scripts/sync-skill.sh - do not edit.",
      " * Embedded PromptScript skill content, so the CLI works without",
      " * filesystem skill discovery (including deno compile binaries).",
      " */",
      "export const PROMPTSCRIPT_SKILL_CONTENT =",
      `  ${JSON.stringify(source)};`,
      "",
    ].join("\n");
    fs.writeFileSync(process.argv[2], output);
  ' "$SOURCE" "$1"
  "$ROOT/node_modules/.bin/prettier" --write "$1" > /dev/null
}

if [ "${1:-}" = "--check" ]; then
  failed=0
  source_hash=$(shasum -a 256 "$SOURCE" | cut -d' ' -f1)
  for dest in "${DESTINATIONS[@]}"; do
    if [ ! -f "$dest" ]; then
      echo "MISSING: $dest" >&2
      failed=1
      continue
    fi
    dest_hash=$(shasum -a 256 "$dest" | cut -d' ' -f1)
    if [ "$source_hash" != "$dest_hash" ]; then
      echo "OUT OF SYNC: $dest" >&2
      failed=1
    fi
  done
  expected_dir="$(mktemp -d)"
  generate_embedded_skill "$expected_dir/promptscript-skill.ts"
  if [ ! -f "$GENERATED_FILE" ] || ! cmp -s "$expected_dir/promptscript-skill.ts" "$GENERATED_FILE"; then
    echo "OUT OF SYNC: $GENERATED_FILE" >&2
    failed=1
  fi
  rm -rf "$expected_dir"
  if [ "$failed" -ne 0 ]; then
    echo "Run './scripts/sync-skill.sh' to fix." >&2
    exit 1
  fi
  echo "All SKILL.md copies in sync."
  exit 0
fi

for dest in "${DESTINATIONS[@]}"; do
  mkdir -p "$(dirname "$dest")"
  cp "$SOURCE" "$dest"
  echo "Synced: $dest"
done

mkdir -p "$GENERATED_DIR"
generate_embedded_skill "$GENERATED_FILE"
echo "Synced: $GENERATED_FILE"
