import { afterEach, describe, expect, it } from 'vitest';
import { lstat, mkdtemp, mkdir, readFile, rm, symlink, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import type { FormatterOutput } from '@promptscript/compiler';
import { cleanupManagedOutputs, removeIfUnchanged } from '../managed-output-cleanup.js';

const GENERATED_MARKER =
  '<!-- PromptScript 2026-07-15T00:00:00.000Z | source: project.prs | target: factory - do not edit -->';

describe('cleanupManagedOutputs', () => {
  const temporaryDirectories: string[] = [];

  afterEach(async () => {
    await Promise.all(
      temporaryDirectories
        .splice(0)
        .map((directory) => rm(directory, { recursive: true, force: true }))
    );
  });

  it('should prune only obsolete marked files for monolith output', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-project-');
    const rules = join(project, '.factory', 'rules');
    await mkdir(join(rules, 'standards'), { recursive: true });
    await writeFile(join(rules, 'old.md'), `${GENERATED_MARKER}\n\n# Old\n`);
    await writeFile(
      join(rules, '--require=untrusted-package.md'),
      `${GENERATED_MARKER}\n\n# Old\n`
    );
    await writeFile(
      join(rules, 'standards', 'old.md'),
      `---\n# promptscript-generated: 2026-07-15T00:00:00.000Z | source: project.prs | target: factory\n---\n\n# Old\n`
    );
    await writeFile(join(rules, 'team.md'), '# Team-owned rules\n');

    const result = await cleanupManagedOutputs(createMonolithOutputs(), {
      outputRoot: project,
    });

    expect(result.removed).toEqual([
      join(rules, '--require=untrusted-package.md'),
      join(rules, 'old.md'),
      join(rules, 'standards', 'old.md'),
    ]);
    await expect(readFile(join(rules, 'old.md'), 'utf-8')).rejects.toMatchObject({
      code: 'ENOENT',
    });
    await expect(readFile(join(rules, 'team.md'), 'utf-8')).resolves.toBe('# Team-owned rules\n');
  });

  it('should preserve current generated files in split output', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-current-');
    const rules = join(project, '.factory', 'rules');
    await mkdir(rules, { recursive: true });
    await writeFile(join(rules, 'current.md'), `${GENERATED_MARKER}\n\n# Current\n`);
    await writeFile(join(rules, 'stale.md'), `${GENERATED_MARKER}\n\n# Stale\n`);
    const outputs = createMonolithOutputs();
    outputs.set('.factory/rules/current.md', {
      path: '.factory/rules/current.md',
      content: '# Current\n',
    });

    const result = await cleanupManagedOutputs(outputs, { outputRoot: project });

    expect(result.removed).toEqual([join(rules, 'stale.md')]);
    await expect(readFile(join(rules, 'current.md'), 'utf-8')).resolves.toContain('# Current');
  });

  it('should preserve user files that only mention generated markers', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-marker-example-');
    const rules = join(project, '.factory', 'rules');
    const examples = [
      `Marker example: ${GENERATED_MARKER}\n`,
      'Use `# promptscript-generated: <timestamp>` in generated frontmatter.\n',
      'The legacy marker is `> Auto-generated by PromptScript`.\n',
    ];
    await mkdir(rules, { recursive: true });
    await Promise.all(
      examples.map((content, index) => writeFile(join(rules, `example-${index}.md`), content))
    );

    const result = await cleanupManagedOutputs(createMonolithOutputs(), {
      outputRoot: project,
    });

    expect(result.removed).toEqual([]);
    await expect(readFile(join(rules, 'example-0.md'), 'utf-8')).resolves.toBe(examples[0]);
    await expect(readFile(join(rules, 'example-1.md'), 'utf-8')).resolves.toBe(examples[1]);
    await expect(readFile(join(rules, 'example-2.md'), 'utf-8')).resolves.toBe(examples[2]);
  });

  it('should report dry-run removals without changing files', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-dry-run-');
    const staleFile = join(project, '.factory', 'rules', 'stale.md');
    await mkdir(join(project, '.factory', 'rules'), { recursive: true });
    await writeFile(staleFile, `${GENERATED_MARKER}\n\n# Stale\n`);

    const result = await cleanupManagedOutputs(createMonolithOutputs(), {
      outputRoot: project,
      dryRun: true,
    });

    expect(result.removed).toEqual([staleFile]);
    await expect(readFile(staleFile, 'utf-8')).resolves.toContain('# Stale');
  });

  it('should support a project-root managed directory without deleting desired output', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-root-');
    const staleFile = join(project, 'stale.md');
    const desiredFile = join(project, 'AGENTS.md');
    await writeFile(staleFile, `${GENERATED_MARKER}\n\n# Stale\n`);
    await writeFile(desiredFile, `${GENERATED_MARKER}\n\n# Current\n`);
    const outputs = new Map<string, FormatterOutput>([
      [
        'AGENTS.md',
        {
          path: 'AGENTS.md',
          content: '# Current\n',
          managedOutputDirectories: ['.'],
        },
      ],
    ]);

    const result = await cleanupManagedOutputs(outputs, { outputRoot: project });

    expect(result.removed).toEqual([staleFile]);
    await expect(readFile(desiredFile, 'utf-8')).resolves.toContain('# Current');
  });

  it('should recognize marked headings and BOMs without following file symlinks', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-marker-layout-');
    const outside = await createTemporaryDirectory('promptscript-cleanup-file-link-');
    const rules = join(project, '.factory', 'rules');
    const outsideFile = join(outside, 'outside.md');
    const headingFile = join(rules, 'heading.md');
    const bomFile = join(rules, 'bom.md');
    await mkdir(rules, { recursive: true });
    await writeFile(outsideFile, `${GENERATED_MARKER}\n\n# Outside\n`);
    await writeFile(headingFile, `# Security\n\n${GENERATED_MARKER}\n`);
    await writeFile(bomFile, `\uFEFF${GENERATED_MARKER}\n\n# BOM\n`);
    await symlink(outsideFile, join(rules, 'linked.md'), 'file');

    const result = await cleanupManagedOutputs(createMonolithOutputs(), {
      outputRoot: project,
    });

    expect(result.removed).toEqual([bomFile, headingFile]);
    await expect(readFile(outsideFile, 'utf-8')).resolves.toContain('# Outside');
  });

  it('should ignore missing managed directories', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-missing-');

    await expect(
      cleanupManagedOutputs(createMonolithOutputs(), { outputRoot: project })
    ).resolves.toEqual({ removed: [] });
  });

  it('should never follow managed directory or nested symlinks', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-symlink-project-');
    const outside = await createTemporaryDirectory('promptscript-cleanup-symlink-outside-');
    const outsideFile = join(outside, 'outside.md');
    await writeFile(outsideFile, `${GENERATED_MARKER}\n\n# Outside\n`);

    const rules = join(project, '.factory', 'rules');
    await mkdir(join(project, '.factory'), { recursive: true });
    await symlink(outside, rules, 'dir');

    const rootSymlinkResult = await cleanupManagedOutputs(createMonolithOutputs(), {
      outputRoot: project,
    });
    expect(rootSymlinkResult.removed).toEqual([]);
    await expect(readFile(outsideFile, 'utf-8')).resolves.toContain('# Outside');

    await rm(rules);
    await mkdir(rules);
    await symlink(outside, join(rules, 'linked'), 'dir');

    const nestedSymlinkResult = await cleanupManagedOutputs(createMonolithOutputs(), {
      outputRoot: project,
    });
    expect(nestedSymlinkResult.removed).toEqual([]);
    await expect(readFile(outsideFile, 'utf-8')).resolves.toContain('# Outside');
  });

  it('should ignore unsafe managed directory declarations', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-unsafe-project-');
    const outside = await createTemporaryDirectory('promptscript-cleanup-unsafe-outside-');
    const outsideFile = join(outside, 'outside.md');
    await writeFile(outsideFile, `${GENERATED_MARKER}\n\n# Outside\n`);
    const outputs = new Map<string, FormatterOutput>([
      [
        'AGENTS.md',
        {
          path: 'AGENTS.md',
          content: '# AGENTS.md\n',
          managedOutputDirectories: [
            '',
            '..\\promptscript-cleanup-unsafe-outside-',
            '../promptscript-cleanup-unsafe-outside-',
            outside,
          ],
        },
      ],
      [
        outsideFile,
        {
          path: outsideFile,
          content: '# Outside\n',
        },
      ],
    ]);

    const result = await cleanupManagedOutputs(outputs, { outputRoot: project });

    expect(result.removed).toEqual([]);
    await expect(readFile(outsideFile, 'utf-8')).resolves.toContain('# Outside');
  });

  it('should remove obsolete files via in-process fallback when child eval is unavailable', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-fallback-');
    const rules = join(project, '.factory', 'rules');
    await mkdir(rules, { recursive: true });
    const staleFile = join(rules, 'stale.md');
    const keptFile = join(rules, 'team.md');
    await writeFile(staleFile, `${GENERATED_MARKER}\n\n# Stale\n`);
    await writeFile(keptFile, '# Team-owned rules\n');

    const originalExecPath = process.execPath;
    process.execPath = join(project, 'nonexistent-node-binary');
    try {
      const result = await cleanupManagedOutputs(createMonolithOutputs(), {
        outputRoot: project,
      });
      expect(result.removed).toEqual([staleFile]);
    } finally {
      process.execPath = originalExecPath;
    }

    await expect(readFile(staleFile, 'utf-8')).rejects.toMatchObject({ code: 'ENOENT' });
    await expect(readFile(keptFile, 'utf-8')).resolves.toBe('# Team-owned rules\n');
  });

  describe('removeIfUnchanged fallback', () => {
    it('should remove a regular file whose identity is unchanged', async () => {
      const directory = await createTemporaryDirectory('promptscript-remove-ok-');
      const file = join(directory, 'generated.md');
      await writeFile(file, `${GENERATED_MARKER}\n`);
      const stat = await lstat(file);

      await expect(removeIfUnchanged(file, { dev: stat.dev, ino: stat.ino })).resolves.toBe(true);
      await expect(readFile(file, 'utf-8')).rejects.toMatchObject({ code: 'ENOENT' });
    });

    it('should keep a file whose identity no longer matches', async () => {
      const directory = await createTemporaryDirectory('promptscript-remove-mismatch-');
      const file = join(directory, 'generated.md');
      await writeFile(file, `${GENERATED_MARKER}\n`);

      await expect(removeIfUnchanged(file, { dev: 0, ino: 0 })).resolves.toBe(false);
      await expect(readFile(file, 'utf-8')).resolves.toContain('PromptScript');
    });

    it('should ignore a missing entry', async () => {
      const directory = await createTemporaryDirectory('promptscript-remove-missing-');

      await expect(
        removeIfUnchanged(join(directory, 'absent.md'), { dev: 1, ino: 1 })
      ).resolves.toBe(false);
    });

    it('should ignore directories and symlinks', async () => {
      const directory = await createTemporaryDirectory('promptscript-remove-nonfile-');
      const nested = join(directory, 'nested');
      await mkdir(nested);
      const directoryStat = await lstat(nested);
      await expect(
        removeIfUnchanged(nested, { dev: directoryStat.dev, ino: directoryStat.ino })
      ).resolves.toBe(false);

      const target = join(directory, 'target.md');
      await writeFile(target, `${GENERATED_MARKER}\n`);
      const link = join(directory, 'link.md');
      await symlink(target, link, 'file');
      const linkStat = await lstat(link);
      await expect(removeIfUnchanged(link, { dev: linkStat.dev, ino: linkStat.ino })).resolves.toBe(
        false
      );
      await expect(readFile(target, 'utf-8')).resolves.toContain('PromptScript');
    });
  });

  async function createTemporaryDirectory(prefix: string): Promise<string> {
    const directory = await mkdtemp(join(tmpdir(), prefix));
    temporaryDirectories.push(directory);
    return directory;
  }
});

function createMonolithOutputs(): Map<string, FormatterOutput> {
  return new Map([
    [
      'AGENTS.md',
      {
        path: 'AGENTS.md',
        content: '# AGENTS.md\n',
        managedOutputDirectories: ['.factory/rules'],
      },
    ],
  ]);
}
