import { afterEach, describe, expect, it } from 'vitest';
import { lstat, mkdtemp, mkdir, readFile, rm, symlink, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { tmpdir } from 'node:os';
import type { FormatterOutput } from '@promptscript/compiler';
import {
  cleanupManagedOutputs,
  createHookOutputSafely,
  hasOnlyOwnedHookCommands,
  isHookOutputPath,
  isPromptScriptOwnedHookOutput,
  mergePromptScriptCodexConfig,
  mergePromptScriptHookOutput,
  removePromptScriptOwnedCodexHooks,
  removePromptScriptOwnedHooks,
  removeHookOutputIfUnchanged,
  removeIfUnchanged,
  rewriteHookOutputIfUnchanged,
} from '../managed-output-cleanup.js';

const GENERATED_MARKER =
  '<!-- PromptScript 2026-07-15T00:00:00.000Z | source: project.prs | target: factory - do not edit -->';

describe('cleanupManagedOutputs', () => {
  const temporaryDirectories: string[] = [];

  afterEach(async () => {
    await Promise.all(
      temporaryDirectories
        .splice(0)
        .map((directory) => rm(directory, { recursive: true, force: true }))
    );
  });

  it('should prune only obsolete marked files for monolith output', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-project-');
    const rules = join(project, '.factory', 'rules');
    await mkdir(join(rules, 'standards'), { recursive: true });
    await writeFile(join(rules, 'old.md'), `${GENERATED_MARKER}\n\n# Old\n`);
    await writeFile(
      join(rules, '--require=untrusted-package.md'),
      `${GENERATED_MARKER}\n\n# Old\n`
    );
    await writeFile(
      join(rules, 'standards', 'old.md'),
      `---\n# promptscript-generated: 2026-07-15T00:00:00.000Z | source: project.prs | target: factory\n---\n\n# Old\n`
    );
    await writeFile(join(rules, 'team.md'), '# Team-owned rules\n');

    const result = await cleanupManagedOutputs(createMonolithOutputs(), {
      outputRoot: project,
    });

    expect(result.removed).toEqual([
      join(rules, '--require=untrusted-package.md'),
      join(rules, 'old.md'),
      join(rules, 'standards', 'old.md'),
    ]);
    await expect(readFile(join(rules, 'old.md'), 'utf-8')).rejects.toMatchObject({
      code: 'ENOENT',
    });
    await expect(readFile(join(rules, 'team.md'), 'utf-8')).resolves.toBe('# Team-owned rules\n');
  });

  it('should preserve current generated files in split output', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-current-');
    const rules = join(project, '.factory', 'rules');
    await mkdir(rules, { recursive: true });
    await writeFile(join(rules, 'current.md'), `${GENERATED_MARKER}\n\n# Current\n`);
    await writeFile(join(rules, 'stale.md'), `${GENERATED_MARKER}\n\n# Stale\n`);
    const outputs = createMonolithOutputs();
    outputs.set('.factory/rules/current.md', {
      path: '.factory/rules/current.md',
      content: '# Current\n',
    });

    const result = await cleanupManagedOutputs(outputs, { outputRoot: project });

    expect(result.removed).toEqual([join(rules, 'stale.md')]);
    await expect(readFile(join(rules, 'current.md'), 'utf-8')).resolves.toContain('# Current');
  });

  it('should preserve user files that only mention generated markers', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-marker-example-');
    const rules = join(project, '.factory', 'rules');
    const examples = [
      `Marker example: ${GENERATED_MARKER}\n`,
      'Use `# promptscript-generated: <timestamp>` in generated frontmatter.\n',
      'The legacy marker is `> Auto-generated by PromptScript`.\n',
    ];
    await mkdir(rules, { recursive: true });
    await Promise.all(
      examples.map((content, index) => writeFile(join(rules, `example-${index}.md`), content))
    );

    const result = await cleanupManagedOutputs(createMonolithOutputs(), {
      outputRoot: project,
    });

    expect(result.removed).toEqual([]);
    await expect(readFile(join(rules, 'example-0.md'), 'utf-8')).resolves.toBe(examples[0]);
    await expect(readFile(join(rules, 'example-1.md'), 'utf-8')).resolves.toBe(examples[1]);
    await expect(readFile(join(rules, 'example-2.md'), 'utf-8')).resolves.toBe(examples[2]);
  });

  it('should report dry-run removals without changing files', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-dry-run-');
    const staleFile = join(project, '.factory', 'rules', 'stale.md');
    await mkdir(join(project, '.factory', 'rules'), { recursive: true });
    await writeFile(staleFile, `${GENERATED_MARKER}\n\n# Stale\n`);

    const result = await cleanupManagedOutputs(createMonolithOutputs(), {
      outputRoot: project,
      dryRun: true,
    });

    expect(result.removed).toEqual([staleFile]);
    await expect(readFile(staleFile, 'utf-8')).resolves.toContain('# Stale');
  });

  it('should remove obsolete files with the legacy generated marker', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-legacy-marker-');
    const staleFile = join(project, '.factory', 'rules', 'stale.md');
    await mkdir(join(project, '.factory', 'rules'), { recursive: true });
    await writeFile(staleFile, '> Auto-generated by PromptScript - do not edit\n\n# Stale\n');

    const result = await cleanupManagedOutputs(createMonolithOutputs(), {
      outputRoot: project,
    });

    expect(result.removed).toEqual([staleFile]);
  });

  it('should remove only obsolete owned managed JSON files', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-json-');
    const factoryDirectory = join(project, '.factory');
    const generatedFile = join(factoryDirectory, 'hooks.json');
    const userFile = join(project, '.github', 'hooks', 'promptscript.json');
    await mkdir(factoryDirectory, { recursive: true });
    await mkdir(join(project, '.github', 'hooks'), { recursive: true });
    await writeFile(
      generatedFile,
      '{"hooks":{"PreToolUse":[{"hooks":[{"type":"command","command":"echo ok # promptscript-generated:test"}]}]}}\n'
    );
    await writeFile(userFile, '{"version":1,"hooks":{}}\n');
    const outputs = new Map<string, FormatterOutput>([
      [
        'AGENTS.md',
        {
          path: 'AGENTS.md',
          content: '# Current\n',
          managedOutputFiles: ['.factory/hooks.json', '.github/hooks/promptscript.json'],
        },
      ],
    ]);

    const result = await cleanupManagedOutputs(outputs, { outputRoot: project });

    expect(result.removed).toEqual([generatedFile]);
    await expect(readFile(generatedFile, 'utf-8')).rejects.toMatchObject({ code: 'ENOENT' });
    await expect(readFile(userFile, 'utf-8')).resolves.toContain('"version":1');
  });

  it('should preserve desired managed JSON files', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-json-current-');
    const generatedFile = join(project, '.factory', 'hooks.json');
    await mkdir(dirname(generatedFile), { recursive: true });
    const content =
      '{"hooks":{"PreToolUse":[{"hooks":[{"type":"command","command":"echo ok # promptscript-generated:test"}]}]}}\n';
    await writeFile(generatedFile, content);
    const outputs = new Map<string, FormatterOutput>([
      [
        'AGENTS.md',
        {
          path: 'AGENTS.md',
          content: '# Current\n',
          managedOutputFiles: ['.factory/hooks.json'],
        },
      ],
      ['.factory/hooks.json', { path: '.factory/hooks.json', content }],
    ]);

    await expect(cleanupManagedOutputs(outputs, { outputRoot: project })).resolves.toEqual({
      removed: [],
      removedDirectories: [],
    });
    await expect(readFile(generatedFile, 'utf-8')).resolves.toBe(content);
  });

  it('should preserve managed JSON with marker-like or mixed user commands', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-json-user-');
    const file = join(project, '.github', 'hooks', 'promptscript.json');
    await mkdir(dirname(file), { recursive: true });
    const content = JSON.stringify({
      version: 1,
      hooks: {
        preToolUse: [
          {
            type: 'command',
            command: 'echo "# promptscript-generated:example" then continue',
          },
          {
            type: 'command',
            command: 'echo generated # promptscript-generated:owned',
          },
        ],
      },
    });
    await writeFile(file, content);
    const outputs = new Map<string, FormatterOutput>([
      [
        'AGENTS.md',
        {
          path: 'AGENTS.md',
          content: '# Current\n',
          managedOutputFiles: ['.github/hooks/promptscript.json'],
        },
      ],
    ]);

    await expect(cleanupManagedOutputs(outputs, { outputRoot: project })).resolves.toEqual({
      removed: [],
      removedDirectories: [],
    });
    await expect(readFile(file, 'utf-8').then((value) => JSON.parse(value))).resolves.toEqual({
      version: 1,
      hooks: {
        preToolUse: [
          {
            type: 'command',
            command: 'echo "# promptscript-generated:example" then continue',
          },
        ],
      },
    });
  });

  it('should reject malformed or non-command hook ownership structures', () => {
    expect(hasOnlyOwnedHookCommands('{')).toBe(false);
    expect(hasOnlyOwnedHookCommands('[]')).toBe(false);
    expect(hasOnlyOwnedHookCommands('{"hooks":"invalid"}')).toBe(false);
    expect(hasOnlyOwnedHookCommands('{"hooks":{"event":[{"type":"prompt"}]}}')).toBe(false);
    expect(hasOnlyOwnedHookCommands('{"hooks":{"event":[{"type":"command"}]}}')).toBe(false);
  });

  it('should recognize owned direct-command hook contracts', () => {
    const content =
      '{"version":1,"hooks":{"postToolUse":[{"command":"echo ok # promptscript-generated:test"}]}}';

    expect(isPromptScriptOwnedHookOutput('.cursor/hooks.json', content)).toBe(true);
    expect(
      isPromptScriptOwnedHookOutput(
        '.claude/settings.json',
        '{"autoMode":"acceptEdits","hooks":{"PostToolUse":[{"hooks":[{"type":"command","command":"echo ok # promptscript-generated:test"}]}]}}'
      )
    ).toBe(false);
    expect(
      isPromptScriptOwnedHookOutput(
        '.cursor/hooks.json',
        '{"version":1,"hooks":{"postToolUse":[{"command":"echo ok # promptscript-generated:test","commandWindows":"echo user"}]}}'
      )
    ).toBe(false);
    expect(
      isPromptScriptOwnedHookOutput(
        '.github/hooks/promptscript-vscode.json',
        '{"hooks":{"PostToolUse":[{"type":"command","command":"echo ok # promptscript-generated:test","windows":"echo user"}]}}'
      )
    ).toBe(false);
    expect(
      isPromptScriptOwnedHookOutput(
        '.claude/settings.json',
        '{"hooks":{"PostToolUse":[{"matcher":"Edit","hooks":[{"type":"command","command":"echo ok # promptscript-generated:test"}],"userMetadata":true}]}}'
      )
    ).toBe(false);
    expect(isPromptScriptOwnedHookOutput('.windsurf/hooks.json', content)).toBe(false);
    expect(
      isPromptScriptOwnedHookOutput(
        '.cursor/hooks.json',
        '{"version":1,"userSetting":true,"hooks":{"postToolUse":[{"command":"echo ok # promptscript-generated:test"}]}}'
      )
    ).toBe(false);
  });

  it('should merge generated hooks without replacing user settings', () => {
    const existing = JSON.stringify({
      permissions: { allow: ['Read'] },
      hooks: {
        PreToolUse: [
          {
            matcher: 'Bash',
            hooks: [
              {
                type: 'command',
                command: 'echo old # promptscript-generated:old',
              },
              { type: 'command', command: 'echo user' },
            ],
          },
        ],
      },
    });
    const generated = JSON.stringify({
      hooks: {
        PreToolUse: [
          {
            matcher: 'Edit',
            hooks: [
              {
                type: 'command',
                command: 'echo generated # promptscript-generated:check',
              },
            ],
          },
        ],
      },
    });

    const merged = JSON.parse(
      mergePromptScriptHookOutput('.claude/settings.json', existing, generated)!
    ) as {
      permissions: unknown;
      hooks: { PreToolUse: unknown[] };
    };
    expect(merged.permissions).toEqual({ allow: ['Read'] });
    expect(merged.hooks.PreToolUse).toHaveLength(2);
    expect(merged.hooks.PreToolUse[0]).toEqual({
      matcher: 'Bash',
      hooks: [{ type: 'command', command: 'echo user' }],
    });
  });

  it('should merge Claude autoMode without replacing user settings', () => {
    const merged = mergePromptScriptHookOutput(
      '.claude/settings.json',
      '{"permissions":{"allow":["Read"]},"autoMode":"disabled"}',
      '{"autoMode":"acceptEdits"}'
    );

    expect(JSON.parse(merged!)).toEqual({
      permissions: { allow: ['Read'] },
      autoMode: 'acceptEdits',
    });
  });

  it('should reject malformed hook output contracts', () => {
    expect(isHookOutputPath('.github/hooks/promptscript.json')).toBe(true);
    expect(isHookOutputPath('.codex/config.toml')).toBe(true);
    expect(isHookOutputPath('.unknown/hooks.json')).toBe(false);
    expect(isPromptScriptOwnedHookOutput('.github/hooks/promptscript.json', '{')).toBe(false);
    expect(isPromptScriptOwnedHookOutput('.github/hooks/promptscript.json', '[]')).toBe(false);
    expect(
      isPromptScriptOwnedHookOutput(
        '.github/hooks/promptscript.json',
        '{"version":1,"extra":true,"hooks":{"postToolUse":[]}}'
      )
    ).toBe(false);
  });

  it('should reject unsupported hook merges', () => {
    expect(
      mergePromptScriptHookOutput('.github/hooks/promptscript.json', '{}', '{')
    ).toBeUndefined();
    expect(
      mergePromptScriptHookOutput(
        '.github/hooks/promptscript.json',
        '{}',
        '{"autoMode":"acceptEdits"}'
      )
    ).toBeUndefined();
    expect(
      mergePromptScriptHookOutput(
        '.claude/settings.json',
        '{}',
        '{"autoMode":"acceptEdits","other":true}'
      )
    ).toBeUndefined();
  });

  it('should remove owned entries while preserving user hooks and settings', () => {
    const content = JSON.stringify({
      theme: 'dark',
      hooks: {
        AfterTool: [
          {
            hooks: [
              {
                type: 'command',
                command: 'echo generated # promptscript-generated:check',
              },
            ],
          },
          {
            hooks: [{ type: 'command', command: 'echo user' }],
          },
        ],
      },
    });

    const result = removePromptScriptOwnedHooks('.gemini/settings.json', content);

    expect(result?.empty).toBe(false);
    expect(JSON.parse(result!.content)).toEqual({
      theme: 'dark',
      hooks: {
        AfterTool: [
          {
            hooks: [{ type: 'command', command: 'echo user' }],
          },
        ],
      },
    });
  });

  it('should preserve malformed and unowned hook events during merge and removal', () => {
    const existing = JSON.stringify({
      hooks: {
        malformed: 'preserve',
        PreToolUse: [{ type: 'command', command: 'echo user' }],
      },
    });
    const generated = JSON.stringify({
      hooks: {
        malformed: 'replace',
        PostToolUse: [{ type: 'command', command: 'echo generated' }],
      },
    });

    const merged = JSON.parse(
      mergePromptScriptHookOutput('.claude/settings.json', existing, generated)!
    ) as { hooks: Record<string, unknown> };
    expect(merged.hooks['malformed']).toBe('replace');
    expect(merged.hooks['PreToolUse']).toEqual([{ type: 'command', command: 'echo user' }]);
    expect(
      removePromptScriptOwnedHooks(
        '.claude/settings.json',
        JSON.stringify({ hooks: { malformed: 'preserve' } })
      )
    ).toBeUndefined();
  });

  it('should prune legacy owned Codex TOML hook groups', () => {
    const ownedContent = `[[hooks.PreToolUse]]
matcher = "Edit"
[[hooks.PreToolUse.hooks]]
type = "command"
command = "echo owned # promptscript-generated:owned"
command_windows = "& 'echo' 'owned' # promptscript-generated:owned"
`;
    const content = `max_threads = 8

${ownedContent}
[[hooks.Stop]]
[[hooks.Stop.hooks]]
type = "command"
command = "echo user"
`;

    const result = removePromptScriptOwnedCodexHooks('.codex/config.toml', content);

    expect(result?.empty).toBe(false);
    expect(result?.content).toContain('max_threads = 8');
    expect(result?.content).toContain('command = "echo user"');
    expect(result?.content).not.toContain('promptscript-generated:owned');
    expect(removePromptScriptOwnedCodexHooks('.codex/config.toml', ownedContent)?.empty).toBe(true);
  });

  it('should prune unmarked Codex TOML hook groups emitted before 1.16', () => {
    const legacyContent = `[[hooks.post_tool_use]]
id = "fmt"
command = ["pnpm", "format"]
matcher = "Edit"
timeout_ms = 5000
status_message = "Formatting"
continue_on_failure = false
`;
    const content = `max_threads = 8

${legacyContent}
[[hooks.PreToolUse]]
matcher = "^Bash$"

[[hooks.PreToolUse.hooks]]
type = "command"
command = "echo user"
`;

    const result = removePromptScriptOwnedCodexHooks('.codex/config.toml', content);

    expect(result?.empty).toBe(false);
    expect(result?.content).toContain('max_threads = 8');
    expect(result?.content).toContain('command = "echo user"');
    expect(result?.content).not.toContain('post_tool_use');
    expect(result?.content).not.toContain('pnpm');
    expect(removePromptScriptOwnedCodexHooks('.codex/config.toml', legacyContent)?.empty).toBe(
      true
    );
  });

  it('should preserve user Codex TOML groups that only resemble the legacy shape', () => {
    // Native schema: nested handler table, so the flat legacy shape never applies.
    const nestedSnakeCase = `[[hooks.post_tool_use]]
id = "fmt"
[[hooks.post_tool_use.hooks]]
type = "command"
command = "echo user"
`;
    // Unknown event name outside the set the legacy emitter could produce.
    const unknownEvent = `[[hooks.custom_event]]
id = "fmt"
command = ["pnpm", "format"]
`;
    // Legacy events never carried extra keys, so an unknown key means user content.
    const extraField = `[[hooks.post_tool_use]]
id = "fmt"
command = ["pnpm", "format"]
retries = 3
`;
    // An array command without an id is not something the legacy emitter wrote.
    const missingId = `[[hooks.post_tool_use]]
command = ["pnpm", "format"]
`;
    // An id without an array command is likewise outside the legacy shape.
    const missingCommand = `[[hooks.post_tool_use]]
id = "fmt"
matcher = "Edit"
`;

    for (const content of [nestedSnakeCase, unknownEvent, extraField, missingId, missingCommand]) {
      expect(removePromptScriptOwnedCodexHooks('.codex/config.toml', content)).toBeUndefined();
    }
  });

  it('should merge generated Codex settings with user TOML', () => {
    expect(
      mergePromptScriptCodexConfig(
        '"max_threads" = 4\nmodel = "gpt-5"\n\n[features]\nhooks = true\n',
        'max_threads = 8\nmax_depth = 2\n'
      )
    ).toBe('max_threads = 8\nmax_depth = 2\n\nmodel = "gpt-5"\n\n[features]\nhooks = true\n');
    expect(mergePromptScriptCodexConfig('max_threads = 4\n', '')).toBeUndefined();
    expect(mergePromptScriptCodexConfig('max_threads = 4\n', 'model = "gpt-5"\n')).toBeUndefined();
    expect(mergePromptScriptCodexConfig('max_threads = 4\n', 'max_threads =')).toBeUndefined();
  });

  it('should reject Codex groups with malformed string assignments', () => {
    const malformed = `[[hooks.PreToolUse]]
matcher = "unterminated
[[hooks.PreToolUse.hooks]]
type = "command"
command = "echo owned # promptscript-generated:owned"
`;

    expect(removePromptScriptOwnedCodexHooks('.codex/config.toml', malformed)).toBeUndefined();
  });

  it('should accept escaped TOML strings and reject unescaped quotes', () => {
    const escaped = `[[hooks.PreToolUse]]
matcher = "Edit\\"Write"
[[hooks.PreToolUse.hooks]]
type = "command"
command = "echo owned # promptscript-generated:owned"
`;
    expect(removePromptScriptOwnedCodexHooks('.codex/config.toml', escaped)?.empty).toBe(true);

    const unescaped = `[[hooks.PreToolUse]]
matcher = "Edit"Write"
[[hooks.PreToolUse.hooks]]
type = "command"
command = "echo owned # promptscript-generated:owned"
`;
    expect(removePromptScriptOwnedCodexHooks('.codex/config.toml', unescaped)).toBeUndefined();
  });

  it('should reject malformed existing hook JSON and unsupported paths', () => {
    expect(
      mergePromptScriptHookOutput('.claude/settings.json', '{"hooks":[]}', '{}')
    ).toBeUndefined();
    expect(removePromptScriptOwnedHooks('.unknown/hooks.json', '{}')).toBeUndefined();
    expect(
      removePromptScriptOwnedHooks('.claude/settings.json', '{"hooks":"invalid"}')
    ).toBeUndefined();
  });

  it('should atomically rewrite only unchanged regular hook files', async () => {
    const project = await createTemporaryDirectory('promptscript-rewrite-hooks-');
    const file = join(project, '.claude', 'settings.json');
    await mkdir(dirname(file), { recursive: true });
    await writeFile(file, 'old');

    await expect(rewriteHookOutputIfUnchanged(file, project, 'different', 'new')).resolves.toBe(
      false
    );
    await expect(readFile(file, 'utf-8')).resolves.toBe('old');
    await expect(rewriteHookOutputIfUnchanged(file, project, 'old', 'new')).resolves.toBe(true);
    await expect(readFile(file, 'utf-8')).resolves.toBe('new');
  });

  it.skipIf(process.platform === 'win32')(
    'should apply output modes during guarded creates and rewrites',
    async () => {
      const project = await createTemporaryDirectory('promptscript-output-mode-');
      const file = join(project, 'scripts', 'run.sh');

      await expect(createHookOutputSafely(file, project, 'old', 0o755)).resolves.toBe(true);
      expect((await lstat(file)).mode & 0o777).toBe(0o755);

      await expect(rewriteHookOutputIfUnchanged(file, project, 'old', 'new', 0o644)).resolves.toBe(
        true
      );
      expect((await lstat(file)).mode & 0o777).toBe(0o644);
    }
  );

  it('should refuse hook rewrites through a parent symlink', async () => {
    const project = await createTemporaryDirectory('promptscript-rewrite-root-');
    const outside = await createTemporaryDirectory('promptscript-rewrite-outside-');
    const file = join(outside, 'settings.json');
    await writeFile(file, 'old');
    await symlink(outside, join(project, '.claude'));

    await expect(
      rewriteHookOutputIfUnchanged(join(project, '.claude', 'settings.json'), project, 'old', 'new')
    ).resolves.toBe(false);
    await expect(
      removeHookOutputIfUnchanged(join(project, '.claude', 'settings.json'), project, 'old')
    ).resolves.toBe(false);
    await expect(readFile(file, 'utf-8')).resolves.toBe('old');
  });

  it('should atomically create hook files without following parent symlinks', async () => {
    const project = await createTemporaryDirectory('promptscript-create-root-');
    const file = join(project, '.factory', 'hooks.json');

    await expect(createHookOutputSafely(file, project, 'created')).resolves.toBe(true);
    await expect(readFile(file, 'utf-8')).resolves.toBe('created');

    const outside = await createTemporaryDirectory('promptscript-create-outside-');
    await symlink(outside, join(project, '.grok'));
    await expect(
      createHookOutputSafely(
        join(project, '.grok', 'hooks', 'promptscript.json'),
        project,
        'escaped'
      )
    ).resolves.toBe(false);
    await expect(
      readFile(join(outside, 'hooks', 'promptscript.json'), 'utf-8')
    ).rejects.toMatchObject({ code: 'ENOENT' });
  });

  it('should remove a hook output only when its content is unchanged', async () => {
    const project = await createTemporaryDirectory('promptscript-remove-hook-output-');
    const file = join(project, '.factory', 'hooks.json');
    await mkdir(dirname(file), { recursive: true });
    await writeFile(file, 'expected');

    await expect(removeHookOutputIfUnchanged(file, project, 'different')).resolves.toBe(false);
    await expect(readFile(file, 'utf-8')).resolves.toBe('expected');
    await expect(removeHookOutputIfUnchanged(file, project, 'expected')).resolves.toBe(true);
    await expect(readFile(file, 'utf-8')).rejects.toMatchObject({ code: 'ENOENT' });
  });

  it('should return false when guarded child processes cannot start', async () => {
    const project = await createTemporaryDirectory('promptscript-hook-child-');
    const file = join(project, 'settings.json');
    await writeFile(file, 'old');
    const originalExecPath = process.execPath;
    process.execPath = join(project, 'missing-node');
    try {
      await expect(rewriteHookOutputIfUnchanged(file, project, 'old', 'new')).resolves.toBe(false);
      await expect(
        createHookOutputSafely(join(project, 'hooks.json'), project, 'new')
      ).resolves.toBe(false);
      await expect(
        createHookOutputSafely(join(project, 'nested', 'hooks.json'), project, 'new')
      ).resolves.toBe(false);
      await expect(removeHookOutputIfUnchanged(file, project, 'old')).resolves.toBe(false);
    } finally {
      process.execPath = originalExecPath;
    }
  });

  it('should handle closed child stdin for rejected large writes', async () => {
    const project = await createTemporaryDirectory('promptscript-hook-stdin-');
    const file = join(project, 'settings.json');
    const content = 'x'.repeat(4 * 1024 * 1024);
    await writeFile(file, 'old');

    await expect(rewriteHookOutputIfUnchanged(file, project, 'different', content)).resolves.toBe(
      false
    );
    await expect(createHookOutputSafely(file, project, content)).resolves.toBe(false);
    await expect(readFile(file, 'utf-8')).resolves.toBe('old');
  });

  it('should reject hook rewrites and creations outside the output root', async () => {
    const project = await createTemporaryDirectory('promptscript-hook-root-');
    const outside = await createTemporaryDirectory('promptscript-hook-outside-');
    const outsideFile = join(outside, 'hooks.json');
    await writeFile(outsideFile, 'old');

    await expect(rewriteHookOutputIfUnchanged(outsideFile, project, 'old', 'new')).resolves.toBe(
      false
    );
    await expect(removeHookOutputIfUnchanged(outsideFile, project, 'old')).resolves.toBe(false);
    await expect(createHookOutputSafely(join(outside, 'new.json'), project, 'new')).resolves.toBe(
      false
    );
    await expect(readFile(outsideFile, 'utf-8')).resolves.toBe('old');
  });

  it('should remove obsolete owned Windsurf hooks', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-windsurf-hooks-');
    const file = join(project, '.windsurf', 'hooks.json');
    const content =
      '{"hooks":{"post_write_code":[{"command":"echo ok # promptscript-generated:test"}]}}\n';
    await mkdir(dirname(file), { recursive: true });
    await writeFile(file, content);
    const outputs = new Map<string, FormatterOutput>([
      [
        '.windsurf/rules/project.md',
        {
          path: '.windsurf/rules/project.md',
          content: '# Current\n',
          managedOutputFiles: ['.windsurf/hooks.json'],
        },
      ],
    ]);

    await expect(cleanupManagedOutputs(outputs, { outputRoot: project })).resolves.toEqual({
      removed: [file],
      removedDirectories: [],
    });
    await expect(readFile(file, 'utf-8')).rejects.toMatchObject({ code: 'ENOENT' });
  });

  it('should report an obsolete owned JSON file in dry-run mode', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-json-dry-run-');
    const file = join(project, '.factory', 'hooks.json');
    const content =
      '{"hooks":{"PreToolUse":[{"hooks":[{"type":"command","command":"echo ok # promptscript-generated:test"}]}]}}\n';
    await mkdir(dirname(file), { recursive: true });
    await writeFile(file, content);
    const outputs = new Map<string, FormatterOutput>([
      [
        'AGENTS.md',
        {
          path: 'AGENTS.md',
          content: '# Current\n',
          managedOutputFiles: ['.factory/hooks.json'],
        },
      ],
    ]);

    await expect(
      cleanupManagedOutputs(outputs, { outputRoot: project, dryRun: true })
    ).resolves.toEqual({ removed: [file], removedDirectories: [] });
    await expect(readFile(file, 'utf-8')).resolves.toBe(content);
  });

  it('should ignore missing managed files and managed files behind directory symlinks', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-json-symlink-');
    const outside = await createTemporaryDirectory('promptscript-cleanup-json-symlink-outside-');
    const outsideFile = join(outside, 'hooks.json');
    const content =
      '{"hooks":{"PreToolUse":[{"hooks":[{"type":"command","command":"echo ok # promptscript-generated:test"}]}]}}\n';
    await writeFile(outsideFile, content);
    await symlink(outside, join(project, '.factory'), 'dir');
    const outputs = new Map<string, FormatterOutput>([
      [
        'AGENTS.md',
        {
          path: 'AGENTS.md',
          content: '# Current\n',
          managedOutputFiles: ['missing.json', '.factory/hooks.json'],
        },
      ],
    ]);

    await expect(cleanupManagedOutputs(outputs, { outputRoot: project })).resolves.toEqual({
      removed: [],
      removedDirectories: [],
    });
    await expect(readFile(outsideFile, 'utf-8')).resolves.toBe(content);
  });

  it('should support a project-root managed directory without deleting desired output', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-root-');
    const staleFile = join(project, 'stale.md');
    const desiredFile = join(project, 'AGENTS.md');
    await writeFile(staleFile, `${GENERATED_MARKER}\n\n# Stale\n`);
    await writeFile(desiredFile, `${GENERATED_MARKER}\n\n# Current\n`);
    const outputs = new Map<string, FormatterOutput>([
      [
        'AGENTS.md',
        {
          path: 'AGENTS.md',
          content: '# Current\n',
          managedOutputDirectories: ['.'],
        },
      ],
    ]);

    const result = await cleanupManagedOutputs(outputs, { outputRoot: project });

    expect(result.removed).toEqual([staleFile]);
    await expect(readFile(desiredFile, 'utf-8')).resolves.toContain('# Current');
  });

  it('should recognize marked headings and BOMs without following file symlinks', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-marker-layout-');
    const outside = await createTemporaryDirectory('promptscript-cleanup-file-link-');
    const rules = join(project, '.factory', 'rules');
    const outsideFile = join(outside, 'outside.md');
    const headingFile = join(rules, 'heading.md');
    const bomFile = join(rules, 'bom.md');
    await mkdir(rules, { recursive: true });
    await writeFile(outsideFile, `${GENERATED_MARKER}\n\n# Outside\n`);
    await writeFile(headingFile, `# Security\n\n${GENERATED_MARKER}\n`);
    await writeFile(bomFile, `\uFEFF${GENERATED_MARKER}\n\n# BOM\n`);
    await symlink(outsideFile, join(rules, 'linked.md'), 'file');

    const result = await cleanupManagedOutputs(createMonolithOutputs(), {
      outputRoot: project,
    });

    expect(result.removed).toEqual([bomFile, headingFile]);
    await expect(readFile(outsideFile, 'utf-8')).resolves.toContain('# Outside');
  });

  it('should ignore missing managed directories', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-missing-');

    await expect(
      cleanupManagedOutputs(createMonolithOutputs(), { outputRoot: project })
    ).resolves.toEqual({ removed: [], removedDirectories: [] });
  });

  it('should never follow managed directory or nested symlinks', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-symlink-project-');
    const outside = await createTemporaryDirectory('promptscript-cleanup-symlink-outside-');
    const outsideFile = join(outside, 'outside.md');
    await writeFile(outsideFile, `${GENERATED_MARKER}\n\n# Outside\n`);

    const rules = join(project, '.factory', 'rules');
    await mkdir(join(project, '.factory'), { recursive: true });
    await symlink(outside, rules, 'dir');

    const rootSymlinkResult = await cleanupManagedOutputs(createMonolithOutputs(), {
      outputRoot: project,
    });
    expect(rootSymlinkResult.removed).toEqual([]);
    await expect(readFile(outsideFile, 'utf-8')).resolves.toContain('# Outside');

    await rm(rules);
    await mkdir(rules);
    await symlink(outside, join(rules, 'linked'), 'dir');

    const nestedSymlinkResult = await cleanupManagedOutputs(createMonolithOutputs(), {
      outputRoot: project,
    });
    expect(nestedSymlinkResult.removed).toEqual([]);
    await expect(readFile(outsideFile, 'utf-8')).resolves.toContain('# Outside');
  });

  it('should ignore unsafe managed directory and file declarations', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-unsafe-project-');
    const outside = await createTemporaryDirectory('promptscript-cleanup-unsafe-outside-');
    const outsideFile = join(outside, 'outside.md');
    await writeFile(outsideFile, `${GENERATED_MARKER}\n\n# Outside\n`);
    const outputs = new Map<string, FormatterOutput>([
      [
        'AGENTS.md',
        {
          path: 'AGENTS.md',
          content: '# AGENTS.md\n',
          managedOutputDirectories: [
            '',
            '..\\promptscript-cleanup-unsafe-outside-',
            '../promptscript-cleanup-unsafe-outside-',
            outside,
          ],
          managedOutputFiles: [
            '',
            '..\\promptscript-cleanup-unsafe-outside-\\outside.md',
            '../promptscript-cleanup-unsafe-outside-/outside.md',
            outsideFile,
          ],
        },
      ],
      [
        outsideFile,
        {
          path: outsideFile,
          content: '# Outside\n',
        },
      ],
    ]);

    const result = await cleanupManagedOutputs(outputs, { outputRoot: project });

    expect(result.removed).toEqual([]);
    await expect(readFile(outsideFile, 'utf-8')).resolves.toContain('# Outside');
  });

  it('should remove obsolete files via in-process fallback when child eval is unavailable', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-fallback-');
    const rules = join(project, '.factory', 'rules');
    await mkdir(rules, { recursive: true });
    const staleFile = join(rules, 'stale.md');
    const keptFile = join(rules, 'team.md');
    await writeFile(staleFile, `${GENERATED_MARKER}\n\n# Stale\n`);
    await writeFile(keptFile, '# Team-owned rules\n');

    const originalExecPath = process.execPath;
    process.execPath = join(project, 'nonexistent-node-binary');
    try {
      const result = await cleanupManagedOutputs(createMonolithOutputs(), {
        outputRoot: project,
      });
      expect(result.removed).toEqual([staleFile]);
    } finally {
      process.execPath = originalExecPath;
    }

    await expect(readFile(staleFile, 'utf-8')).rejects.toMatchObject({ code: 'ENOENT' });
    await expect(readFile(keptFile, 'utf-8')).resolves.toBe('# Team-owned rules\n');
  });

  it('should prune a managed hooks directory emptied by obsolete file removal', async () => {
    // Arrange
    const project = await createTemporaryDirectory('promptscript-cleanup-prune-hooks-');
    const hooksDirectory = join(project, '.github', 'hooks');
    const obsoleteFile = join(hooksDirectory, 'promptscript.json');
    await mkdir(hooksDirectory, { recursive: true });
    await writeFile(
      obsoleteFile,
      '{"version":1,"hooks":{"preToolUse":[{"type":"command","bash":"echo ok # promptscript-generated:test"}]}}\n'
    );
    const outputs = new Map<string, FormatterOutput>([
      [
        'AGENTS.md',
        {
          path: 'AGENTS.md',
          content: '# Current\n',
          managedOutputDirectories: ['.github/hooks'],
          managedOutputFiles: ['.github/hooks/promptscript.json'],
        },
      ],
    ]);

    // Act
    const result = await cleanupManagedOutputs(outputs, { outputRoot: project });

    // Assert
    expect(result.removed).toEqual([obsoleteFile]);
    expect(result.removedDirectories).toEqual([hooksDirectory]);
    await expect(lstat(hooksDirectory)).rejects.toMatchObject({ code: 'ENOENT' });
  });

  it('should prune nested managed directories deepest first', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-prune-nested-');
    const nestedDirectory = join(project, '.github', 'hooks', 'generated');
    const obsoleteFile = join(nestedDirectory, 'stale.md');
    await mkdir(nestedDirectory, { recursive: true });
    await writeFile(obsoleteFile, `${GENERATED_MARKER}\n\n# Stale\n`);
    const outputs = new Map<string, FormatterOutput>([
      [
        'AGENTS.md',
        {
          path: 'AGENTS.md',
          content: '# Current\n',
          managedOutputDirectories: ['.github/hooks', '.github/hooks/generated'],
        },
      ],
    ]);

    await expect(cleanupManagedOutputs(outputs, { outputRoot: project })).resolves.toEqual({
      removed: [obsoleteFile],
      removedDirectories: [nestedDirectory, dirname(nestedDirectory)],
    });
  });

  it('should keep managed directories containing unmanaged nested directories', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-prune-unmanaged-');
    const hooksDirectory = join(project, '.github', 'hooks');
    const obsoleteFile = join(hooksDirectory, 'promptscript.json');
    await mkdir(join(hooksDirectory, 'team'), { recursive: true });
    await writeFile(obsoleteFile, `${GENERATED_MARKER}\n`);
    await writeFile(join(hooksDirectory, 'team', 'rules.json'), '{}\n');

    const outputs = new Map<string, FormatterOutput>([
      [
        'AGENTS.md',
        {
          path: 'AGENTS.md',
          content: '# Current\n',
          managedOutputDirectories: ['.github/hooks'],
          managedOutputFiles: ['.github/hooks/promptscript.json'],
        },
      ],
    ]);

    await expect(cleanupManagedOutputs(outputs, { outputRoot: project })).resolves.toEqual({
      removed: [obsoleteFile],
      removedDirectories: [],
    });
    await expect(readFile(join(hooksDirectory, 'team', 'rules.json'), 'utf-8')).resolves.toBe(
      '{}\n'
    );
  });

  it('should keep a parent when a managed child directory is not empty', async () => {
    const project = await createTemporaryDirectory('promptscript-cleanup-prune-child-user-');
    const nestedDirectory = join(project, '.github', 'hooks', 'team');
    const obsoleteFile = join(project, '.github', 'hooks', 'promptscript.json');
    await mkdir(nestedDirectory, { recursive: true });
    await writeFile(obsoleteFile, `${GENERATED_MARKER}\n`);
    await writeFile(join(nestedDirectory, 'rules.json'), '{}\n');

    const outputs = new Map<string, FormatterOutput>([
      [
        'AGENTS.md',
        {
          path: 'AGENTS.md',
          content: '# Current\n',
          managedOutputDirectories: ['.github/hooks', '.github/hooks/team'],
          managedOutputFiles: ['.github/hooks/promptscript.json'],
        },
      ],
    ]);

    await expect(cleanupManagedOutputs(outputs, { outputRoot: project })).resolves.toEqual({
      removed: [obsoleteFile],
      removedDirectories: [],
    });
  });

  it('should keep a managed directory that still contains user files', async () => {
    // Arrange
    const project = await createTemporaryDirectory('promptscript-cleanup-keep-hooks-');
    const hooksDirectory = join(project, '.github', 'hooks');
    const obsoleteFile = join(hooksDirectory, 'promptscript.json');
    await mkdir(hooksDirectory, { recursive: true });
    await writeFile(
      obsoleteFile,
      '{"version":1,"hooks":{"preToolUse":[{"type":"command","bash":"echo ok # promptscript-generated:test"}]}}\n'
    );
    await writeFile(join(hooksDirectory, 'team.json'), '{"version":1,"hooks":{}}\n');
    const outputs = new Map<string, FormatterOutput>([
      [
        'AGENTS.md',
        {
          path: 'AGENTS.md',
          content: '# Current\n',
          managedOutputDirectories: ['.github/hooks'],
          managedOutputFiles: ['.github/hooks/promptscript.json'],
        },
      ],
    ]);

    // Act
    const result = await cleanupManagedOutputs(outputs, { outputRoot: project });

    // Assert
    expect(result.removed).toEqual([obsoleteFile]);
    expect(result.removedDirectories).toEqual([]);
    await expect(lstat(hooksDirectory)).resolves.toBeDefined();
  });

  it('should report prunable directories in dry-run mode without removing them', async () => {
    // Arrange
    const project = await createTemporaryDirectory('promptscript-cleanup-prune-dry-');
    const hooksDirectory = join(project, '.github', 'hooks');
    const obsoleteFile = join(hooksDirectory, 'promptscript.json');
    await mkdir(hooksDirectory, { recursive: true });
    await writeFile(
      obsoleteFile,
      '{"version":1,"hooks":{"preToolUse":[{"type":"command","bash":"echo ok # promptscript-generated:test"}]}}\n'
    );
    const outputs = new Map<string, FormatterOutput>([
      [
        'AGENTS.md',
        {
          path: 'AGENTS.md',
          content: '# Current\n',
          managedOutputDirectories: ['.github/hooks'],
          managedOutputFiles: ['.github/hooks/promptscript.json'],
        },
      ],
    ]);

    // Act
    const result = await cleanupManagedOutputs(outputs, { outputRoot: project, dryRun: true });

    // Assert
    expect(result.removed).toEqual([obsoleteFile]);
    expect(result.removedDirectories).toEqual([hooksDirectory]);
    await expect(readFile(obsoleteFile, 'utf-8')).resolves.toContain('promptscript-generated');
    await expect(lstat(hooksDirectory)).resolves.toBeDefined();
  });

  it('should never prune the output root itself', async () => {
    // Arrange
    const project = await createTemporaryDirectory('promptscript-cleanup-prune-root-');
    const staleFile = join(project, 'stale.md');
    await writeFile(staleFile, `${GENERATED_MARKER}\n\n# Stale\n`);
    const outputs = new Map<string, FormatterOutput>([
      [
        'AGENTS.md',
        {
          path: 'AGENTS.md',
          content: '# AGENTS.md\n',
          managedOutputDirectories: ['.'],
        },
      ],
    ]);

    // Act
    const result = await cleanupManagedOutputs(outputs, { outputRoot: project });

    // Assert
    expect(result.removed).toEqual([staleFile]);
    expect(result.removedDirectories).toEqual([]);
    await expect(lstat(project)).resolves.toBeDefined();
  });

  describe('removeIfUnchanged fallback', () => {
    it('should remove a regular file whose identity is unchanged', async () => {
      const directory = await createTemporaryDirectory('promptscript-remove-ok-');
      const file = join(directory, 'generated.md');
      await writeFile(file, `${GENERATED_MARKER}\n`);
      const stat = await lstat(file);

      await expect(removeIfUnchanged(file, { dev: stat.dev, ino: stat.ino })).resolves.toBe(true);
      await expect(readFile(file, 'utf-8')).rejects.toMatchObject({ code: 'ENOENT' });
    });

    it('should keep a file whose identity no longer matches', async () => {
      const directory = await createTemporaryDirectory('promptscript-remove-mismatch-');
      const file = join(directory, 'generated.md');
      await writeFile(file, `${GENERATED_MARKER}\n`);

      await expect(removeIfUnchanged(file, { dev: 0, ino: 0 })).resolves.toBe(false);
      await expect(readFile(file, 'utf-8')).resolves.toContain('PromptScript');
    });

    it('should ignore a missing entry', async () => {
      const directory = await createTemporaryDirectory('promptscript-remove-missing-');

      await expect(
        removeIfUnchanged(join(directory, 'absent.md'), { dev: 1, ino: 1 })
      ).resolves.toBe(false);
    });

    it('should ignore directories and symlinks', async () => {
      const directory = await createTemporaryDirectory('promptscript-remove-nonfile-');
      const nested = join(directory, 'nested');
      await mkdir(nested);
      const directoryStat = await lstat(nested);
      await expect(
        removeIfUnchanged(nested, { dev: directoryStat.dev, ino: directoryStat.ino })
      ).resolves.toBe(false);

      const target = join(directory, 'target.md');
      await writeFile(target, `${GENERATED_MARKER}\n`);
      const link = join(directory, 'link.md');
      await symlink(target, link, 'file');
      const linkStat = await lstat(link);
      await expect(removeIfUnchanged(link, { dev: linkStat.dev, ino: linkStat.ino })).resolves.toBe(
        false
      );
      await expect(readFile(target, 'utf-8')).resolves.toContain('PromptScript');
    });
  });

  async function createTemporaryDirectory(prefix: string): Promise<string> {
    const directory = await mkdtemp(join(tmpdir(), prefix));
    temporaryDirectories.push(directory);
    return directory;
  }
});

function createMonolithOutputs(): Map<string, FormatterOutput> {
  return new Map([
    [
      'AGENTS.md',
      {
        path: 'AGENTS.md',
        content: '# AGENTS.md\n',
        managedOutputDirectories: ['.factory/rules'],
      },
    ],
  ]);
}
